package services;

import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import static org.junit.jupiter.api.Assertions.*;

class EmploymentApplicationServiceTest {
    @Test void submissionDoesNotRequireRemovedWorkPreferences(){var f=form();f.remove("availability");f.remove("startDate");f.remove("preferredStores");assertDoesNotThrow(()->EmploymentApplicationService.validateForm(f,true));}
    static JsonObject form(){JsonObject f=new JsonObject();f.addProperty("firstName","Alex");f.addProperty("lastName","Example");f.addProperty("phone","6001234");f.addProperty("dateOfBirth","2000-01-01");f.addProperty("availability","Flexible");f.addProperty("startDate","Not sure yet");f.addProperty("declaration",true);return f;}
    static byte[] image()throws Exception{var out=new ByteArrayOutputStream();javax.imageio.ImageIO.write(new java.awt.image.BufferedImage(10,10,java.awt.image.BufferedImage.TYPE_INT_RGB),"png",out);return out.toByteArray();}
    @Test void draftCanBeIncompleteButSubmissionRequiresDobAndDeclaration(){assertEquals(0,EmploymentApplicationService.validateForm(new JsonObject(),false).size());assertDoesNotThrow(()->EmploymentApplicationService.validateForm(form(),true));var f=form();f.remove("dateOfBirth");assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateForm(f,true));f.addProperty("dateOfBirth",LocalDate.now().plusDays(1).toString());assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateForm(f,true));f.addProperty("dateOfBirth","2000-01-01");f.addProperty("declaration",false);assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateForm(f,true));}
    @Test void formCannotSetOwnershipOrEmployeePermissions(){var f=form();f.addProperty("auth_user_id","attacker");f.addProperty("role","ADMIN");f.addProperty("status","APPROVED");var clean=EmploymentApplicationService.validateForm(f,true);assertFalse(clean.has("auth_user_id"));assertFalse(clean.has("role"));assertFalse(clean.has("status"));}
    @Test void documentIsOptionalAndQuotaIncludesTenthFile(){assertDoesNotThrow(()->EmploymentApplicationService.validateQuota(0,0,100));assertDoesNotThrow(()->EmploymentApplicationService.validateQuota(9,49L*1024*1024,1024*1024));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateQuota(10,100,100));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateQuota(2,50L*1024*1024,1));}
    @Test void validatesActualFileDataAndPdfPageLimit()throws Exception{assertEquals("image/png",EmploymentApplicationService.validateDocument(image()).type());assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateDocument("not an image".getBytes()));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateDocument(new byte[10*1024*1024+1]));try(var pdf=new org.apache.pdfbox.pdmodel.PDDocument()){for(int i=0;i<21;i++)pdf.addPage(new org.apache.pdfbox.pdmodel.PDPage());var out=new ByteArrayOutputStream();pdf.save(out);assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateDocument(out.toByteArray()));}}
    @Test void requestsNeedMessageAndApplicantsCannotHireThemselves(){assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateTransition("PENDING","INFORMATION_REQUESTED",true,""));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateTransition("PENDING","APPROVED",false,""));assertDoesNotThrow(()->EmploymentApplicationService.validateTransition("PENDING","WITHDRAWN",false,""));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateTransition("APPROVING","WITHDRAWN",false,""));assertThrows(IllegalArgumentException.class,()->EmploymentApplicationService.validateTransition("REJECTED","INTERVIEW",true,""));assertDoesNotThrow(()->EmploymentApplicationService.validateTransition("REJECTED","INFORMATION_REQUESTED",true,"Please update your availability."));}
    @Test void publicOriginRejectsPathsCredentialsAndNonHttps(){assertEquals("https://jobs.example.com",EmploymentPortalConfig.validateOrigin("https://jobs.example.com/"));for(String bad:new String[]{null,"http://jobs.example.com","https://user:password@example.com","https://example.com/register","https://example.com?next=x","https://example.com#x"})assertThrows(IllegalStateException.class,()->EmploymentPortalConfig.validateOrigin(bad));}
}
