package services;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import models.CashDrawerContext;
import managers.ServerReceiptNumberManager;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/** Service-role coordinated, immediately paid cross-store return workflow. */
final class CrossStoreRefundService {
    private static final Gson GSON=new Gson();
    private static final Set<String> METHODS=Set.of("CASH","CARD","CHEQUE","MMG","ACCOUNT","BANK_TRANSFER");
    private CrossStoreRefundService(){}

    static Map<String,Object> refund(Connection c,JsonObject body,UUID deviceId,int userId,String userName,
                                     int receivingLocationId,LanRefundService.ApprovalConsumer approvalConsumer)throws Exception{
        requirePair(c,userId);SyncSchemaInstaller.ensureSchema(c);Request request=GSON.fromJson(body,Request.class);validate(request,receivingLocationId);
        Map<Integer,CachedLine> cached=loadLines(c,request.sourceLocationId(),request.saleId());BigDecimal total=BigDecimal.ZERO;
        JsonArray cloudLines=new JsonArray();
        for(Line line:request.lines()){
            CachedLine item=cached.get(line.saleItemId());if(item==null||line.quantity()<=0||line.quantity()>item.available())throw rule(409,"RETURN_QUANTITY_CHANGED","A selected quantity is no longer available in synchronized data.",false);
            if("RESTOCK".equals(line.disposition())&&(line.destinationLocationId()==null||line.destinationLocationId()<=0))throw rule(400,"DESTINATION_REQUIRED","Select a destination store for each restocked item.",false);
            if(!Set.of("RESTOCK","DISCARD").contains(line.disposition()))throw rule(400,"INVALID_DISPOSITION","Each item must be restocked or discarded.",false);
            BigDecimal amount=item.unitPrice().multiply(BigDecimal.valueOf(line.quantity())).setScale(2,RoundingMode.HALF_UP);total=total.add(amount);
            JsonObject row=new JsonObject();row.addProperty("source_sale_item_id",line.saleItemId());row.addProperty("product_id",item.productId());row.addProperty("quantity",line.quantity());row.addProperty("unit_price",item.unitPrice());row.addProperty("disposition",line.disposition());
            if(line.destinationLocationId()!=null)row.addProperty("destination_location_id",line.destinationLocationId());row.addProperty("disposition_reason",line.dispositionReason());cloudLines.add(row);
        }
        total=total.setScale(2,RoundingMode.HALF_UP);if(total.signum()<=0)throw rule(400,"INVALID_RETURN","Return total must be greater than zero.",false);
        enforceApproval(c,userId,userName,receivingLocationId,request,total,approvalConsumer);
        CashDrawerContext drawer=new CashDrawerContext(null,null);String method=request.refundMethod().trim().toUpperCase();
        if("CASH".equals(method)){drawer=CashDrawerService.resolveDrawerForDevice(c,receivingLocationId,deviceId.toString());if(!drawer.isAssigned())throw rule(409,"CASH_DRAWER_REQUIRED","This register is not assigned to an active cash drawer.",false);if(!drawer.hasActiveSession())throw rule(409,"CASH_SESSION_REQUIRED","No active draw session is open.",false);}
        ServerReceiptNumberManager.ReturnNumber returnNumber=ServerReceiptNumberManager.nextReturn(c,receivingLocationId,deviceId);
        UUID requestId=request.requestId();JsonObject payload=new JsonObject();payload.addProperty("request_id",requestId.toString());payload.addProperty("source_location_id",request.sourceLocationId());payload.addProperty("receiving_location_id",receivingLocationId);payload.addProperty("source_sale_id",request.saleId());payload.addProperty("refund_method",method);payload.addProperty("refund_amount",total);payload.addProperty("reason",request.reason().trim());payload.addProperty("return_receipt_number",returnNumber.returnReceiptNumber());payload.addProperty("receipt_device_id",returnNumber.deviceId());payload.addProperty("receipt_sequence",returnNumber.sequence());payload.add("lines",cloudLines);
        JsonObject actor=new JsonObject();actor.addProperty("user_id",userId);actor.addProperty("user_name",userName);actor.addProperty("device_id",deviceId.toString());payload.add("actor",actor);
        JsonObject rpc=new JsonObject();rpc.add("p_request",payload);JsonObject reserved=rpc("smartstock_reserve_cross_store_refund",rpc,"Cross-store refund reservation");long sequence=reserved.get("requestSequence").getAsLong();
        try(PreparedStatement ps=c.prepareStatement("""
          INSERT INTO cross_store_refund_requests(request_id,source_location_id,receiving_location_id,source_sale_id,cloud_request_sequence,refund_method,refund_amount,reason,status,user_id,user_name,device_id,cash_drawer_id,cash_drawer_session_id,return_receipt_number,receipt_device_id,receipt_sequence)
          VALUES(?,?,?,?,?,?,?,?, 'PAID_PENDING_SOURCE',?,?,?,?,?,?,?,?,?) ON CONFLICT(request_id) DO NOTHING
          """)){ps.setObject(1,requestId);ps.setInt(2,request.sourceLocationId());ps.setInt(3,receivingLocationId);ps.setInt(4,request.saleId());ps.setLong(5,sequence);ps.setString(6,method);ps.setBigDecimal(7,total);ps.setString(8,request.reason().trim());ps.setInt(9,userId);ps.setString(10,userName);ps.setObject(11,deviceId);setLong(ps,12,drawer.cashDrawerId());setLong(ps,13,drawer.sessionId());ps.setString(14,returnNumber.returnReceiptNumber());ps.setString(15,returnNumber.deviceId());ps.setInt(16,returnNumber.sequence());ps.executeUpdate();}
        try(PreparedStatement ps=c.prepareStatement("""
          INSERT INTO cross_store_refund_lines(request_id,source_sale_item_id,product_id,quantity,unit_price,disposition,destination_location_id,disposition_reason)
          VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(request_id,source_sale_item_id) DO NOTHING
          """)){for(Line line:request.lines()){CachedLine item=cached.get(line.saleItemId());ps.setObject(1,requestId);ps.setInt(2,line.saleItemId());ps.setInt(3,item.productId());ps.setInt(4,line.quantity());ps.setBigDecimal(5,item.unitPrice());ps.setString(6,line.disposition());setInteger(ps,7,line.destinationLocationId());ps.setString(8,line.dispositionReason());ps.addBatch();}ps.executeBatch();}
        audit(c,deviceId,userId,"CROSS_STORE_REFUND_PAID","request_id="+requestId+"; source_location_id="+request.sourceLocationId()+"; sale_id="+request.saleId()+"; receiving_location_id="+receivingLocationId+"; amount="+total);
        Map<String,Object> out=new LinkedHashMap<>();out.put("requestId",requestId.toString());out.put("returnId",0);out.put("returnReceiptNumber",returnNumber.returnReceiptNumber());out.put("saleId",request.saleId());out.put("sourceLocationId",request.sourceLocationId());out.put("refundAmount",total);out.put("refundMethod",method);out.put("status","PAID_PENDING_SOURCE");out.put("approvalRequired",approvalRequired(c,receivingLocationId,total));out.put("approvedByName","");return out;
    }

    static QueueResult synchronize(Connection c,int locationId)throws SQLException{
        SyncSchemaInstaller.ensureSchema(c);JsonObject body=new JsonObject();body.addProperty("p_location_id",locationId);JsonObject queue;
        try{queue=rpc("smartstock_cross_store_refund_queue",body,"Cross-store refund queue");}catch(Exception ex){throw new SQLException("Cross-store refund queue could not be synchronized.",ex);}
        JsonArray requests=queue.getAsJsonArray("requests");int sourced=0,destinations=0,conflicts=0;if(requests==null)return new QueueResult(0,0,0);
        for(JsonElement element:requests){JsonObject envelope=element.getAsJsonObject();JsonObject q=envelope.getAsJsonObject("request");JsonArray lines=envelope.getAsJsonArray("lines");UUID id=UUID.fromString(q.get("request_id").getAsString());upsertLocal(c,q,lines);
            if(q.get("source_location_id").getAsInt()==locationId&&!sourceApplied(c,id)){ApplyResult applied=applySource(c,q,lines,locationId);updateCloud(id,applied.status(),applied.lines(),applied.error());sourced++;conflicts+=applied.conflicts();}
            destinations+=applyDestinations(c,id,lines,locationId);
        }return new QueueResult(sourced,destinations,conflicts);
    }

    private static ApplyResult applySource(Connection c,JsonObject q,JsonArray lines,int locationId)throws SQLException{
        UUID id=UUID.fromString(q.get("request_id").getAsString());int saleId=q.get("source_sale_id").getAsInt();int receiving=q.get("receiving_location_id").getAsInt();BigDecimal paid=q.get("refund_amount").getAsBigDecimal();JsonArray updates=new JsonArray();int conflicts=0;long returnId;
        try(PreparedStatement lock=c.prepareStatement("SELECT sale_id FROM sales WHERE sale_id=? AND location_id=? FOR UPDATE")){lock.setInt(1,saleId);lock.setInt(2,locationId);try(ResultSet rs=lock.executeQuery()){if(!rs.next())return new ApplyResult("CONFLICT_REVIEW",updates,lines.size(),"Source sale is unavailable.");}}
        try(PreparedStatement ps=c.prepareStatement("INSERT INTO sale_returns(sale_id,location_id,user_name,refund_method,refund_amount,reason,cross_store_request_id,receiving_location_id,return_receipt_number,receipt_device_id,receipt_sequence) VALUES(?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){
            ps.setInt(1,saleId);ps.setInt(2,locationId);ps.setString(3,"Multistore / "+q.getAsJsonObject("actor").get("user_name").getAsString());ps.setString(4,q.get("refund_method").getAsString());ps.setBigDecimal(5,paid);ps.setString(6,q.get("reason").getAsString());ps.setObject(7,id);ps.setInt(8,receiving);ps.setString(9,q.get("return_receipt_number").getAsString());ps.setString(10,q.get("receipt_device_id").getAsString());ps.setInt(11,q.get("receipt_sequence").getAsInt());ps.executeUpdate();try(ResultSet keys=ps.getGeneratedKeys()){keys.next();returnId=keys.getLong(1);}}
        for(JsonElement e:lines){JsonObject line=e.getAsJsonObject();int item=line.get("source_sale_item_id").getAsInt(),requested=line.get("quantity").getAsInt(),available=available(c,item),confirmed=Math.min(requested,Math.max(0,available)),conflict=requested-confirmed;conflicts+=conflict;
            if(confirmed>0)try(PreparedStatement ps=c.prepareStatement("INSERT INTO sale_return_items(return_id,sale_item_id,product_id,quantity,unit_price) VALUES(?,?,?,?,?)")){ps.setLong(1,returnId);ps.setInt(2,item);ps.setInt(3,line.get("product_id").getAsInt());ps.setInt(4,confirmed);ps.setBigDecimal(5,line.get("unit_price").getAsBigDecimal());ps.executeUpdate();}
            if(conflict>0)reconciliation(c,id,item,locationId,receiving,line.get("product_id").getAsInt(),conflict,line.get("unit_price").getAsBigDecimal().multiply(BigDecimal.valueOf(conflict)),"Paid cross-store return exceeded remaining source quantity.");
            JsonObject u=new JsonObject();u.addProperty("source_sale_item_id",item);u.addProperty("source_status",conflict>0?"CONFLICT":"CONFIRMED");u.addProperty("confirmed_quantity",confirmed);u.addProperty("conflict_quantity",conflict);updates.add(u);
        }
        try(PreparedStatement ps=c.prepareStatement("UPDATE sales SET returned_amount=COALESCE(returned_amount,0)+? WHERE sale_id=? AND location_id=?")){ps.setBigDecimal(1,paid);ps.setInt(2,saleId);ps.setInt(3,locationId);ps.executeUpdate();}
        String status=conflicts>0?"CONFLICT_REVIEW":"CONFIRMED";try(PreparedStatement ps=c.prepareStatement("UPDATE cross_store_refund_requests SET status=?,updated_at=CURRENT_TIMESTAMP WHERE request_id=?")){ps.setString(1,status);ps.setObject(2,id);ps.executeUpdate();}return new ApplyResult(status,updates,conflicts,null);
    }

    private static int applyDestinations(Connection c,UUID id,JsonArray lines,int locationId)throws SQLException{int applied=0;for(JsonElement e:lines){JsonObject line=e.getAsJsonObject();if(!"RESTOCK".equals(line.get("disposition").getAsString())||!line.has("destination_location_id")||line.get("destination_location_id").isJsonNull()||line.get("destination_location_id").getAsInt()!=locationId||!line.has("confirmed_quantity")||line.get("confirmed_quantity").getAsInt()<=0||"APPLIED".equals(line.get("destination_status").getAsString()))continue;int qty=line.get("confirmed_quantity").getAsInt();int product=line.get("product_id").getAsInt();try(PreparedStatement ensure=c.prepareStatement("INSERT INTO inventory(product_id,location_id,quantity_on_hand,reorder_level) VALUES(?,?,0,0) ON CONFLICT(product_id,location_id) DO NOTHING");PreparedStatement update=c.prepareStatement("UPDATE inventory SET quantity_on_hand=quantity_on_hand+? WHERE product_id=? AND location_id=?");PreparedStatement movement=c.prepareStatement("INSERT INTO inventory_movements(product_id,location_id,change_qty,reason,note) VALUES(?,?,?,'CROSS_STORE_RETURN',?)")){ensure.setInt(1,product);ensure.setInt(2,locationId);ensure.executeUpdate();update.setInt(1,qty);update.setInt(2,product);update.setInt(3,locationId);update.executeUpdate();movement.setInt(1,product);movement.setInt(2,locationId);movement.setInt(3,qty);movement.setString(4,"request_id="+id);movement.executeUpdate();}
          try(PreparedStatement ps=c.prepareStatement("UPDATE cross_store_refund_lines SET destination_status='APPLIED' WHERE request_id=? AND source_sale_item_id=? AND destination_status<>'APPLIED'")){ps.setObject(1,id);ps.setInt(2,line.get("source_sale_item_id").getAsInt());if(ps.executeUpdate()==1){JsonObject u=new JsonObject();u.addProperty("source_sale_item_id",line.get("source_sale_item_id").getAsInt());u.addProperty("destination_status","APPLIED");JsonArray one=new JsonArray();one.add(u);updateCloud(id,"DESTINATION_PENDING",one,null);applied++;}}}
        return applied;}

    private static void upsertLocal(Connection c,JsonObject q,JsonArray lines)throws SQLException{UUID id=UUID.fromString(q.get("request_id").getAsString());try(PreparedStatement ps=c.prepareStatement("INSERT INTO cross_store_refund_requests(request_id,source_location_id,receiving_location_id,source_sale_id,cloud_request_sequence,refund_method,refund_amount,reason,status,user_name,return_receipt_number,receipt_device_id,receipt_sequence) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(request_id) DO UPDATE SET status=EXCLUDED.status,last_error=?")){ps.setObject(1,id);ps.setInt(2,q.get("source_location_id").getAsInt());ps.setInt(3,q.get("receiving_location_id").getAsInt());ps.setInt(4,q.get("source_sale_id").getAsInt());ps.setLong(5,q.get("request_sequence").getAsLong());ps.setString(6,q.get("refund_method").getAsString());ps.setBigDecimal(7,q.get("refund_amount").getAsBigDecimal());ps.setString(8,q.get("reason").getAsString());ps.setString(9,q.get("status").getAsString());ps.setString(10,q.getAsJsonObject("actor").has("user_name")?q.getAsJsonObject("actor").get("user_name").getAsString():"");ps.setString(11,q.get("return_receipt_number").getAsString());ps.setString(12,q.get("receipt_device_id").getAsString());ps.setInt(13,q.get("receipt_sequence").getAsInt());ps.setString(14,q.has("source_error")&&!q.get("source_error").isJsonNull()?q.get("source_error").getAsString():null);ps.executeUpdate();}
      try(PreparedStatement ps=c.prepareStatement("INSERT INTO cross_store_refund_lines(request_id,source_sale_item_id,product_id,quantity,unit_price,disposition,destination_location_id,disposition_reason,confirmed_quantity,conflict_quantity,destination_status) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(request_id,source_sale_item_id) DO UPDATE SET confirmed_quantity=EXCLUDED.confirmed_quantity,conflict_quantity=EXCLUDED.conflict_quantity,destination_status=EXCLUDED.destination_status")){for(JsonElement e:lines){JsonObject l=e.getAsJsonObject();ps.setObject(1,id);ps.setInt(2,l.get("source_sale_item_id").getAsInt());ps.setInt(3,l.get("product_id").getAsInt());ps.setInt(4,l.get("quantity").getAsInt());ps.setBigDecimal(5,l.get("unit_price").getAsBigDecimal());ps.setString(6,l.get("disposition").getAsString());if(!l.has("destination_location_id")||l.get("destination_location_id").isJsonNull())ps.setNull(7,Types.INTEGER);else ps.setInt(7,l.get("destination_location_id").getAsInt());ps.setString(8,l.has("disposition_reason")&&!l.get("disposition_reason").isJsonNull()?l.get("disposition_reason").getAsString():null);ps.setInt(9,l.get("confirmed_quantity").getAsInt());ps.setInt(10,l.get("conflict_quantity").getAsInt());ps.setString(11,l.get("destination_status").getAsString());ps.addBatch();}ps.executeBatch();}}
    private static void updateCloud(UUID id,String status,JsonArray lines,String error)throws SQLException{JsonObject b=new JsonObject();b.addProperty("p_request_id",id.toString());b.addProperty("p_status",status);b.add("p_lines",lines);if(error!=null)b.addProperty("p_error",error);try{rpc("smartstock_update_cross_store_refund",b,"Cross-store refund acknowledgement");}catch(Exception ex){throw new SQLException("Cross-store refund acknowledgement failed.",ex);}}
    private static boolean sourceApplied(Connection c,UUID id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT 1 FROM sale_returns WHERE cross_store_request_id=?")){ps.setObject(1,id);try(ResultSet rs=ps.executeQuery()){return rs.next();}}}private static int available(Connection c,int item)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT si.quantity-COALESCE((SELECT SUM(sri.quantity) FROM sale_return_items sri WHERE sri.sale_item_id=si.sale_item_id),0) FROM sale_items si WHERE si.sale_item_id=? AND NOT si.is_misc_item FOR UPDATE OF si")){ps.setInt(1,item);try(ResultSet rs=ps.executeQuery()){return rs.next()?rs.getInt(1):0;}}}
    private static void reconciliation(Connection c,UUID id,int item,int source,int receiving,int product,int qty,BigDecimal loss,String detail)throws SQLException{try(PreparedStatement ps=c.prepareStatement("INSERT INTO cross_store_refund_reconciliation(request_id,source_sale_item_id,source_location_id,receiving_location_id,product_id,conflict_quantity,financial_loss,detail) VALUES(?,?,?,?,?,?,?,?)")){ps.setObject(1,id);ps.setInt(2,item);ps.setInt(3,source);ps.setInt(4,receiving);ps.setInt(5,product);ps.setInt(6,qty);ps.setBigDecimal(7,loss);ps.setString(8,detail);ps.executeUpdate();}}
    private static Map<Integer,CachedLine> loadLines(Connection c,int loc,int sale)throws SQLException{Map<Integer,CachedLine> out=new LinkedHashMap<>();try(PreparedStatement ps=c.prepareStatement("SELECT i.sale_item_id,i.product_id,i.quantity-COALESCE((SELECT SUM(r.quantity) FROM sync_cross_store_return_items_cache r WHERE r.source_location_id=i.source_location_id AND r.sale_item_id=i.sale_item_id),0),i.unit_price FROM sync_cross_store_sale_items_cache i WHERE i.source_location_id=? AND i.sale_id=? AND NOT i.is_misc_item")){ps.setInt(1,loc);ps.setInt(2,sale);try(ResultSet rs=ps.executeQuery()){while(rs.next())out.put(rs.getInt(1),new CachedLine(rs.getInt(2),rs.getInt(3),rs.getBigDecimal(4)));}}return out;}
    private static void enforceApproval(Connection c,int user,String name,int locationId,Request r,BigDecimal total,LanRefundService.ApprovalConsumer consumer)throws Exception{BigDecimal limit=limit(c,locationId);if(limit.signum()>0&&total.compareTo(limit)>0&&!has(c,user,"RETURN_OVERRIDE")){String identity=RefundApprovalIdentity.build(r.saleId(),total,r.lines().stream().collect(java.util.stream.Collectors.toMap(Line::saleItemId,Line::quantity)));consumer.consume(r.approvalToken(),"RETURN_OVERRIDE","Multistore Return Override",r.approvalReason(),identity);}}
    private static boolean approvalRequired(Connection c,int loc,BigDecimal total)throws SQLException{BigDecimal l=limit(c,loc);return l.signum()>0&&total.compareTo(l)>0;}private static BigDecimal limit(Connection c,int locationId)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT COALESCE(sale_return_approval_limit,0) FROM company_customization WHERE location_id=?")){ps.setInt(1,locationId);try(ResultSet rs=ps.executeQuery()){return rs.next()?rs.getBigDecimal(1):BigDecimal.ZERO;}}}
    private static void requirePair(Connection c,int user)throws Exception{if(!has(c,user,"PROCESS_RETURNS")||!has(c,user,"PROCESS_MULTI_STORE_RETURNS"))throw rule(403,"PERMISSION_DENIED","Both local and multistore return permissions are required.",false);}private static boolean has(Connection c,int u,String k)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT 1 FROM users x JOIN role_permissions rp ON rp.role_id=x.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE x.user_id=? AND UPPER(p.permission_key)=? LIMIT 1")){ps.setInt(1,u);ps.setString(2,k);try(ResultSet rs=ps.executeQuery()){return rs.next();}}}
    private static JsonObject rpc(String name,JsonObject body,String label)throws IOException,InterruptedException{SupabaseServerApi.Response response=SupabaseServerApi.postRpc(name,body);if(!response.successful())throw new IOException(SupabaseServerApi.failureMessage(label,response));return JsonParser.parseString(response.body()).getAsJsonObject();}
    private static void audit(Connection c,UUID device,int user,String type,String details)throws SQLException{try(PreparedStatement ps=c.prepareStatement("INSERT INTO security_audit_events(event_type,device_id,actor_user_id,details) VALUES(?,?,?,?)")){ps.setString(1,type);ps.setObject(2,device);ps.setInt(3,user);ps.setString(4,details);ps.executeUpdate();}}
    private static void validate(Request r,int receiving)throws RuleViolation{if(r==null||r.requestId()==null||r.sourceLocationId()<=0||r.sourceLocationId()==receiving||r.saleId()<=0||r.lines()==null||r.lines().isEmpty()||r.lines().size()>200)throw rule(400,"VALIDATION_ERROR","A valid multistore return request is required.",false);if(r.refundMethod()==null||!METHODS.contains(r.refundMethod().trim().toUpperCase()))throw rule(400,"VALIDATION_ERROR","Unsupported refund method.",false);if(r.reason()==null||r.reason().isBlank()||r.reason().length()>2000)throw rule(400,"VALIDATION_ERROR","A return reason is required.",false);for(Line line:r.lines()){String d=line.disposition()==null?"":line.disposition().trim().toUpperCase();if(!Set.of("RESTOCK","DISCARD").contains(d))throw rule(400,"DISPOSITION_REQUIRED","Choose restock or discard for every returned item.",false);if("DISCARD".equals(d)&&(line.dispositionReason()==null||line.dispositionReason().isBlank()))throw rule(400,"DISCARD_REASON_REQUIRED","A discard reason is required.",false);}}
    private static void setInteger(PreparedStatement p,int i,Integer v)throws SQLException{if(v==null)p.setNull(i,Types.INTEGER);else p.setInt(i,v);}private static void setLong(PreparedStatement p,int i,Long v)throws SQLException{if(v==null)p.setNull(i,Types.BIGINT);else p.setLong(i,v);}private static RuleViolation rule(int s,String c,String m,boolean r){return new RuleViolation(s,c,m,r);}
    private record Request(UUID requestId,int sourceLocationId,int saleId,String refundMethod,String reason,String approvalToken,String approvalReason,List<Line>lines){}private record Line(int saleItemId,int quantity,String disposition,Integer destinationLocationId,String dispositionReason){}private record CachedLine(int productId,int available,BigDecimal unitPrice){}private record ApplyResult(String status,JsonArray lines,int conflicts,String error){}record QueueResult(int sourceApplied,int destinationsApplied,int conflicts){}
    static final class RuleViolation extends Exception{private final int status;private final String code;private final boolean retryable;RuleViolation(int s,String c,String m,boolean r){super(m);status=s;code=c;retryable=r;}int status(){return status;}String code(){return code;}String safeMessage(){return getMessage();}boolean retryable(){return retryable;}}
}
