package services;

import java.sql.SQLException;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.random.RandomGenerator;

/** Register-safe automatic schedule facade. */
public final class EmployeeAutoScheduleService {
    private EmployeeAutoScheduleService() { }
    public enum WarningLevel{INFO,WARNING}
    public record ScheduleWarning(WarningLevel level,LocalDate workDate,Integer userId,String message){}
    public record ScheduleEntry(int userId,String displayName,String username,LocalDate workDate,UUID shiftId,String shiftName,LocalTime shiftStartTime,LocalTime shiftEndTime,LocalTime lunchStartTime,boolean proposed){}
    public record DailyCoverage(LocalDate workDate,int existingCount,int proposedCount,int totalCount,Map<String,Integer>shiftCounts){}
    public record AutoScheduleProposal(UUID proposalId,int locationId,LocalDate periodStart,LocalDate periodEnd,LocalDate fingerprintStart,LocalDate fingerprintEnd,Instant generatedAt,String assignmentFingerprint,List<ScheduleEntry>entries,List<DailyCoverage>dailyCoverage,List<ScheduleWarning>warnings){public List<ScheduleEntry>proposedEntries(){return entries.stream().filter(ScheduleEntry::proposed).toList();}}
    public static AutoScheduleProposal generate(int locationId,LocalDate start)throws SQLException{return generateRange(locationId,start,start.plusDays(6));}
    public static AutoScheduleProposal generate(int locationId,LocalDate start,RandomGenerator ignored)throws SQLException{return generate(locationId,start);}
    public static AutoScheduleProposal generateRange(int locationId,LocalDate start,LocalDate end)throws SQLException{return generateRange(locationId,start,end,(Set<Integer>)null);}
    public static AutoScheduleProposal generateRange(int locationId,LocalDate start,LocalDate end,RandomGenerator ignored)throws SQLException{return generateRange(locationId,start,end);}
    public static AutoScheduleProposal generateRange(int locationId,LocalDate start,LocalDate end,Set<Integer>employees)throws SQLException{try{return LanApiClient.generateAutoSchedule(locationId,start,end,employees);}catch(Exception e){throw new SQLException("The automatic schedule could not be generated by the SmartStock server.",e);}}
    public static AutoScheduleProposal generateRange(int locationId,LocalDate start,LocalDate end,Set<Integer>employees,RandomGenerator ignored)throws SQLException{return generateRange(locationId,start,end,employees);}
    public static int apply(AutoScheduleProposal proposal)throws SQLException{try{return LanApiClient.applyAutoSchedule(proposal,UUID.randomUUID().toString());}catch(Exception e){throw new SQLException("The automatic schedule could not be applied by the SmartStock server.",e);}}
}
