package services;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/** Server-only custom-order catalog administration with named domain operations. */
public final class LanCustomOrderCatalogAdminService {
    private static final Gson GSON=LanJson.create();
    private LanCustomOrderCatalogAdminService(){}

    public static State load(Connection c)throws SQLException{
        List<Item>items=new ArrayList<>();
        try(PreparedStatement ps=c.prepareStatement("""
                SELECT ci.custom_item_id,ci.item_name,COALESCE(ci.sku,''),COALESCE(ci.barcode,''),COALESCE(ci.description,''),COALESCE(ci.image_url,''),
                       COALESCE(ci.product_type,'INVENTORY'),COALESCE(ci.pricing_type,'VARIABLE'),ci.fixed_price,COALESCE(ci.area_price_unit,'SQ_FT'),
                       COALESCE(ci.dimension_unit,'IN'),ci.max_width,ci.max_length,COALESCE(ci.has_variants,FALSE),COALESCE(ci.quantity_on_hand,0),
                       COALESCE(ci.reorder_level,0),COALESCE(ci.is_active,TRUE),ci.category_id,COALESCE(cat.name,''),COALESCE(it.name,''),COALESCE(br.name,'')
                FROM custom_order_items ci LEFT JOIN categories cat ON cat.category_id=ci.category_id
                LEFT JOIN item_types it ON it.item_type_id=ci.item_type_id LEFT JOIN item_brands br ON br.brand_id=ci.brand_id
                ORDER BY ci.is_active DESC,ci.item_name
                """);ResultSet rs=ps.executeQuery()){while(rs.next()){long id=rs.getLong(1);Integer category=(Integer)rs.getObject(18);items.add(new Item(id,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getBigDecimal(9),rs.getString(10),rs.getString(11),rs.getBigDecimal(12),rs.getBigDecimal(13),rs.getBoolean(14),rs.getBigDecimal(15),rs.getBigDecimal(16),rs.getBoolean(17),category,rs.getString(19),rs.getString(20),rs.getString(21),barcodes(c,id),variants(c,id)));}}
        List<Material>materials=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT print_material_id,material_name,COALESCE(description,''),is_active FROM custom_order_print_materials ORDER BY is_active DESC,material_name");ResultSet rs=ps.executeQuery()){while(rs.next())materials.add(new Material(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getBoolean(4)));}
        List<Preset>presets=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT print_size_preset_id,print_material_id,preset_name,COALESCE(pricing_mode,'FIXED_PRESET'),fixed_price,is_active FROM custom_order_print_size_presets ORDER BY print_material_id,is_active DESC,preset_name");ResultSet rs=ps.executeQuery()){while(rs.next())presets.add(new Preset(rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),rs.getBigDecimal(5),rs.getBoolean(6)));}
        List<Placement>placements=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT design_placement_id,placement_name,sort_order,is_active FROM custom_order_design_placements ORDER BY is_active DESC,sort_order,placement_name");ResultSet rs=ps.executeQuery()){while(rs.next())placements.add(new Placement(rs.getLong(1),rs.getString(2),rs.getInt(3),rs.getBoolean(4)));}
        return new State(items,materials,presets,placements);
    }

    public static long mutate(Connection c,String action,JsonObject body)throws Exception{return switch(action){
        case"SAVE_ITEM"->saveItem(c,GSON.fromJson(body.get("item"),ItemSave.class));
        case"DEACTIVATE_ITEM"->{deactivate(c,"custom_order_items","custom_item_id",id(body,"itemId"));yield id(body,"itemId");}
        case"SAVE_VARIANT"->saveVariant(c,GSON.fromJson(body.get("variant"),VariantSave.class));
        case"DEACTIVATE_VARIANT"->{deactivate(c,"custom_order_item_variants","custom_variant_id",id(body,"variantId"));yield id(body,"variantId");}
        case"SAVE_MATERIAL"->saveMaterial(c,GSON.fromJson(body.get("material"),MaterialSave.class));
        case"DEACTIVATE_MATERIAL"->{deactivate(c,"custom_order_print_materials","print_material_id",id(body,"materialId"));yield id(body,"materialId");}
        case"SAVE_PRESET"->savePreset(c,GSON.fromJson(body.get("preset"),PresetSave.class));
        case"DEACTIVATE_PRESET"->{deactivate(c,"custom_order_print_size_presets","print_size_preset_id",id(body,"presetId"));yield id(body,"presetId");}
        case"SAVE_PLACEMENT"->savePlacement(c,GSON.fromJson(body.get("placement"),PlacementSave.class));
        case"DEACTIVATE_PLACEMENT"->{deactivate(c,"custom_order_design_placements","design_placement_id",id(body,"placementId"));yield id(body,"placementId");}
        default->throw new SQLException("The custom catalog action is invalid.");};}

    private static long saveItem(Connection c,ItemSave r)throws SQLException{
        if(r==null||blank(r.name()))throw new SQLException("Item name is required.");
        Set<String> requestedBarcodes=new LinkedHashSet<>(r.extraBarcodes()==null?List.of():r.extraBarcodes());
        if(!blank(r.barcode()))requestedBarcodes.add(r.barcode());
        CatalogBarcodeService.requireAvailable(c,requestedBarcodes,null,r.itemId(),null);
        String product=one(r.productType(),List.of("INVENTORY","SERVICE","NON_INVENTORY"),"INVENTORY"),pricing=one(r.pricingType(),List.of("VARIABLE","FIXED","AREA"),"VARIABLE");
        boolean variants=r.hasVariants();BigDecimal qty=variants||!"INVENTORY".equals(product)?BigDecimal.ZERO:zero(r.quantity()),reorder=variants||!"INVENTORY".equals(product)?BigDecimal.ZERO:zero(r.reorderLevel());
        BigDecimal price=variants?null:r.fixedPrice();if(!variants&&List.of("FIXED","AREA").contains(pricing)&&price==null)throw new SQLException("A price is required for fixed or area pricing.");
        if("AREA".equals(pricing)&&(positive(r.maxWidth())==false||positive(r.maxLength())==false))throw new SQLException("Area-priced items require maximum width and length greater than zero.");
        int categoryId=r.categoryId()==null?ItemDetailsService.ensureCustomDepartment(c):r.categoryId();int itemTypeId=ItemDetailsService.resolveItemType(c,categoryId,r.itemType());int brandId=ItemDetailsService.resolveBrand(c,r.brand());
        boolean update=r.itemId()!=null;String sql=update?"""
                UPDATE custom_order_items SET item_name=?,barcode=?,description=?,image_url=?,product_type=?,pricing_type=?,fixed_price=?,area_price=?,area_price_unit=?,dimension_unit=?,max_width=?,max_length=?,has_variants=?,quantity_on_hand=?,reorder_level=?,is_active=?,category_id=?,item_type_id=?,brand_id=?,updated_at=CURRENT_TIMESTAMP WHERE custom_item_id=? RETURNING custom_item_id
                """:"""
                INSERT INTO custom_order_items(item_name,barcode,description,image_url,product_type,pricing_type,fixed_price,area_price,area_price_unit,dimension_unit,max_width,max_length,has_variants,quantity_on_hand,reorder_level,is_active,category_id,item_type_id,brand_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING custom_item_id
                """;long itemId;try(PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,r.name().trim());ps.setString(2,nullIfBlank(r.barcode()));ps.setString(3,nullIfBlank(r.description()));ps.setString(4,nullIfBlank(r.imageUrl()));ps.setString(5,product);ps.setString(6,pricing);decimal(ps,7,price);decimal(ps,8,"AREA".equals(pricing)?price:null);ps.setString(9,"AREA".equals(pricing)?one(r.areaPriceUnit(),List.of("SQ_FT","SQ_IN","SQ_YD","SQ_M","SQ_CM"),"SQ_FT"):null);ps.setString(10,"AREA".equals(pricing)?one(r.dimensionUnit(),List.of("IN","FT","YD","M","CM"),"IN"):null);decimal(ps,11,"AREA".equals(pricing)?r.maxWidth():null);decimal(ps,12,"AREA".equals(pricing)?r.maxLength():null);ps.setBoolean(13,variants);ps.setBigDecimal(14,qty);ps.setBigDecimal(15,reorder);ps.setBoolean(16,r.active());ps.setInt(17,categoryId);ps.setInt(18,itemTypeId);ps.setInt(19,brandId);if(update)ps.setLong(20,r.itemId());try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Custom item was not saved.");itemId=rs.getLong(1);}}
        if(!variants&&hasVariants(c,itemId))throw new SQLException("Deactivate all variants before turning off variant tracking.");
        try(PreparedStatement ps=c.prepareStatement("DELETE FROM custom_order_item_barcodes WHERE custom_item_id=?")){ps.setLong(1,itemId);ps.executeUpdate();}
        Set<String>codes=new LinkedHashSet<>(r.extraBarcodes()==null?List.of():r.extraBarcodes());codes.removeIf(x->blank(x)||x.trim().equals(r.barcode()==null?"":r.barcode().trim()));try(PreparedStatement ps=c.prepareStatement("INSERT INTO custom_order_item_barcodes(custom_item_id,barcode) VALUES(?,?)")){for(String code:codes){ps.setLong(1,itemId);ps.setString(2,code.trim());ps.addBatch();}ps.executeBatch();}
        if(variants)refreshTotals(c,itemId);return itemId;
    }
    private static long saveVariant(Connection c,VariantSave r)throws SQLException{if(r==null||r.itemId()==null||blank(r.name()))throw new SQLException("Variant item and name are required.");Set<String>requested=new LinkedHashSet<>(r.extraBarcodes()==null?List.of():r.extraBarcodes());if(!blank(r.barcode()))requested.add(r.barcode());CatalogBarcodeService.requireAvailable(c,requested,null,null,r.variantId());boolean update=r.variantId()!=null;String sql=update?"UPDATE custom_order_item_variants SET variant_name=?,barcode=?,image_url=?,fixed_price=?,quantity_on_hand=?,reorder_level=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE custom_variant_id=? RETURNING custom_variant_id":"INSERT INTO custom_order_item_variants(custom_item_id,variant_name,barcode,image_url,fixed_price,quantity_on_hand,reorder_level,is_active) VALUES(?,?,?,?,?,?,?,?) RETURNING custom_variant_id";long id;try(PreparedStatement ps=c.prepareStatement(sql)){int i=1;if(!update)ps.setLong(i++,r.itemId());ps.setString(i++,r.name().trim());ps.setString(i++,nullIfBlank(r.barcode()));ps.setString(i++,nullIfBlank(r.imageUrl()));decimal(ps,i++,r.fixedPrice());ps.setBigDecimal(i++,zero(r.quantity()));ps.setBigDecimal(i++,zero(r.reorderLevel()));ps.setBoolean(i++,r.active());if(update)ps.setLong(i,r.variantId());try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Variant was not saved.");id=rs.getLong(1);}}try(PreparedStatement ps=c.prepareStatement("DELETE FROM custom_order_item_variant_barcodes WHERE custom_variant_id=?")){ps.setLong(1,id);ps.executeUpdate();}Set<String>codes=new LinkedHashSet<>(r.extraBarcodes()==null?List.of():r.extraBarcodes());codes.removeIf(x->blank(x)||BarcodeNormalizer.normalize(x).equals(BarcodeNormalizer.normalize(r.barcode())));try(PreparedStatement ps=c.prepareStatement("INSERT INTO custom_order_item_variant_barcodes(custom_variant_id,barcode) VALUES(?,?)")){for(String code:codes){ps.setLong(1,id);ps.setString(2,BarcodeNormalizer.normalize(code));ps.addBatch();}ps.executeBatch();}try(PreparedStatement ps=c.prepareStatement("UPDATE custom_order_items SET has_variants=TRUE,fixed_price=NULL,area_price=NULL,updated_at=CURRENT_TIMESTAMP WHERE custom_item_id=?")){ps.setLong(1,r.itemId());ps.executeUpdate();}refreshTotals(c,r.itemId());return id;}
    private static long saveMaterial(Connection c,MaterialSave r)throws SQLException{if(r==null||blank(r.name()))throw new SQLException("Material name is required.");return upsert(c,r.materialId(),"custom_order_print_materials","print_material_id","material_name=?,description=?,is_active=?",ps->{ps.setString(1,r.name().trim());ps.setString(2,nullIfBlank(r.description()));ps.setBoolean(3,r.active());},"material_name,description,is_active","?,?,?",3);}
    private static long savePreset(Connection c,PresetSave r)throws SQLException{if(r==null||r.materialId()==null||blank(r.name())||r.price()==null||r.price().signum()<0)throw new SQLException("Material, preset name, and non-negative price are required.");boolean update=r.presetId()!=null;String sql=update?"UPDATE custom_order_print_size_presets SET preset_name=?,pricing_mode=?,fixed_price=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE print_size_preset_id=? RETURNING print_size_preset_id":"INSERT INTO custom_order_print_size_presets(print_material_id,preset_name,pricing_mode,fixed_price,is_active) VALUES(?,?,?,?,?) RETURNING print_size_preset_id";try(PreparedStatement ps=c.prepareStatement(sql)){int i=1;if(!update)ps.setLong(i++,r.materialId());ps.setString(i++,r.name().trim());ps.setString(i++,one(r.pricingMode(),List.of("FIXED_PRESET","PER_LINE"),"FIXED_PRESET"));ps.setBigDecimal(i++,r.price());ps.setBoolean(i++,r.active());if(update)ps.setLong(i,r.presetId());try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Preset was not saved.");return rs.getLong(1);}}}
    private static long savePlacement(Connection c,PlacementSave r)throws SQLException{if(r==null||blank(r.name()))throw new SQLException("Placement name is required.");return upsert(c,r.placementId(),"custom_order_design_placements","design_placement_id","placement_name=?,sort_order=?,is_active=?",ps->{ps.setString(1,r.name().trim());ps.setInt(2,r.sortOrder());ps.setBoolean(3,r.active());},"placement_name,sort_order,is_active","?,?,?",3);}
    private static long upsert(Connection c,Long id,String table,String key,String assignments,Binder binder,String columns,String values,int count)throws SQLException{String sql=id==null?"INSERT INTO "+table+"("+columns+") VALUES("+values+") RETURNING "+key:"UPDATE "+table+" SET "+assignments+",updated_at=CURRENT_TIMESTAMP WHERE "+key+"=? RETURNING "+key;try(PreparedStatement ps=c.prepareStatement(sql)){binder.bind(ps);if(id!=null)ps.setLong(count+1,id);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("The record was not saved.");return rs.getLong(1);}}}
    private static void deactivate(Connection c,String table,String key,long id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("UPDATE "+table+" SET is_active=FALSE,updated_at=CURRENT_TIMESTAMP WHERE "+key+"=?")){ps.setLong(1,id);if(ps.executeUpdate()!=1)throw new SQLException("The record was not found.");}}
    private static List<String>barcodes(Connection c,long id)throws SQLException{List<String>r=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT barcode FROM custom_order_item_barcodes WHERE custom_item_id=? ORDER BY barcode")){ps.setLong(1,id);try(ResultSet rs=ps.executeQuery()){while(rs.next())r.add(rs.getString(1));}}return r;}
    private static List<Variant>variants(Connection c,long id)throws SQLException{List<Variant>r=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT custom_variant_id,COALESCE(sku,''),variant_name,COALESCE(barcode,''),COALESCE(image_url,''),fixed_price,quantity_on_hand,reorder_level,is_active FROM custom_order_item_variants WHERE custom_item_id=? ORDER BY is_active DESC,variant_name")){ps.setLong(1,id);try(ResultSet rs=ps.executeQuery()){while(rs.next()){long variantId=rs.getLong(1);r.add(new Variant(variantId,id,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getBigDecimal(6),rs.getBigDecimal(7),rs.getBigDecimal(8),rs.getBoolean(9),variantBarcodes(c,variantId)));}}}return r;}
    private static List<String>variantBarcodes(Connection c,long id)throws SQLException{List<String>r=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT barcode FROM custom_order_item_variant_barcodes WHERE custom_variant_id=? ORDER BY barcode")){ps.setLong(1,id);try(ResultSet rs=ps.executeQuery()){while(rs.next())r.add(rs.getString(1));}}return r;}
    private static boolean hasVariants(Connection c,long id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT EXISTS(SELECT 1 FROM custom_order_item_variants WHERE custom_item_id=? AND is_active=TRUE)")){ps.setLong(1,id);try(ResultSet rs=ps.executeQuery()){rs.next();return rs.getBoolean(1);}}}
    private static void refreshTotals(Connection c,long id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("UPDATE custom_order_items SET quantity_on_hand=COALESCE((SELECT SUM(quantity_on_hand) FROM custom_order_item_variants WHERE custom_item_id=? AND is_active),0),reorder_level=COALESCE((SELECT SUM(reorder_level) FROM custom_order_item_variants WHERE custom_item_id=? AND is_active),0),updated_at=CURRENT_TIMESTAMP WHERE custom_item_id=?")){ps.setLong(1,id);ps.setLong(2,id);ps.setLong(3,id);ps.executeUpdate();}}
    private static long id(JsonObject b,String k)throws SQLException{try{return b.get(k).getAsLong();}catch(Exception e){throw new SQLException(k+" is required.");}}
    private static boolean blank(String s){return s==null||s.isBlank();}private static String nullIfBlank(String s){return blank(s)?null:s.trim();}private static BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO:v;}private static boolean positive(BigDecimal v){return v!=null&&v.signum()>0;}private static String one(String v,List<String>a,String d){v=v==null?d:v.trim().toUpperCase();return a.contains(v)?v:d;}private static void decimal(PreparedStatement ps,int i,BigDecimal v)throws SQLException{if(v==null)ps.setNull(i,Types.NUMERIC);else ps.setBigDecimal(i,v);}
    @FunctionalInterface private interface Binder{void bind(PreparedStatement ps)throws SQLException;}
    public record State(List<Item>items,List<Material>materials,List<Preset>presets,List<Placement>placements){}
    public record Item(long itemId,String name,String sku,String barcode,String description,String imageUrl,String productType,String pricingType,BigDecimal fixedPrice,String areaPriceUnit,String dimensionUnit,BigDecimal maxWidth,BigDecimal maxLength,boolean hasVariants,BigDecimal quantity,BigDecimal reorderLevel,boolean active,Integer categoryId,String categoryName,String itemType,String brand,List<String>extraBarcodes,List<Variant>variants){}
    public record Variant(long variantId,long itemId,String sku,String name,String barcode,String imageUrl,BigDecimal fixedPrice,BigDecimal quantity,BigDecimal reorderLevel,boolean active,List<String>extraBarcodes){}
    public record Material(long materialId,String name,String description,boolean active){}public record Preset(long presetId,long materialId,String name,String pricingMode,BigDecimal price,boolean active){}public record Placement(long placementId,String name,int sortOrder,boolean active){}
    public record ItemSave(Long itemId,String name,String barcode,String description,String imageUrl,String productType,String pricingType,BigDecimal fixedPrice,String areaPriceUnit,String dimensionUnit,BigDecimal maxWidth,BigDecimal maxLength,boolean hasVariants,BigDecimal quantity,BigDecimal reorderLevel,boolean active,Integer categoryId,String itemType,String brand,List<String>extraBarcodes){}
    public record VariantSave(Long variantId,Long itemId,String name,String barcode,String imageUrl,BigDecimal fixedPrice,BigDecimal quantity,BigDecimal reorderLevel,boolean active,List<String>extraBarcodes){}public record MaterialSave(Long materialId,String name,String description,boolean active){}public record PresetSave(Long presetId,Long materialId,String name,String pricingMode,BigDecimal price,boolean active){}public record PlacementSave(Long placementId,String name,int sortOrder,boolean active){}
}
