package services;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Server-owned employee administration repository. */
public final class LanEmployeeAdminService {
    private LanEmployeeAdminService() { }
    public static State state(Connection c,Integer selectedUserId,LocalDate today)throws SQLException{
        List<String>roles=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT role_name FROM roles ORDER BY role_name");ResultSet rs=ps.executeQuery()){while(rs.next())roles.add(rs.getString(1));}
        List<Employee>employees=new ArrayList<>();String sql="""
SELECT u.user_id,u.username,u.full_name,u.first_name,u.middle_name,u.last_name,u.email,u.phone,COALESCE(u.employee_photo_url,''),u.date_of_birth,u.hire_date,u.deactivated_at::date,u.badge_id,COALESCE(u.badge_print_count,0),COALESCE(u.compensation_type,'HOURLY'),COALESCE(u.salary,0),COALESCE(r.role_name,'USER'),COALESCE(u.is_active,TRUE),COALESCE(u.employee_id_card_document_url,'') FROM users u LEFT JOIN roles r ON u.role_id=r.role_id ORDER BY u.user_id
""";
        try(PreparedStatement ps=c.prepareStatement(sql);ResultSet rs=ps.executeQuery()){while(rs.next())employees.add(new Employee(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),date(rs,10),date(rs,11),date(rs,12),rs.getString(13),rs.getInt(14),rs.getString(15),rs.getBigDecimal(16),rs.getString(17),rs.getBoolean(18),rs.getString(19)));}
        List<Store>stores=stores(c,selectedUserId);EmployeePayrollSettingsService.SettingView payroll=null;if(selectedUserId!=null){String comp=employees.stream().filter(e->e.userId()==selectedUserId).map(Employee::compensationType).findFirst().orElse("HOURLY");payroll=EmployeePayrollSettingsService.loadCurrentAndPending(c,selectedUserId,today,comp);}return new State(roles,employees,stores,payroll);
    }
    public static List<Store> stores(Connection c,Integer userId)throws SQLException{List<Store>out=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT l.location_id,l.name,COALESCE(l.address,''),EXISTS(SELECT 1 FROM user_locations ul WHERE ul.location_id=l.location_id AND ul.user_id=?) FROM locations l ORDER BY l.name")){if(userId==null)ps.setNull(1,Types.INTEGER);else ps.setInt(1,userId);try(ResultSet rs=ps.executeQuery()){while(rs.next())out.add(new Store(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getBoolean(4)));}}return out;}
    public static int create(Connection c,SaveRequest r,String authUserId,int actorId,String actorName)throws SQLException{validate(r,true);String badgeId=BadgeCredentialService.generateBadgeId();BadgeCredentialService.BadgeHash h=BadgeCredentialService.createHash(badgeId,r.dateOfBirth());String sql="""
INSERT INTO users(username,password_hash,first_name,middle_name,last_name,full_name,email,phone,employee_photo_url,employee_id_card_document_url,date_of_birth,hire_date,badge_id,badge_secret_salt,badge_secret_hash,badge_generated_at,compensation_type,salary,role_id,auth_user_id,is_active,deactivated_at,password_cache_invalidated_at) VALUES(?,NULL,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,?,?,(SELECT role_id FROM roles WHERE UPPER(role_name)=UPPER(?)),?::uuid,?,CASE WHEN ? THEN NULL ELSE CURRENT_TIMESTAMP END,CURRENT_TIMESTAMP) RETURNING user_id
""";int id;try(PreparedStatement ps=c.prepareStatement(sql)){bindCore(ps,r,badgeId,h,authUserId);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Employee was not created.");id=rs.getInt(1);}}saveStores(c,id,r.locationIds());if(EmployeePayrollSettingsService.usesSelectablePeriod(r.compensationType()))EmployeePayrollSettingsService.setInitialSetting(c,id,r.payrollPeriodType(),r.workHourLimit());else EmployeePayrollSettingsService.ensureDefaultForEmployee(c,id);return id;}
    private static void bindCore(PreparedStatement ps,SaveRequest r,String badgeId,BadgeCredentialService.BadgeHash h,String auth)throws SQLException{ps.setString(1,r.username());ps.setString(2,r.firstName());ps.setString(3,blank(r.middleName()));ps.setString(4,r.lastName());ps.setString(5,r.fullName());ps.setString(6,r.email());ps.setString(7,r.phone());ps.setString(8,blank(r.photoUrl()));ps.setString(9,blank(r.idCardUrl()));setDate(ps,10,r.dateOfBirth());ps.setDate(11,Date.valueOf(r.hireDate()));ps.setString(12,badgeId);ps.setString(13,h.salt());ps.setString(14,h.hash());ps.setObject(15,r.compensationType(),Types.OTHER);ps.setBigDecimal(16,r.salary());ps.setString(17,r.role());ps.setString(18,auth);ps.setBoolean(19,r.active());ps.setBoolean(20,r.active());}
    public static void update(Connection c,int userId,SaveRequest r,String authUserId,boolean invalidatePassword,int actorId,String actorName,LocalDate today)throws SQLException{validate(r,false);String sql="""
UPDATE users SET username=?,password_hash=NULL,first_name=?,middle_name=?,last_name=?,full_name=?,email=?,phone=?,employee_photo_url=?,employee_id_card_document_url=?,date_of_birth=?,hire_date=?,compensation_type=?,salary=?,role_id=(SELECT role_id FROM roles WHERE UPPER(role_name)=UPPER(?)),auth_user_id=?::uuid,is_active=?,deactivated_at=CASE WHEN ? THEN NULL ELSE COALESCE(deactivated_at,CURRENT_TIMESTAMP) END,deactivated_by_user_id=CASE WHEN ? THEN NULL ELSE COALESCE(deactivated_by_user_id,?) END,deactivated_by_name=CASE WHEN ? THEN NULL ELSE COALESCE(deactivated_by_name,?) END,password_cache_invalidated_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE password_cache_invalidated_at END,updated_at=CURRENT_TIMESTAMP WHERE user_id=?
""";try(PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,r.username());ps.setString(2,r.firstName());ps.setString(3,blank(r.middleName()));ps.setString(4,r.lastName());ps.setString(5,r.fullName());ps.setString(6,r.email());ps.setString(7,r.phone());ps.setString(8,blank(r.photoUrl()));ps.setString(9,blank(r.idCardUrl()));setDate(ps,10,r.dateOfBirth());ps.setDate(11,Date.valueOf(r.hireDate()));ps.setObject(12,r.compensationType(),Types.OTHER);ps.setBigDecimal(13,r.salary());ps.setString(14,r.role());ps.setString(15,authUserId);ps.setBoolean(16,r.active());ps.setBoolean(17,r.active());ps.setBoolean(18,r.active());ps.setInt(19,actorId);ps.setBoolean(20,r.active());ps.setString(21,actorName);ps.setBoolean(22,invalidatePassword);ps.setInt(23,userId);if(ps.executeUpdate()!=1)throw new SQLException("Employee record was not found.");}saveStores(c,userId,r.locationIds());if(r.payrollSettingChanged()&&EmployeePayrollSettingsService.usesSelectablePeriod(r.compensationType()))EmployeePayrollSettingsService.saveNextSetting(c,userId,r.payrollPeriodType(),r.workHourLimit(),today);}
    public static String authUserId(Connection c,int userId)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT auth_user_id::text FROM users WHERE user_id=? FOR UPDATE")){ps.setInt(1,userId);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Employee record was not found.");return rs.getString(1);}}}
    public static String rotateBadge(Connection c,int userId,int actorId,String actorName)throws SQLException{LocalDate dob;try(PreparedStatement ps=c.prepareStatement("SELECT date_of_birth FROM users WHERE user_id=? FOR UPDATE")){ps.setInt(1,userId);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Employee not found.");dob=date(rs,1);}}String badge;for(int i=0;;i++){if(i>=10)throw new SQLException("Unable to generate a unique badge ID.");badge=BadgeCredentialService.generateBadgeId();try(PreparedStatement ps=c.prepareStatement("SELECT 1 FROM users WHERE UPPER(REGEXP_REPLACE(COALESCE(badge_id,''),'[^a-zA-Z0-9]','','g'))=? LIMIT 1")){ps.setString(1,BadgeCredentialService.normalizeBadge(badge));try(ResultSet rs=ps.executeQuery()){if(!rs.next())break;}}}BadgeCredentialService.BadgeHash h=BadgeCredentialService.createHash(badge,dob);try(PreparedStatement ps=c.prepareStatement("UPDATE users SET badge_id=?,badge_secret_salt=?,badge_secret_hash=?,badge_generated_at=CURRENT_TIMESTAMP,badge_print_count=0,badge_rotated_at=CURRENT_TIMESTAMP,badge_rotated_by_user_id=?,badge_rotated_by_name=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?")){ps.setString(1,badge);ps.setString(2,h.salt());ps.setString(3,h.hash());ps.setInt(4,actorId);ps.setString(5,actorName);ps.setInt(6,userId);if(ps.executeUpdate()!=1)throw new SQLException("The employee badge was not updated.");}LocalAuthCacheService.replaceCachedBadgeId(c,userId,badge);return badge;}
    public static void deactivate(Connection c,int userId,int actorId,String actorName)throws SQLException{try(PreparedStatement ps=c.prepareStatement("UPDATE users SET is_active=FALSE,deactivated_at=COALESCE(deactivated_at,CURRENT_TIMESTAMP),deactivated_by_user_id=?,deactivated_by_name=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?")){ps.setInt(1,actorId);ps.setString(2,actorName);ps.setInt(3,userId);if(ps.executeUpdate()!=1)throw new SQLException("Employee record was not found.");}}
    public static void saveStores(Connection c,int userId,List<Integer>ids)throws SQLException{Set<Integer>selected=new HashSet<>(ids==null?List.of():ids),current=new HashSet<>();try(PreparedStatement ps=c.prepareStatement("SELECT location_id FROM user_locations WHERE user_id=?")){ps.setInt(1,userId);try(ResultSet rs=ps.executeQuery()){while(rs.next())current.add(rs.getInt(1));}}for(Integer id:current)if(!selected.contains(id)){ReferenceDataSyncService.recordTombstone(c,"user_locations",Map.of("user_id",userId,"location_id",id));try(PreparedStatement ps=c.prepareStatement("DELETE FROM user_locations WHERE user_id=? AND location_id=?")){ps.setInt(1,userId);ps.setInt(2,id);ps.executeUpdate();}}try(PreparedStatement ps=c.prepareStatement("INSERT INTO user_locations(user_id,location_id) SELECT ?,location_id FROM locations WHERE location_id=? ON CONFLICT DO NOTHING")){for(Integer id:selected){ps.setInt(1,userId);ps.setInt(2,id);ps.addBatch();}ps.executeBatch();}}
    private static void validate(SaveRequest r,boolean creating)throws SQLException{if(r==null||r.username()==null||r.username().isBlank()||r.firstName()==null||r.firstName().isBlank()||r.lastName()==null||r.lastName().isBlank()||r.email()==null||r.email().isBlank()||r.hireDate()==null||r.salary()==null||r.role()==null||r.role().isBlank()||r.locationIds()==null||r.locationIds().isEmpty())throw new SQLException("First name, last name, email, hire date, pay, role, and at least one store are required.");}
    private static LocalDate date(ResultSet rs,int i)throws SQLException{Date d=rs.getDate(i);return d==null?null:d.toLocalDate();}private static void setDate(PreparedStatement ps,int i,LocalDate d)throws SQLException{if(d==null)ps.setNull(i,Types.DATE);else ps.setDate(i,Date.valueOf(d));}private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
    public record State(List<String>roles,List<Employee>employees,List<Store>stores,EmployeePayrollSettingsService.SettingView payroll){}public record Employee(int userId,String username,String fullName,String firstName,String middleName,String lastName,String email,String phone,String photoUrl,LocalDate dateOfBirth,LocalDate hireDate,LocalDate deactivationDate,String badgeId,int badgePrintCount,String compensationType,BigDecimal salary,String role,boolean active,String idCardUrl){}public record Store(int locationId,String name,String address,boolean assigned){}public record SaveRequest(String username,String password,String firstName,String middleName,String lastName,String fullName,String email,String phone,String photoUrl,String idCardUrl,LocalDate dateOfBirth,LocalDate hireDate,String compensationType,BigDecimal salary,String role,boolean active,List<Integer>locationIds,EmployeePayrollSettingsService.PeriodType payrollPeriodType,BigDecimal workHourLimit,boolean payrollSettingChanged,String supabaseAccessToken){}
}
