package services;
import com.google.gson.Gson;import com.google.gson.JsonObject;import java.math.BigDecimal;import java.sql.*;import java.util.*;
final class LanMaintenancePartsService{
 private static final Gson G=LanJson.create();private LanMaintenancePartsService(){}
 static Map<String,Object>list(Connection c,JsonObject b,int u)throws Exception{require(c,u);String s=text(b,"search"),p="%"+s+"%";List<Map<String,Object>>x=new ArrayList<>();try(PreparedStatement q=c.prepareStatement("""
 SELECT part_id,part_name,COALESCE(part_number,''),COALESCE(category,''),COALESCE(quantity_on_hand,0),COALESCE(reorder_point,0),COALESCE(reorder_quantity,0),COALESCE(unit_cost,0),COALESCE(vendor_name,''),COALESCE(bin_location,''),COALESCE(is_active,TRUE),COALESCE(notes,'') FROM maintenance_parts
 WHERE (?='' OR part_name ILIKE ? OR COALESCE(part_number,'') ILIKE ? OR COALESCE(category,'') ILIKE ? OR COALESCE(vendor_name,'') ILIKE ? OR COALESCE(bin_location,'') ILIKE ?) ORDER BY part_name
 """)){q.setString(1,s);for(int i=2;i<=6;i++)q.setString(i,p);try(ResultSet r=q.executeQuery()){while(r.next())x.add(row(r));}}return map("parts",x);}
 static Map<String,Object>save(Connection c,JsonObject b,int u)throws Exception{require(c,u);Part r=G.fromJson(b,Part.class);if(r==null||text(r.name()).isBlank())throw rule(400,"VALIDATION_ERROR","Part name is required.");BigDecimal quantity=money(r.quantity()),point=money(r.reorderPoint()),reorder=money(r.reorderQuantity()),cost=money(r.unitCost());if(quantity.signum()<0||point.signum()<0||reorder.signum()<0||cost.signum()<0)throw rule(400,"VALIDATION_ERROR","Part quantities and cost cannot be negative.");Integer id=r.partId();String sql=id==null?"INSERT INTO maintenance_parts(part_name,part_number,category,quantity_on_hand,reorder_point,reorder_quantity,unit_cost,vendor_name,bin_location,is_active,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING part_id":"UPDATE maintenance_parts SET part_name=?,part_number=?,category=?,quantity_on_hand=?,reorder_point=?,reorder_quantity=?,unit_cost=?,vendor_name=?,bin_location=?,is_active=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE part_id=? RETURNING part_id";try(PreparedStatement q=c.prepareStatement(sql)){q.setString(1,text(r.name()));q.setString(2,blank(r.partNumber()));q.setString(3,blank(r.category()));q.setBigDecimal(4,quantity);q.setBigDecimal(5,point);q.setBigDecimal(6,reorder);q.setBigDecimal(7,cost);q.setString(8,blank(r.vendor()));q.setString(9,blank(r.binLocation()));q.setBoolean(10,r.active());q.setString(11,blank(r.notes()));if(id!=null)q.setInt(12,id);try(ResultSet rs=q.executeQuery()){if(!rs.next())throw new SQLException("Part could not be saved.");id=rs.getInt(1);}}return map("partId",id);}
 static Map<String,Object>delete(Connection c,JsonObject b,int u)throws Exception{require(c,u);int id=b.get("partId").getAsInt();try(PreparedStatement q=c.prepareStatement("DELETE FROM maintenance_parts WHERE part_id=?")){q.setInt(1,id);if(q.executeUpdate()!=1)throw rule(404,"PART_NOT_FOUND","Part was not found.");}return map("deleted",true);}
 private static Map<String,Object>row(ResultSet r)throws SQLException{return map("partId",r.getInt(1),"name",r.getString(2),"partNumber",r.getString(3),"category",r.getString(4),"quantity",r.getBigDecimal(5),"reorderPoint",r.getBigDecimal(6),"reorderQuantity",r.getBigDecimal(7),"unitCost",r.getBigDecimal(8),"vendor",r.getString(9),"binLocation",r.getString(10),"active",r.getBoolean(11),"notes",r.getString(12));}
 private static void require(Connection c,int u)throws Exception{try(PreparedStatement q=c.prepareStatement("SELECT 1 FROM users u JOIN role_permissions rp ON rp.role_id=u.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE u.user_id=? AND UPPER(p.permission_key) IN ('PARTS_MANAGEMENT','MAINTENANCE_MANAGEMENT') LIMIT 1")){q.setInt(1,u);try(ResultSet r=q.executeQuery()){if(r.next())return;}}throw rule(403,"PERMISSION_DENIED","You do not have permission to manage parts.");}
 private static String text(JsonObject b,String k){return b.has(k)&&!b.get(k).isJsonNull()?b.get(k).getAsString().trim():"";}private static String text(String s){return s==null?"":s.trim();}private static String blank(String s){s=text(s);return s.isBlank()?null:s;}private static BigDecimal money(BigDecimal v){return v==null?BigDecimal.ZERO:v;}private static Map<String,Object>map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}private static RuleViolation rule(int s,String c,String m){return new RuleViolation(s,c,m);}
 private record Part(Integer partId,String name,String partNumber,String category,BigDecimal quantity,BigDecimal reorderPoint,BigDecimal reorderQuantity,BigDecimal unitCost,String vendor,String binLocation,boolean active,String notes){}
 static final class RuleViolation extends Exception{private final int status;private final String code;private final String safeMessage;RuleViolation(int s,String c,String m){super(m);status=s;code=c;safeMessage=m;}int status(){return status;}String code(){return code;}String safeMessage(){return safeMessage;}}
}
