package services;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/** Server-owned maintenance logs and tickets repository. */
public final class LanMaintenanceWorkflowService {
    private LanMaintenanceWorkflowService() { }
    public static State state(Connection c,String ticketSearch,String filter)throws SQLException{
        autoClose(c);List<MachineOption>machines=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT machine_id,machine_name FROM maintenance_machines ORDER BY machine_name");ResultSet rs=ps.executeQuery()){while(rs.next())machines.add(new MachineOption(rs.getInt(1),rs.getString(2)));}
        List<LogRow>logs=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement("SELECT l.log_id,l.service_date,m.machine_name,l.service_type,COALESCE(l.technician_name,''),l.labor_hours,l.total_cost,COALESCE(l.summary,'') FROM maintenance_logs l JOIN maintenance_machines m ON m.machine_id=l.machine_id ORDER BY l.service_date DESC,l.log_id DESC");ResultSet rs=ps.executeQuery()){while(rs.next())logs.add(new LogRow(rs.getInt(1),rs.getDate(2).toLocalDate(),rs.getString(3),rs.getString(4),rs.getString(5),rs.getBigDecimal(6),rs.getBigDecimal(7),rs.getString(8)));}
        String status=switch(filter==null?"Active":filter){case"Resolved"->"RESOLVED";case"Ticket History"->"CLOSED";case"All"->null;default->"ACTIVE";};String search=ticketSearch==null?"":ticketSearch.trim(),pattern="%"+search+"%";
        String sql="""
SELECT t.ticket_id,t.opened_at,COALESCE(m.machine_name,''),t.priority,t.status,COALESCE(t.problem_summary,''),COALESCE(t.assigned_to_name,''),t.due_date,CASE WHEN t.opened_by_user_id IS NULL THEN 'Unknown' WHEN NULLIF(TRIM(u.full_name),'') IS NOT NULL THEN u.full_name ELSE 'User #'||t.opened_by_user_id::text END FROM maintenance_tickets t LEFT JOIN maintenance_machines m ON m.machine_id=t.machine_id LEFT JOIN users u ON u.user_id=t.opened_by_user_id WHERE (? IS NULL OR (?='ACTIVE' AND t.status IN ('OPEN','IN_PROGRESS','WAITING_PARTS')) OR t.status=?) AND (?='' OR COALESCE(m.machine_name,'') ILIKE ? OR COALESCE(t.problem_summary,'') ILIKE ? OR COALESCE(t.assigned_to_name,'') ILIKE ? OR COALESCE(t.status,'') ILIKE ? OR COALESCE(t.priority,'') ILIKE ?) ORDER BY t.opened_at DESC,t.ticket_id DESC
""";
        List<TicketRow>tickets=new ArrayList<>();try(PreparedStatement ps=c.prepareStatement(sql)){ps.setString(1,status);ps.setString(2,status);ps.setString(3,status);ps.setString(4,search);for(int i=5;i<=9;i++)ps.setString(i,pattern);try(ResultSet rs=ps.executeQuery()){while(rs.next()){Timestamp opened=rs.getTimestamp(2);Date due=rs.getDate(8);tickets.add(new TicketRow(rs.getInt(1),opened==null?0:opened.getTime(),rs.getString(3),rs.getString(9),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),due==null?null:due.toLocalDate()));}}}
        return new State(machines,logs,tickets);
    }
    private static void autoClose(Connection c)throws SQLException{try(PreparedStatement ps=c.prepareStatement("UPDATE maintenance_tickets SET status='CLOSED',closed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE status='RESOLVED' AND resolved_at IS NOT NULL AND resolved_at<=CURRENT_TIMESTAMP-INTERVAL '24 hours' AND closed_at IS NULL")){ps.executeUpdate();}}
    public static Detail detail(Connection c,String type,int id)throws SQLException{return switch(type){case"LOG"->new Detail(log(c,id),null);case"TICKET"->new Detail(null,ticket(c,id));default->throw new SQLException("Maintenance detail type is invalid.");};}
    private static Log log(Connection c,int id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("SELECT log_id,machine_id,service_date,service_type,technician_name,labor_hours,total_cost,summary,details,parts_used FROM maintenance_logs WHERE log_id=?")){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Maintenance log not found.");return new Log(rs.getInt(1),rs.getInt(2),rs.getDate(3).toLocalDate(),rs.getString(4),rs.getString(5),rs.getBigDecimal(6),rs.getBigDecimal(7),rs.getString(8),rs.getString(9),rs.getString(10));}}}
    private static Ticket ticket(Connection c,int id)throws SQLException{String sql="""
SELECT t.ticket_id,t.machine_id,t.priority,t.status,t.assigned_to_name,t.due_date,t.problem_summary,t.resolution_summary,t.notes,CASE WHEN t.opened_by_user_id IS NULL THEN 'Unknown' WHEN NULLIF(TRIM(u.full_name),'') IS NOT NULL THEN u.full_name ELSE 'User #'||t.opened_by_user_id::text END FROM maintenance_tickets t LEFT JOIN users u ON u.user_id=t.opened_by_user_id WHERE t.ticket_id=?
""";try(PreparedStatement ps=c.prepareStatement(sql)){ps.setInt(1,id);try(ResultSet rs=ps.executeQuery()){if(!rs.next())throw new SQLException("Maintenance ticket not found.");Date due=rs.getDate(6);return new Ticket(rs.getInt(1),nullableInt(rs,2),rs.getString(3),rs.getString(4),rs.getString(5),due==null?null:due.toLocalDate(),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10));}}}
    public static int saveLog(Connection c,Log log,int actorId)throws SQLException{if(log==null||log.machineId()<=0||log.serviceDate()==null)throw new SQLException("Machine and service date are required.");String sql=log.id()==null?"INSERT INTO maintenance_logs(machine_id,service_date,service_type,technician_name,labor_hours,total_cost,summary,details,parts_used,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?,?)":"UPDATE maintenance_logs SET machine_id=?,service_date=?,service_type=?,technician_name=?,labor_hours=?,total_cost=?,summary=?,details=?,parts_used=? WHERE log_id=?";try(PreparedStatement ps=c.prepareStatement(sql,log.id()==null?Statement.RETURN_GENERATED_KEYS:Statement.NO_GENERATED_KEYS)){ps.setInt(1,log.machineId());ps.setDate(2,Date.valueOf(log.serviceDate()));ps.setString(3,log.type());ps.setString(4,blank(log.technician()));ps.setBigDecimal(5,zero(log.hours()));ps.setBigDecimal(6,zero(log.cost()));ps.setString(7,blank(log.summary()));ps.setString(8,blank(log.details()));ps.setString(9,blank(log.partsUsed()));ps.setInt(10,log.id()==null?actorId:log.id());ps.executeUpdate();if(log.id()!=null)return log.id();try(ResultSet rs=ps.getGeneratedKeys()){if(!rs.next())throw new SQLException("Maintenance log ID was not returned.");return rs.getInt(1);}}}
    public static int saveTicket(Connection c,Ticket t,int actorId)throws SQLException{if(t==null||t.problem()==null||t.problem().trim().isBlank())throw new SQLException("Problem summary is required.");if(!List.of("OPEN","IN_PROGRESS","WAITING_PARTS","RESOLVED","CANCELED").contains(t.status()))throw new SQLException("Ticket status is invalid.");if("RESOLVED".equals(t.status())&&(t.resolution()==null||t.resolution().isBlank()))throw new SQLException("A resolution summary is required.");String sql=t.id()==null?"INSERT INTO maintenance_tickets(machine_id,priority,status,assigned_to_name,due_date,problem_summary,resolution_summary,notes,opened_by_user_id,resolved_at) VALUES(?,?,?,?,?,?,?,?,?,CASE WHEN ?='RESOLVED' THEN CURRENT_TIMESTAMP END)":"UPDATE maintenance_tickets SET machine_id=?,priority=?,status=?,assigned_to_name=?,due_date=?,problem_summary=?,resolution_summary=?,notes=?,resolved_at=CASE WHEN ?='RESOLVED' AND status<>'RESOLVED' THEN CURRENT_TIMESTAMP ELSE resolved_at END,updated_at=CURRENT_TIMESTAMP WHERE ticket_id=?";try(PreparedStatement ps=c.prepareStatement(sql,t.id()==null?Statement.RETURN_GENERATED_KEYS:Statement.NO_GENERATED_KEYS)){setInt(ps,1,t.machineId());ps.setString(2,t.priority());ps.setString(3,t.status());ps.setString(4,blank(t.assigned()));setDate(ps,5,t.dueDate());ps.setString(6,t.problem().trim());ps.setString(7,blank(t.resolution()));ps.setString(8,blank(t.notes()));if(t.id()==null){ps.setInt(9,actorId);ps.setString(10,t.status());}else{ps.setString(9,t.status());ps.setInt(10,t.id());}ps.executeUpdate();if(t.id()!=null)return t.id();try(ResultSet rs=ps.getGeneratedKeys()){if(!rs.next())throw new SQLException("Ticket ID was not returned.");return rs.getInt(1);}}}
    public static void closeTicket(Connection c,int id)throws SQLException{try(PreparedStatement ps=c.prepareStatement("UPDATE maintenance_tickets SET status='CLOSED',closed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE ticket_id=? AND status='RESOLVED'")){ps.setInt(1,id);if(ps.executeUpdate()==0)throw new SQLException("Only a resolved ticket can be closed.");}}
    private static Integer nullableInt(ResultSet rs,int i)throws SQLException{int v=rs.getInt(i);return rs.wasNull()?null:v;}private static void setInt(PreparedStatement ps,int i,Integer v)throws SQLException{if(v==null)ps.setNull(i,Types.INTEGER);else ps.setInt(i,v);}private static void setDate(PreparedStatement ps,int i,LocalDate v)throws SQLException{if(v==null)ps.setNull(i,Types.DATE);else ps.setDate(i,Date.valueOf(v));}private static String blank(String v){return v==null||v.isBlank()?null:v.trim();}private static BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO:v;}
    public record State(List<MachineOption>machines,List<LogRow>logs,List<TicketRow>tickets){}public record MachineOption(int id,String name){}public record LogRow(int id,LocalDate date,String machine,String type,String technician,BigDecimal hours,BigDecimal cost,String summary){}public record TicketRow(int id,long openedEpochMillis,String machine,String creator,String priority,String status,String problem,String assigned,LocalDate dueDate){}public record Detail(Log log,Ticket ticket){}public record Log(Integer id,int machineId,LocalDate serviceDate,String type,String technician,BigDecimal hours,BigDecimal cost,String summary,String details,String partsUsed){}public record Ticket(Integer id,Integer machineId,String priority,String status,String assigned,LocalDate dueDate,String problem,String resolution,String notes,String creator){}
}
