package services;
import java.math.BigDecimal;import java.sql.*;import java.time.*;import java.util.*;
final class LanReportDetailService{private LanReportDetailService(){}
 static Map<String,Object>orders(Connection c,ZonedDateTime from,ZonedDateTime to,int location)throws SQLException{List<Map<String,Object>>rows=new ArrayList<>();BigDecimal collected=z(null),cash=z(null),card=z(null),cheque=z(null),mmg=z(null),account=z(null);
  try(PreparedStatement p=c.prepareStatement("""
   SELECT p.custom_order_payment_id,co.order_number,p.created_at AT TIME ZONE ?,COALESCE(co.customer_name,''),COALESCE(p.taken_by_name,u.full_name,u.username,'Unknown'),COALESCE(p.device_name,co.device_name,p.device_id::text,co.device_id::text,''),COALESCE(NULLIF(TRIM(p.cash_drawer_name),''),'Unassigned'),p.payment_method,COALESCE(p.payment_action,'PAYMENT'),COALESCE(p.payment_amount,0),COALESCE(co.total_amount,0),COALESCE(co.balance_due,0),COALESCE(co.status,''),COALESCE(co.payment_status,'') FROM custom_order_payments p JOIN custom_orders co ON co.custom_order_id=p.custom_order_id LEFT JOIN users u ON u.user_id=p.taken_by_user_id WHERE p.created_at>=? AND p.created_at<? AND co.location_id=? ORDER BY p.created_at,p.custom_order_payment_id
   """)){p.setString(1,from.getZone().getId());p.setTimestamp(2,Timestamp.from(from.toInstant()));p.setTimestamp(3,Timestamp.from(to.toInstant()));p.setInt(4,location);try(ResultSet r=p.executeQuery()){while(r.next()){BigDecimal a=signed(r.getString(9),r.getBigDecimal(10));collected=collected.add(a);String m=r.getString(8);if("CASH".equalsIgnoreCase(m))cash=cash.add(a);else if("CARD".equalsIgnoreCase(m))card=card.add(a);else if("CHEQUE".equalsIgnoreCase(m))cheque=cheque.add(a);else if("MMG".equalsIgnoreCase(m))mmg=mmg.add(a);else if("ACCOUNT".equalsIgnoreCase(m))account=account.add(a);rows.add(map("paymentId",r.getLong(1),"orderNumber",r.getString(2),"time",r.getTimestamp(3).toLocalDateTime(),"customer",r.getString(4),"employee",r.getString(5),"device",r.getString(6),"drawer",r.getString(7),"method",m,"amount",a,"total",z(r.getBigDecimal(11)),"balance",z(r.getBigDecimal(12)),"status",r.getString(13)+" / "+r.getString(14)));}}}
  BigDecimal total=z(null),balance=z(null),returns=z(null);try(PreparedStatement p=c.prepareStatement("SELECT COALESCE(SUM(total_amount),0),COALESCE(SUM(balance_due),0) FROM custom_orders WHERE created_at>=? AND created_at<? AND location_id=?")){range(p,from,to,location);try(ResultSet r=p.executeQuery()){r.next();total=z(r.getBigDecimal(1));balance=z(r.getBigDecimal(2));}}try(PreparedStatement p=c.prepareStatement("SELECT COALESCE(SUM(refund_amount),0) FROM custom_order_line_returns WHERE created_at>=? AND created_at<? AND custom_order_id IN(SELECT custom_order_id FROM custom_orders WHERE location_id=?)")){range(p,from,to,location);try(ResultSet r=p.executeQuery()){r.next();returns=z(r.getBigDecimal(1));}}
  return map("rows",rows,"payments",rows.size(),"collected",collected,"total",total,"balance",balance,"cash",cash,"card",card,"cheque",cheque,"mmg",mmg,"account",account,"returns",returns);}
 static Map<String,Object>invoices(Connection c,ZonedDateTime from,ZonedDateTime to,int location)throws SQLException{List<Map<String,Object>>rows=new ArrayList<>();BigDecimal total=z(null),paid=z(null),balance=z(null);int open=0,delivered=0;
  try(PreparedStatement p=c.prepareStatement("SELECT invoice_id,invoice_number,invoice_date,customer_name,status,payment_status,COALESCE(total_amount,0),COALESCE(amount_paid,0),COALESCE(balance_due,0),COALESCE(created_by_name,''),COALESCE(device_name,device_id::text,''),COALESCE(NULLIF(TRIM(cash_drawer_name),''),'Unassigned') FROM invoices WHERE created_at>=? AND created_at<? AND location_id=? ORDER BY created_at,invoice_id")){range(p,from,to,location);try(ResultSet r=p.executeQuery()){while(r.next()){BigDecimal t=z(r.getBigDecimal(7)),a=z(r.getBigDecimal(8)),b=z(r.getBigDecimal(9));total=total.add(t);paid=paid.add(a);balance=balance.add(b);String s=r.getString(5);if("DELIVERED".equalsIgnoreCase(s))delivered++;else if(!"CANCELLED".equalsIgnoreCase(s))open++;rows.add(map("invoiceId",r.getLong(1),"invoiceNumber",r.getString(2),"invoiceDate",r.getDate(3).toLocalDate(),"customer",r.getString(4),"status",s,"paymentStatus",r.getString(6),"total",t,"paid",a,"balance",b,"creator",r.getString(10),"device",r.getString(11),"drawer",r.getString(12)));}}}
  BigDecimal cash=z(null),card=z(null),cheque=z(null),mmg=z(null);try(PreparedStatement p=c.prepareStatement("SELECT payment_method,COALESCE(payment_action,'PAYMENT'),COALESCE(SUM(payment_amount),0) FROM invoice_payments WHERE voided_at IS NULL AND created_at>=? AND created_at<? AND location_id=? GROUP BY payment_method,COALESCE(payment_action,'PAYMENT')")){range(p,from,to,location);try(ResultSet r=p.executeQuery()){while(r.next()){BigDecimal a=signed(r.getString(2),r.getBigDecimal(3));switch(r.getString(1).toUpperCase()){case"CASH"->cash=cash.add(a);case"CARD"->card=card.add(a);case"CHEQUE"->cheque=cheque.add(a);case"MMG"->mmg=mmg.add(a);}}}}
  return map("rows",rows,"count",rows.size(),"open",open,"delivered",delivered,"total",total,"paid",paid,"balance",balance,"cash",cash,"card",card,"cheque",cheque,"mmg",mmg);}
 private static void range(PreparedStatement p,ZonedDateTime f,ZonedDateTime t,int l)throws SQLException{p.setTimestamp(1,Timestamp.from(f.toInstant()));p.setTimestamp(2,Timestamp.from(t.toInstant()));p.setInt(3,l);}private static BigDecimal z(BigDecimal v){return v==null?BigDecimal.ZERO:v;}private static BigDecimal signed(String a,BigDecimal v){v=z(v);return Set.of("REFUND","REVERSAL").contains(a==null?"":a.toUpperCase())?v.negate():v;}private static Map<String,Object>map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}}
