package services;

import com.google.gson.*;
import com.sun.net.httpserver.*;
import data.DB;

import java.io.*;
import java.net.*;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

/** Public browser surface for owner scheduling and employee self-service viewing. Reverse-proxy only /scheduler paths. */
public final class SchedulerWebServer implements AutoCloseable {
    public static final int DEFAULT_PORT=8446;
    private static final Duration PREAUTH_TTL=Duration.ofMinutes(10),IDLE=Duration.ofMinutes(15),ABSOLUTE=Duration.ofHours(8),PROPOSAL_TTL=Duration.ofMinutes(10);
    private static final Gson GSON=LanJson.create();
    private final HttpsServer server; private final ExecutorService executor; private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build();
    private final ConcurrentMap<String,Preauth> preauths=new ConcurrentHashMap<>(); private final ConcurrentMap<UUID,SavedProposal> proposals=new ConcurrentHashMap<>();
    private final String publicOrigin;
    private UUID generation;
    private final SchedulerWebAuthConfig authConfig=SchedulerWebAuthConfig.load();
    private final boolean mfaRequired=Boolean.parseBoolean(System.getenv("SMARTSTOCK_SCHEDULER_REQUIRE_MFA"));

    private SchedulerWebServer(HttpsServer server,ExecutorService executor,String publicOrigin){this.server=server;this.executor=executor;this.publicOrigin=publicOrigin;}
    public static SchedulerWebServer start()throws Exception{
        return start(System.getenv("SMARTSTOCK_SCHEDULER_PUBLIC_ORIGIN"));
    }
    public static SchedulerWebServer start(String requestedOrigin)throws Exception{
        int port=Integer.getInteger("smartstock.scheduler.web.port",DEFAULT_PORT);String origin=cleanOrigin(requestedOrigin);
        if(origin==null)throw new IllegalStateException("SMARTSTOCK_SCHEDULER_PUBLIC_ORIGIN must be an https:// origin.");
        LanTlsIdentity identity=LanTlsIdentity.loadOrCreate();HttpsServer https=HttpsServer.create(new InetSocketAddress("127.0.0.1",port),50);https.setHttpsConfigurator(new HttpsConfigurator(identity.sslContext()));
        ExecutorService pool=new ThreadPoolExecutor(12,12,0L,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(64),r->{Thread t=new Thread(r,"smartstock-scheduler-web");t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());https.setExecutor(pool);
        SchedulerWebServer app=new SchedulerWebServer(https,pool,origin);try(Connection c=DB.getConnection()){app.requireSchema(c);ServerEmployeeScheduleService.ensureSchema(c);try(PreparedStatement p=c.prepareStatement("SELECT generation FROM scheduler_web_runtime WHERE runtime_id=1 AND enabled=TRUE");ResultSet r=p.executeQuery()){if(!r.next())throw err(503,"SCHEDULER_STOPPED","The scheduler is stopped.");app.generation=(UUID)r.getObject(1);}}catch(Exception e){https.stop(0);pool.shutdownNow();throw e;}https.createContext("/scheduler",app::handle);https.start();return app;
    }
    private void handle(HttpExchange x){try{String p=x.getRequestURI().getPath();if("/scheduler/health".equals(p)){text(x,200,"application/json; charset=utf-8","{\"ok\":true}");return;}if(p.startsWith("/scheduler/api/v1/")){api(x,p.substring("/scheduler/api/v1/".length()));return;}asset(x,p);}catch(WebError e){json(x,e.status,Map.of("ok",false,"error",Map.of("code",e.code,"message",e.getMessage())));}catch(Exception e){WebError safe=publicError(e);json(x,safe.status,Map.of("ok",false,"error",Map.of("code",safe.code,"message",safe.getMessage())));}finally{x.close();}}
    private void asset(HttpExchange x,String path)throws Exception{if(!"GET".equals(x.getRequestMethod()))throw err(405,"METHOD_NOT_ALLOWED","GET is required.");String file=switch(path){case"/scheduler","/scheduler/","/scheduler/index.html"->"index.html";case"/scheduler/app.css"->"app.css";case"/scheduler/app.js"->"app.js";case"/scheduler/sw.js"->"sw.js";case"/scheduler/icon.svg"->"icon.svg";case"/scheduler/manifest.webmanifest"->"manifest.webmanifest";default->null;};if(file==null)throw err(404,"NOT_FOUND","Not found.");try(InputStream in=getClass().getClassLoader().getResourceAsStream("scheduler-web/"+file)){if(in==null)throw err(404,"NOT_FOUND","Web asset missing.");byte[] b=in.readAllBytes();String type=file.endsWith(".css")?"text/css; charset=utf-8":file.endsWith(".js")?"application/javascript; charset=utf-8":file.endsWith(".svg")?"image/svg+xml":file.endsWith(".webmanifest")?"application/manifest+json":"text/html; charset=utf-8";headers(x);x.getResponseHeaders().set("Content-Type",type);x.sendResponseHeaders(200,b.length);x.getResponseBody().write(b);}}
    private void api(HttpExchange x,String route)throws Exception{if(!"POST".equals(x.getRequestMethod()))throw err(405,"METHOD_NOT_ALLOWED","POST is required.");sameOrigin(x);try(Connection c=DB.getConnection()){requireAvailable(c);}prune();JsonObject b=body(x);Object out=switch(route){case"auth/login"->login(x,b);case"auth/verify"->verify(x,b);case"auth/session"->session(x);case"auth/logout"->logout(x);case"scheduler/bootstrap"->bootstrap(requireSession(x,false));case"scheduler/snapshot"->snapshot(requireSession(x,false),b);case"scheduler/update"->idempotent(x,requireSession(x,true),b,"scheduler.update",c->update(c,b));case"scheduler/auto-generate"->idempotent(x,requireSession(x,true),b,"scheduler.auto-generate",c->generate(b));case"scheduler/auto-apply"->idempotent(x,requireSession(x,true),b,"scheduler.auto-apply",c->apply(c,b));default->throw err(404,"NOT_FOUND","API route not found.");};json(x,200,Map.of("ok",true,"data",out==null?Map.of():out));}

    private Object login(HttpExchange x,JsonObject b)throws Exception{String identifier=required(b,b.has("identifier")?"identifier":"email",512),password=password(b),address=remote(x),key=LanSecurity.sha256(identifier.toLowerCase(Locale.ROOT));reserveAttempt(key,address);String email;try(Connection c=DB.getConnection()){email=resolveLoginEmail(c,identifier);}
        SupabaseProjectConfig cfg=authConfig.project();JsonObject q=new JsonObject();q.addProperty("email",email);q.addProperty("password",password);JsonObject token=supabase(cfg,"/auth/v1/token?grant_type=password",null,q);
        String access=str(token,"access_token"),sub=jwt(access,"sub"),aal=jwt(access,"aal");if(sub==null){throw err(401,"AUTH_FAILED","The sign-in was not accepted.");}if(!mfaRequired||"aal2".equals(aal))return createSession(x,UUID.fromString(sub),access,key,address);
        JsonObject factors=supabase(cfg,"/auth/v1/user",access,null);if(!sub.equals(str(factors,"id")))throw err(401,"AUTH_INVALID","The online session was not accepted.");try(Connection c=DB.getConnection()){User u=userByAuth(c,UUID.fromString(sub));requireWebAccess(c,u.userId);}JsonArray totp=factors.has("factors")?factors.getAsJsonArray("factors"):new JsonArray();String factor=null;for(JsonElement e:totp){JsonObject f=e.getAsJsonObject();if("totp".equals(str(f,"factor_type"))&&"verified".equalsIgnoreCase(str(f,"status"))){factor=str(f,"id");break;}}
        String qr=null,secret=null;if(factor==null){JsonObject enrollBody=new JsonObject();enrollBody.addProperty("factor_type","totp");enrollBody.addProperty("friendly_name","SmartStock Scheduler");JsonObject enrolled=supabase(cfg,"/auth/v1/factors",access,enrollBody);factor=str(enrolled,"id");JsonObject detail=enrolled.has("totp")?enrolled.getAsJsonObject("totp"):new JsonObject();qr=qrData(str(detail,"qr_code"));secret=str(detail,"secret");if(factor==null)throw err(502,"MFA_ENROLLMENT_FAILED","The authenticator enrollment could not be started.");}
        JsonObject challenge=supabase(cfg,"/auth/v1/factors/"+url(factor)+"/challenge",access,new JsonObject());String challengeId=str(challenge,"id"),handle=LanSecurity.randomToken();if(preauths.size()>=256)throw err(503,"AUTH_BUSY","Please try again shortly.");preauths.put(LanSecurity.sha256(handle),new Preauth(access,UUID.fromString(sub),factor,challengeId,Instant.now().plus(PREAUTH_TTL),key,address));Map<String,Object>result=new LinkedHashMap<>();result.put("preauth",handle);result.put("mfaRequired",true);if(qr!=null){result.put("enrollmentRequired",true);result.put("qrCode",qr);result.put("secret",secret==null?"":secret);}return result;
    }
    private Object verify(HttpExchange x,JsonObject b)throws Exception{String handle=required(b,"preauth",500),code=required(b,"code",12);Preauth p=preauths.remove(LanSecurity.sha256(handle));if(p==null||!p.expires.isAfter(Instant.now()))throw err(401,"PREAUTH_EXPIRED","Start the sign-in again.");reserveAttempt(p.identifierHash,p.address);JsonObject q=new JsonObject();q.addProperty("challenge_id",p.challengeId);q.addProperty("code",code);JsonObject verified=supabase(authConfig.project(),"/auth/v1/factors/"+url(p.factorId)+"/verify",p.accessToken,q);String access=str(verified,"access_token");if(!"aal2".equals(jwt(access,"aal"))||!p.authUserId.toString().equals(jwt(access,"sub"))){throw err(401,"MFA_REQUIRED","The authenticator code was not accepted.");}return createSession(x,p.authUserId,access,p.identifierHash,p.address);}
    private Object createSession(HttpExchange x,UUID authId,String access,String key,String address)throws Exception{requireAssurance(mfaRequired,jwt(access,"aal"));JsonObject remote=supabase(authConfig.project(),"/auth/v1/user",access,null);if(!authId.toString().equals(str(remote,"id")))throw err(401,"AUTH_INVALID","The online session was not accepted.");String token=LanSecurity.randomToken(),csrf=LanSecurity.randomToken();Instant now=Instant.now();try(Connection c=DB.getConnection()){c.setAutoCommit(false);try{requireAvailable(c);User u=userByAuth(c,authId);requireWebAccess(c,u.userId);try(PreparedStatement ps=c.prepareStatement("INSERT INTO scheduler_web_sessions(session_hash,csrf_hash,user_id,auth_user_id,expires_at,absolute_expires_at) VALUES(?,?,?,?,?,?)")){ps.setString(1,LanSecurity.sha256(token));ps.setString(2,LanSecurity.sha256(csrf));ps.setInt(3,u.userId);ps.setObject(4,authId);ps.setTimestamp(5,Timestamp.from(now.plus(IDLE)));ps.setTimestamp(6,Timestamp.from(now.plus(ABSOLUTE)));ps.executeUpdate();}recordAttempt(c,key,address,true);audit(c,"SCHEDULER_WEB_LOGIN",u.userId,"Scheduler web login; MFA required="+mfaRequired+"; assurance="+jwt(access,"aal"));c.commit();}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}cookie(x,"ss_scheduler",token,8*3600);return Map.of("csrfToken",csrf);}
    private Object session(HttpExchange x)throws Exception{Session s=requireSession(x,false);String csrf=LanSecurity.randomToken();try(Connection c=DB.getConnection();PreparedStatement ps=c.prepareStatement("UPDATE scheduler_web_sessions SET csrf_hash=? WHERE session_id=?")){ps.setString(1,LanSecurity.sha256(csrf));ps.setObject(2,s.id);ps.executeUpdate();}return Map.of("csrfToken",csrf);}
    private Object logout(HttpExchange x)throws Exception{
        Session session=requireSession(x,true);
        try(Connection c=DB.getConnection()){c.setAutoCommit(false);try{
            try(PreparedStatement p=c.prepareStatement("UPDATE scheduler_web_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE session_id=? AND revoked_at IS NULL")){
                p.setObject(1,session.id);p.executeUpdate();
            }
            audit(c,"SCHEDULER_WEB_LOGOUT",session.userId,"Scheduler browser session revoked");
            c.commit();
        }catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}
        clearCookie(x,"ss_scheduler");return Map.of();
    }

    private Object bootstrap(Session s)throws Exception{return bound(s,()->Map.of("locations",ServerEmployeeScheduleService.loadAccessibleLocations(),"permissions",s.permissions,"editable",canEdit(s.permissions),"selfOnly",!canEdit(s.permissions),"displayName",s.displayName));}
    private Object snapshot(Session s,JsonObject b)throws Exception{return bound(s,()->{int location=integer(b,"locationId");LocalDate start=date(b,"start"),end=date(b,"end");validateRange(start,end);String before=revision(location,start,end);boolean selfOnly=!canEdit(s.permissions);List<Map<String,Object>>days=new ArrayList<>();ServerEmployeeScheduleService.loadRange(location,start,end).forEach((d,a)->days.add(Map.of("date",d,"assignments",selfOnly?a.stream().filter(row->row.userId()==s.userId).toList():a)));Map<String,Object> result=new LinkedHashMap<>();result.put("days",days);result.put("holidays",ServerEmployeeScheduleService.loadHolidays(start,end).values());result.put("employees",selfOnly?ServerEmployeeScheduleService.loadActiveEmployees(location).stream().filter(e->e.userId()==s.userId).toList():ServerEmployeeScheduleService.loadActiveEmployees(location));result.put("shifts",selfOnly?List.of():ServerEmployeeScheduleService.loadShifts(location,true));String after=revision(location,start,end);if(!before.equals(after))throw err(409,"STALE_SCHEDULE","The schedule changed while loading. Reload the week.");result.put("revision",after);result.put("scope",Map.of("locationId",location,"start",start,"end",end));result.put("selfOnly",selfOnly);return result;});}
    private Object update(Connection c,JsonObject b)throws Exception{Session s=current.get();return bound(s,()->{String action=required(b,"action",40).toUpperCase(Locale.ROOT);Map<String,Object>r=new LinkedHashMap<>();switch(action){case"SAVE_HOLIDAY"->ServerEmployeeScheduleService.saveHoliday(c,date(b,"date"),optional(b,"name"));case"REMOVE_HOLIDAY"->ServerEmployeeScheduleService.removeHoliday(c,date(b,"date"));case"ADD_EMPLOYEES"->{ServerEmployeeScheduleService.Employee e=GSON.fromJson(b.get("employee"),ServerEmployeeScheduleService.Employee.class);ServerEmployeeScheduleService.addEmployees(c,integer(b,"locationId"),date(b,"start"),List.of(e),uuid(b,"shiftId",false),time(b,"lunchStart"));}case"UPDATE_ASSIGNMENT"->ServerEmployeeScheduleService.updateAssignment(c,integer(b,"locationId"),integer(b,"userId"),date(b,"date"),uuid(b,"shiftId",false),time(b,"lunchStart"));case"REMOVE_EMPLOYEE"->ServerEmployeeScheduleService.removeEmployee(c,integer(b,"locationId"),integer(b,"userId"),date(b,"date"));case"CLEAR"->{LocalDate start=date(b,"start"),end=date(b,"end");validateClear(b,start,end);r.put("removed",ServerEmployeeScheduleService.clearSchedule(c,integer(b,"locationId"),start,end));}case"SAVE_SHIFT"->r.put("shift",ServerEmployeeScheduleService.saveShift(c,integer(b,"locationId"),uuid(b,"shiftId",true),required(b,"name",300),time(b,"startTime"),time(b,"endTime"),!b.has("active")||b.get("active").getAsBoolean(),b.has("displayOrder")?b.get("displayOrder").getAsInt():0,false));case"SHIFT_ORDER"->{UUID[]ids=GSON.fromJson(b.get("shiftIds"),UUID[].class);ServerEmployeeScheduleService.updateShiftOrder(c,integer(b,"locationId"),ids==null?List.of():List.of(ids));}default->throw err(400,"VALIDATION_ERROR","Unknown schedule action.");}r.putIfAbsent("updated",true);audit(c,"SCHEDULER_WEB_UPDATED",s.userId,action);return r;});}
    private Object generate(JsonObject b)throws Exception{Session s=current.get();return bound(s,()->{validateRange(date(b,"start"),date(b,"end"));if(proposals.size()>=256)throw err(503,"PREVIEW_BUSY","Please try again shortly.");Integer[]ids=GSON.fromJson(b.get("employeeIds"),Integer[].class);var p=ServerEmployeeAutoScheduleService.generateRange(integer(b,"locationId"),date(b,"start"),date(b,"end"),ids==null?null:Set.of(ids));proposals.put(p.proposalId(),new SavedProposal(s.userId,p,Instant.now().plus(PROPOSAL_TTL)));return Map.of("proposal",p);});}
    private Object apply(Connection c,JsonObject b)throws Exception{Session s=current.get();UUID id=uuid(b,"proposalId",false);SavedProposal saved=proposals.remove(id);if(saved==null||saved.userId!=s.userId||!saved.expires.isAfter(Instant.now()))throw err(409,"PROPOSAL_EXPIRED","Regenerate the automatic schedule preview.");return bound(s,()->{int inserted=ServerEmployeeAutoScheduleService.apply(c,saved.proposal);audit(c,"SCHEDULER_WEB_AUTO_APPLIED",s.userId,"Applied proposal "+id);return Map.of("inserted",inserted);});}

    private final ThreadLocal<Session> current=new ThreadLocal<>();
    private <T>T bound(Session s,SqlWork<T>w)throws Exception{ServerEmployeeScheduleService.bindRequest(s.userId,s.locationId,s.displayName,s.permissions);ServerEmployeeAutoScheduleService.bindRequest(s.userId,s.locationId,s.displayName,s.permissions);current.set(s);try{return w.run();}finally{current.remove();ServerEmployeeScheduleService.clearRequest();ServerEmployeeAutoScheduleService.clearRequest();}}
    private Session requireSession(HttpExchange x,boolean csrf)throws Exception{String token=cookie(x,"ss_scheduler");if(token==null)throw err(401,"SESSION_REQUIRED","Sign in to continue.");Instant now=Instant.now();try(Connection c=DB.getConnection()){c.setAutoCommit(false);try{requireAvailable(c);}catch(Exception e){c.rollback();c.setAutoCommit(true);throw e;}try(PreparedStatement ps=c.prepareStatement("SELECT session_id,user_id,auth_user_id,csrf_hash,expires_at,absolute_expires_at FROM scheduler_web_sessions WHERE session_hash=? AND revoked_at IS NULL FOR UPDATE")){ps.setString(1,LanSecurity.sha256(token));try(ResultSet r=ps.executeQuery()){if(!r.next()||!sessionAlive(r.getTimestamp(5).toInstant(),r.getTimestamp(6).toInstant(),now))throw err(401,"SESSION_EXPIRED","Sign in again.");if(csrf){String supplied=x.getRequestHeaders().getFirst("X-CSRF-Token");validateCsrf(supplied,r.getString(4));}User u=userByAuth(c,(UUID)r.getObject(3));if(u.userId!=r.getInt(2))throw err(401,"SESSION_EXPIRED","Sign in again.");Set<String>permissions=permissions(c,u.userId);requireWebAccess(permissions);Instant absolute=r.getTimestamp(6).toInstant(),next=now.plus(IDLE).isBefore(absolute)?now.plus(IDLE):absolute;try(PreparedStatement q=c.prepareStatement("UPDATE scheduler_web_sessions SET expires_at=?,last_seen_at=CURRENT_TIMESTAMP WHERE session_id=?")){q.setTimestamp(1,Timestamp.from(next));q.setObject(2,r.getObject(1));q.executeUpdate();}c.commit();return new Session((UUID)r.getObject(1),u.userId,u.locationId,u.displayName,permissions);}}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}}
    private Object idempotent(HttpExchange x,Session s,JsonObject b,String operation,DbWork work)throws Exception{String key=x.getRequestHeaders().getFirst("Idempotency-Key");if(key==null||key.isBlank()||key.length()>160)throw err(400,"IDEMPOTENCY_REQUIRED","A valid idempotency key is required.");String hash=LanSecurity.sha256(GSON.toJson(b));current.set(s);try(Connection c=DB.getConnection()){c.setAutoCommit(false);try{requireAvailable(c);revalidateMutation(c,s);try(PreparedStatement lock=c.prepareStatement("SELECT pg_advisory_xact_lock(hashtextextended(?,0))")){lock.setString(1,s.id+":"+key);lock.execute();}try(PreparedStatement q=c.prepareStatement("SELECT operation_key,request_hash,response_json::text FROM scheduler_web_idempotency WHERE session_id=? AND idempotency_key=?")){q.setObject(1,s.id);q.setString(2,key);try(ResultSet r=q.executeQuery()){if(r.next()){if(!operation.equals(r.getString(1))||!hash.equals(r.getString(2)))throw err(409,"IDEMPOTENCY_CONFLICT","That request key was already used.");c.commit();return GSON.fromJson(r.getString(3),Object.class);}}}if("scheduler.update".equals(operation))requireRevision(c,b);Object result=work.run(c);try(PreparedStatement q=c.prepareStatement("INSERT INTO scheduler_web_idempotency(session_id,idempotency_key,operation_key,request_hash,response_json) VALUES(?,?,?,?,?::jsonb)")){q.setObject(1,s.id);q.setString(2,key);q.setString(3,operation);q.setString(4,hash);q.setString(5,GSON.toJson(result));q.executeUpdate();}c.commit();return result;}catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}finally{current.remove();}}



    static boolean sessionAlive(Instant idle,Instant absolute,Instant now){return idle.isAfter(now)&&absolute.isAfter(now);}
    static void validateCsrf(String supplied,String stored)throws WebError{
        if(supplied==null||stored==null||!LanSecurity.constantTimeEquals(LanSecurity.sha256(supplied),stored))throw err(403,"CSRF_INVALID","Refresh the page and try again.");
    }
    static void requireAssurance(boolean mfaRequired,String aal)throws WebError{
        if(mfaRequired){requireAal2(aal);return;}
        if(!"aal1".equals(aal)&&!"aal2".equals(aal))throw err(401,"AUTH_INVALID","The online session was not accepted.");
    }
    static void requireAal2(String aal)throws WebError{
        if(!"aal2".equals(aal))throw err(401,"MFA_REQUIRED","Authenticator verification is required.");
    }
    static WebError publicError(Exception e){
        if(e instanceof SQLException sql){
            String state=sql.getSQLState();
            if(Set.of("23505","40001","40P01","55P03").contains(state==null?"":state))return err(409,"SCHEDULE_CONFLICT","The schedule changed or is busy. Reload and try again.");
            if(state==null||state.startsWith("22")||state.startsWith("23"))return err(400,"VALIDATION_ERROR","Check the selected employee, store, shift, dates and times.");
        }
        if(e instanceof IllegalArgumentException||e instanceof JsonParseException)return err(400,"VALIDATION_ERROR","The request contains invalid values.");
        return err(503,"SERVER_UNAVAILABLE","The scheduler could not complete that request. Please try again.");
    }
    private String revision(int location,LocalDate start,LocalDate end)throws Exception{
        try(Connection c=DB.getConnection()){return SchedulerWebRevision.read(c,location,start,end);}
    }
    private void requireRevision(Connection c,JsonObject b)throws Exception{
        if(!b.has("scope")||!b.get("scope").isJsonObject())throw err(400,"REVISION_REQUIRED","Reload the schedule before editing.");
        JsonObject scope=b.getAsJsonObject("scope");int location=integer(scope,"locationId");LocalDate start=date(scope,"start"),end=date(scope,"end");validateRange(start,end);
        if(b.has("locationId")&&integer(b,"locationId")!=location)throw err(400,"VALIDATION_ERROR","Schedule store does not match.");
        for(String key:List.of("date","start","end"))if(b.has(key)){LocalDate d=date(b,key);if(d.isBefore(start)||d.isAfter(end))throw err(400,"VALIDATION_ERROR","Choose a date in the displayed period.");}
        String expected=required(b,"revision",64);
        SchedulerWebRevision.lockForWrite(c);
        if(!expected.equals(SchedulerWebRevision.read(c,location,start,end)))throw err(409,"STALE_SCHEDULE","The schedule changed. Reload the week before saving.");
    }

    private void requireAvailable(Connection c)throws Exception{
        if(ServerRoleGuard.state()!=ServerRoleGuard.State.PRIMARY)throw err(503,"SERVER_INACTIVE","The active store server is unavailable.");
        try(PreparedStatement p=c.prepareStatement("SELECT generation FROM scheduler_web_runtime WHERE runtime_id=1 AND enabled=TRUE FOR SHARE");ResultSet r=p.executeQuery()){
            if(!r.next()||!generation.equals(r.getObject(1)))throw err(503,"SCHEDULER_STOPPED","The scheduler was stopped or restarted. Sign in again.");
        }
    }
    private void revalidateMutation(Connection c,Session s)throws Exception{
        try(PreparedStatement p=c.prepareStatement("SELECT auth_user_id FROM scheduler_web_sessions WHERE session_id=? AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP AND absolute_expires_at>CURRENT_TIMESTAMP FOR UPDATE")){
            p.setObject(1,s.id);try(ResultSet r=p.executeQuery()){if(!r.next())throw err(401,"SESSION_EXPIRED","Sign in again.");if(userByAuth(c,(UUID)r.getObject(1)).userId!=s.userId)throw err(401,"SESSION_EXPIRED","Sign in again.");}
        }
        User u=user(c,s.userId);Set<String> granted=permissions(c,u.userId);requireWebAccess(granted);
        if(!granted.contains("EDIT_EMPLOYEE_SCHEDULE"))throw err(403,"EDIT_DENIED","This account cannot edit schedules.");
        current.set(new Session(s.id,u.userId,u.locationId,u.displayName,granted));
    }
    private void prune(){
        Instant now=Instant.now();preauths.entrySet().removeIf(e->!e.getValue().expires.isAfter(now));proposals.entrySet().removeIf(e->!e.getValue().expires.isAfter(now));
    }
    private void reserveAttempt(String key,String address)throws Exception{
        try(Connection c=DB.getConnection()){c.setAutoCommit(false);try{
            try(PreparedStatement p=c.prepareStatement("SELECT pg_advisory_xact_lock(734982157)")){p.execute();}
            rateLimit(c,key,address);recordAttempt(c,key,address,false);c.commit();
        }catch(Exception e){c.rollback();throw e;}finally{c.setAutoCommit(true);}}
    }
    static String password(JsonObject b)throws WebError{
        String value=optional(b,"password");if(value==null||value.isEmpty()||value.length()>4096)throw err(400,"VALIDATION_ERROR","Password is required.");return value;
    }
    static boolean canEdit(Set<String> permissions){return permissions!=null&&permissions.contains("EDIT_EMPLOYEE_SCHEDULE");}
    static String qrData(String qr){
        if(qr==null||qr.startsWith("data:image/"))return qr;
        return "data:image/svg+xml;base64,"+Base64.getEncoder().encodeToString(qr.getBytes(StandardCharsets.UTF_8));
    }
    static void validateRange(LocalDate start,LocalDate end)throws WebError{
        if(end.isBefore(start)||java.time.temporal.ChronoUnit.DAYS.between(start,end)>30)throw err(400,"VALIDATION_ERROR","Choose a period of at most 31 days.");
    }
    static void validateClear(JsonObject b,LocalDate start,LocalDate end)throws WebError{
        validateRange(start,end);if(!(start+"/"+end).equals(optional(b,"confirmation")))throw err(400,"CONFIRMATION_REQUIRED","Confirm the exact period before clearing assignments.");
    }

    private JsonObject supabase(SupabaseProjectConfig cfg,String path,String bearer,JsonObject payload)throws Exception{HttpRequest.Builder req=HttpRequest.newBuilder(URI.create(cfg.url()+path)).timeout(Duration.ofSeconds(20)).header("apikey",cfg.publishableKey());if(bearer!=null)req.header("Authorization","Bearer "+bearer);if(payload==null)req.GET();else req.header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(GSON.toJson(payload)));HttpResponse<String>res=http.send(req.build(),HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(res.statusCode()<200||res.statusCode()>=300)throw err(401,"AUTH_FAILED","The sign-in or authenticator code was not accepted.");return JsonParser.parseString(res.body()).getAsJsonObject();}
    private void requireSchema(Connection c)throws SQLException{for(String table:List.of("scheduler_web_runtime","scheduler_web_sessions","scheduler_web_auth_attempts","scheduler_web_idempotency"))try(PreparedStatement ps=c.prepareStatement("SELECT to_regclass(?) IS NOT NULL")){ps.setString(1,"public."+table);try(ResultSet rs=ps.executeQuery()){if(!rs.next()||!rs.getBoolean(1))throw new SQLException("Apply the scheduler web database migration before starting the gateway.");}}}
    private User userByAuth(Connection c,UUID auth)throws Exception{auth=authConfig.localSubject(auth);if(auth==null)throw err(403,"ACCOUNT_DENIED","This account is not enabled for this test scheduler.");try(PreparedStatement p=c.prepareStatement("SELECT u.user_id,COALESCE(NULLIF(TRIM(u.full_name),''),u.username),COALESCE((SELECT MIN(ul.location_id) FROM user_locations ul WHERE ul.user_id=u.user_id),(SELECT MIN(location_id) FROM locations)) FROM users u WHERE u.auth_user_id=? AND u.is_active=TRUE")){p.setObject(1,auth);try(ResultSet r=p.executeQuery()){if(!r.next())throw err(403,"ACCOUNT_DENIED","No active SmartStock account matches this login.");return new User(r.getInt(1),r.getString(2),r.getInt(3));}}}
    private String resolveLoginEmail(Connection c,String identifier)throws Exception{String normalized=identifier.trim().toLowerCase(Locale.ROOT);if(normalized.contains("@"))return normalized;try(PreparedStatement p=c.prepareStatement("SELECT LOWER(TRIM(email)) FROM users WHERE LOWER(TRIM(username))=? AND COALESCE(is_active,TRUE)=TRUE AND NULLIF(TRIM(email),'') IS NOT NULL ORDER BY user_id LIMIT 2")){p.setString(1,normalized);try(ResultSet r=p.executeQuery()){if(!r.next())throw err(401,"AUTH_FAILED","The sign-in was not accepted.");String email=r.getString(1);if(r.next())throw err(401,"AUTH_FAILED","The sign-in was not accepted.");return email;}}}
    private User user(Connection c,int id)throws Exception{try(PreparedStatement p=c.prepareStatement("SELECT u.user_id,COALESCE(NULLIF(TRIM(u.full_name),''),u.username),COALESCE((SELECT MIN(ul.location_id) FROM user_locations ul WHERE ul.user_id=u.user_id),(SELECT MIN(location_id) FROM locations)) FROM users u WHERE u.user_id=? AND u.is_active=TRUE")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())throw err(403,"ACCOUNT_DENIED","This account is no longer active.");return new User(r.getInt(1),r.getString(2),r.getInt(3));}}}
    private Set<String> permissions(Connection c,int id)throws SQLException{Set<String>out=new HashSet<>();try(PreparedStatement p=c.prepareStatement("SELECT UPPER(p.permission_key) FROM users u JOIN role_permissions rp ON rp.role_id=u.role_id JOIN permissions p ON p.permission_id=rp.permission_id WHERE u.user_id=? UNION SELECT UPPER(rmp.permission_key) FROM users u JOIN role_mobile_permissions rmp ON rmp.role_id=u.role_id WHERE u.user_id=?")){p.setInt(1,id);p.setInt(2,id);try(ResultSet r=p.executeQuery()){while(r.next())out.add(r.getString(1));}}return Set.copyOf(out);}
    private void requireWebAccess(Connection c,int id)throws Exception{requireWebAccess(permissions(c,id));}private void requireWebAccess(Set<String>p)throws WebError{if(!p.contains("ACCESS_SCHEDULER_WEB")||!p.contains("VIEW_EMPLOYEE_SCHEDULE"))throw err(403,"SCHEDULER_WEB_DENIED","This account is not allowed to use the scheduler web app.");}
    private void rateLimit(Connection c,String key,String address)throws Exception{try(PreparedStatement p=c.prepareStatement("SELECT count(*) FROM scheduler_web_auth_attempts WHERE succeeded=FALSE AND attempted_at>CURRENT_TIMESTAMP-INTERVAL '15 minutes' AND (identifier_hash=? OR remote_address=?)")){p.setString(1,key);p.setString(2,address);try(ResultSet r=p.executeQuery()){r.next();if(r.getInt(1)>=8)throw err(429,"LOGIN_THROTTLED","Too many sign-in attempts. Wait 15 minutes.");}}}
    private void recordAttempt(Connection c,String key,String address,boolean ok)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO scheduler_web_auth_attempts(identifier_hash,remote_address,succeeded) VALUES(?,?,?)")){p.setString(1,key);p.setString(2,address);p.setBoolean(3,ok);p.executeUpdate();}}
    private void audit(Connection c,String type,int user,String details)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO security_audit_events(event_type,actor_user_id,details) VALUES(?,?,?)")){p.setString(1,type);p.setInt(2,user);p.setString(3,details);p.executeUpdate();}}
    private void sameOrigin(HttpExchange x)throws WebError{String origin=x.getRequestHeaders().getFirst("Origin");if(origin==null||!publicOrigin.equalsIgnoreCase(origin))throw err(403,"ORIGIN_DENIED","This web origin is not allowed.");}
    static String cleanOrigin(String v){if(v==null||v.isBlank())return null;try{URI u=URI.create(v.trim());if(!"https".equalsIgnoreCase(u.getScheme())||u.getHost()==null||u.getRawQuery()!=null||u.getRawFragment()!=null||u.getRawUserInfo()!=null||(u.getRawPath()!=null&&!u.getRawPath().isEmpty()&&!u.getRawPath().equals("/")))return null;return u.getPort()<0?"https://"+u.getHost():"https://"+u.getHost()+":"+u.getPort();}catch(Exception e){return null;}}
    private static String remote(HttpExchange x){String f=x.getRequestHeaders().getFirst("CF-Connecting-IP");return f!=null&&f.length()<=45&&f.matches("[0-9a-fA-F:.]+")?f:x.getRemoteAddress().getAddress().getHostAddress();}
    private static JsonObject body(HttpExchange x)throws Exception{byte[]b=x.getRequestBody().readNBytes(1024*1024+1);if(b.length>1024*1024)throw err(413,"REQUEST_TOO_LARGE","Request too large.");try{return b.length==0?new JsonObject():JsonParser.parseString(new String(b,StandardCharsets.UTF_8)).getAsJsonObject();}catch(RuntimeException e){throw err(400,"VALIDATION_ERROR","A JSON object is required.");}}
    private static String jwt(String token,String key){try{String[]p=token.split("\\.");JsonObject j=JsonParser.parseString(new String(Base64.getUrlDecoder().decode(p[1]),StandardCharsets.UTF_8)).getAsJsonObject();return str(j,key);}catch(Exception e){return null;}}
    private static String required(JsonObject b,String k,int max)throws WebError{String v=optional(b,k);if(v==null||v.isBlank()||v.length()>max)throw err(400,"VALIDATION_ERROR",k+" is required.");return v.trim();}private static String optional(JsonObject b,String k){return b.has(k)&&!b.get(k).isJsonNull()?b.get(k).getAsString():null;}private static String str(JsonObject b,String k){return b!=null&&b.has(k)&&!b.get(k).isJsonNull()?b.get(k).getAsString():null;}private static int integer(JsonObject b,String k)throws WebError{try{return b.get(k).getAsInt();}catch(Exception e){throw err(400,"VALIDATION_ERROR",k+" is invalid.");}}private static LocalDate date(JsonObject b,String k)throws WebError{try{return LocalDate.parse(required(b,k,40));}catch(Exception e){throw err(400,"VALIDATION_ERROR",k+" is invalid.");}}private static LocalTime time(JsonObject b,String k)throws WebError{try{return LocalTime.parse(required(b,k,20));}catch(Exception e){throw err(400,"VALIDATION_ERROR",k+" is invalid.");}}private static UUID uuid(JsonObject b,String k,boolean nullable)throws WebError{String v=optional(b,k);if(nullable&&(v==null||v.isBlank()))return null;try{return UUID.fromString(v);}catch(Exception e){throw err(400,"VALIDATION_ERROR",k+" is invalid.");}}private static String url(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8);}
    private static void cookie(HttpExchange x,String name,String value,int age){x.getResponseHeaders().add("Set-Cookie",name+"="+value+"; Path=/scheduler; Max-Age="+age+"; Secure; HttpOnly; SameSite=Strict");}private static void clearCookie(HttpExchange x,String name){cookie(x,name,"",0);}private static String cookie(HttpExchange x,String name){String h=x.getRequestHeaders().getFirst("Cookie");if(h!=null)for(String p:h.split(";")){String[]kv=p.trim().split("=",2);if(kv.length==2&&name.equals(kv[0]))return kv[1];}return null;}
    private static void headers(HttpExchange x){Headers h=x.getResponseHeaders();h.set("Cache-Control","no-store");h.set("X-Content-Type-Options","nosniff");h.set("X-Frame-Options","DENY");h.set("Referrer-Policy","no-referrer");h.set("Permissions-Policy","camera=(), microphone=(), geolocation=()");h.set("Content-Security-Policy","default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; manifest-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");}
    private static void json(HttpExchange x,int status,Object v){try{byte[]b=GSON.toJson(v).getBytes(StandardCharsets.UTF_8);headers(x);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.sendResponseHeaders(status,b.length);x.getResponseBody().write(b);}catch(Exception ignored){}}private static void text(HttpExchange x,int status,String type,String v)throws IOException{byte[]b=v.getBytes(StandardCharsets.UTF_8);headers(x);x.getResponseHeaders().set("Content-Type",type);x.sendResponseHeaders(status,b.length);x.getResponseBody().write(b);}
    private static WebError err(int status,String code,String message){return new WebError(status,code,message);}public void close(){server.stop(2);executor.shutdownNow();preauths.clear();proposals.clear();}
    private record Preauth(String accessToken,UUID authUserId,String factorId,String challengeId,Instant expires,String identifierHash,String address){}private record User(int userId,String displayName,int locationId){}private record Session(UUID id,int userId,int locationId,String displayName,Set<String>permissions){}private record SavedProposal(int userId,ServerEmployeeAutoScheduleService.AutoScheduleProposal proposal,Instant expires){}private interface SqlWork<T>{T run()throws Exception;}private interface DbWork{Object run(Connection c)throws Exception;}static final class WebError extends Exception{final int status;final String code;WebError(int s,String c,String m){super(m);status=s;code=c;}}
}
