(()=>{'use strict';
const $=id=>document.getElementById(id),orderId=new URLSearchParams(location.search).get('orderId');
const api=`https://${location.hostname}:8445/api/v1`;let csrf='',documents=[],files=[],proofs=[],active=null,selected=null,tool='select',zoom=1,fit=1,drag=null,undo=[],redo=[],dirty=false,saving=false,savePromise=null,saveTimer=null,readonly=false;const images=new Map();
const clone=x=>JSON.parse(JSON.stringify(x));const toast=message=>{const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),5000)};
async function call(route,body={},write=false){const res=await fetch(`${api}${route}`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json',...(write?{'X-CSRF-Token':csrf,'Idempotency-Key':crypto.randomUUID()}:{})},body:JSON.stringify(body)});const reply=await res.json().catch(()=>null);if(!res.ok||!reply?.ok)throw new Error(reply?.error?.message||`Server error ${res.status}`);return reply.data}
async function signIn(){try{const data=await call('/session');csrf=data.csrfToken;$('auth').classList.add('hidden');$('app').classList.remove('hidden');await load()}catch(e){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('saveState').textContent='Sign in required';toast(e.message)}}
async function load(){if(!orderId||!/^[0-9]+$/.test(orderId))throw new Error('Open this workspace from a saved custom order.');const data=await call('/design/state',{orderId:Number(orderId)});documents=data.documents;files=data.files;proofs=data.proofs;const requested=new URLSearchParams(location.search).get('lineId');const choice=documents.find(d=>String(d.lineId||'')===requested)||documents.find(d=>d.lineId)||documents[0];await choose(choice.id)}
function unitInches(value,unit){return value*({IN:1,FT:12,YD:36,CM:1/2.54,M:100/2.54}[unit]||1)}
function logical(){return {w:1000,h:1000*Number(active.height)/Number(active.width)}}
function status(){let text=readonly?'Read only':saving?'Saving…':dirty?'Unsaved changes':`Saved · revision ${active?.revision??0}`;$('saveState').textContent=text}
function listDocuments(){const box=$('documents');box.replaceChildren();for(const d of documents){const button=document.createElement('button');button.className='doc'+(active?.id===d.id?' active':'');const strong=document.createElement('strong');strong.textContent=d.lineId?d.name+(d.variant?` / ${d.variant}`:''):'Order overview';const small=document.createElement('small');small.textContent=`${d.width} × ${d.height} ${d.unit}${d.lineId?'':' · Staff board'}`;button.append(strong,small);button.onclick=()=>choose(d.id).catch(e=>toast(e.message));box.append(button)}}
async function choose(id){if(active?.id===id)return;if(dirty||saving)await save();active=documents.find(d=>d.id===id);if(!active)throw new Error('Design unavailable.');selected=null;undo=[];redo=[];readonly=['DELIVERED','CANCELLED'].includes(active.orderStatus);$('background').value=active.document.background||'#ffffff';$('dimensions').textContent=`${active.width} × ${active.height} ${active.unit} · ${active.lineId?'Order line':'Overview board'}`;listDocuments();refreshFiles();refreshLayers();properties();proofStatus();resize();for(const object of active.document.objects)if(object.type==='image')fetchImage(object.fileId).catch(e=>toast(e.message));status()}
function proofStatus(){const p=proofs.find(p=>p.lineId===active?.lineId);$('proofStatus').textContent=!active?.lineId?'The overview is for staff and is not sent for approval.':p?`Customer proof ${p.revision}: ${p.status.replaceAll('_',' ')}${p.feedback?` · ${p.feedback}`:''}`:'No design sent to the customer yet.';$('send').disabled=!active?.lineId||readonly;$('save').disabled=readonly}
function resize(){if(!active)return;const {w,h}=logical();const scroll=$('canvasScroll');fit=Math.min(1,(scroll.clientWidth-90)/w,(scroll.clientHeight-90)/h);fit=Math.max(.08,fit);const scale=Math.min(2,devicePixelRatio||1);const canvas=$('canvas');canvas.width=Math.max(1,Math.round(w*scale));canvas.height=Math.max(1,Math.round(h*scale));canvas.style.width=`${w*fit*zoom}px`;canvas.style.height=`${h*fit*zoom}px`;paint()}
function paint(){if(!active)return;const canvas=$('canvas'),ctx=canvas.getContext('2d');const {w,h}=logical(),scale=canvas.width/w;ctx.setTransform(scale,0,0,scale,0,0);drawScene(ctx,w,h,true)}
function drawScene(ctx,w,h,chrome){ctx.clearRect(0,0,w,h);ctx.fillStyle=active.document.background;ctx.fillRect(0,0,w,h);for(const o of active.document.objects)drawObject(ctx,o);if(chrome&&$('guides').checked){ctx.save();ctx.strokeStyle='#0d979966';ctx.lineWidth=1;ctx.setLineDash([9,9]);ctx.strokeRect(35,35,w-70,h-70);ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w/2,h);ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();ctx.restore()}if(chrome&&selected){const o=current();if(o){ctx.save();ctx.strokeStyle='#027c86';ctx.lineWidth=2;ctx.setLineDash([7,4]);ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.setLineDash([]);ctx.fillStyle='#027c86';ctx.fillRect(o.x+o.w-7,o.y+o.h-7,14,14);ctx.restore()}}}
function drawObject(ctx,o){ctx.save();ctx.fillStyle=o.fill||'#19313c';ctx.strokeStyle=o.fill||'#19313c';ctx.lineWidth=Math.max(1,Number(o.strokeWidth)||3);if(o.type==='rect')ctx.fillRect(o.x,o.y,o.w,o.h);else if(o.type==='ellipse'){ctx.beginPath();ctx.ellipse(o.x+o.w/2,o.y+o.h/2,Math.max(1,Math.abs(o.w/2)),Math.max(1,Math.abs(o.h/2)),0,0,Math.PI*2);ctx.fill()}else if(o.type==='line'){ctx.beginPath();ctx.moveTo(o.x,o.y);ctx.lineTo(o.x+o.w,o.y+o.h);ctx.stroke()}else if(o.type==='path'){const pts=o.points||[];if(pts.length){ctx.beginPath();ctx.moveTo(o.x+pts[0][0],o.y+pts[0][1]);for(const p of pts.slice(1))ctx.lineTo(o.x+p[0],o.y+p[1]);ctx.stroke()}}else if(o.type==='text'){const size=Math.max(8,Math.min(240,Number(o.size)||48));ctx.font=`${o.bold?'bold ':''}${size}px ${JSON.stringify(o.font||'Arial')}`;ctx.textBaseline='top';let y=o.y;for(const line of String(o.text||'').split('\n')){ctx.fillText(line,o.x+4,y,Math.max(1,o.w-8));y+=size*1.25}}else if(o.type==='image'){const img=images.get(o.fileId)?.image;if(img?.complete&&img.naturalWidth){const factor=Math.max(o.w/img.naturalWidth,o.h/img.naturalHeight);const sw=o.w/factor,sh=o.h/factor,sx=(img.naturalWidth-sw)/2,sy=(img.naturalHeight-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,o.x,o.y,o.w,o.h)}else{ctx.fillStyle='#dce9eb';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#4c6f78';ctx.font='20px Arial';ctx.fillText('Loading image…',o.x+15,o.y+20)}}ctx.restore()}
function current(){return active?.document.objects.find(o=>o.id===selected)}
function checkpoint(){undo.push(clone(active.document));if(undo.length>50)undo.shift();redo=[]}
function changed(){dirty=true;status();paint();refreshLayers();clearTimeout(saveTimer);saveTimer=setTimeout(()=>save().catch(e=>toast(e.message)),1100)}
async function save(){if(savePromise){await savePromise;if(dirty)return save();return}if(!dirty||readonly)return;saving=true;status();const document=clone(active.document),id=active.id,revision=active.revision;dirty=false;savePromise=(async()=>{try{const result=await call('/design/save',{orderId:Number(orderId),documentId:id,revision,document},true);const row=documents.find(d=>d.id===id);row.revision=result.revision}catch(e){dirty=true;throw e}finally{saving=false;savePromise=null;status()}})();await savePromise;if(dirty)return save()}
function point(event){const rect=$('canvas').getBoundingClientRect(),{w,h}=logical();return{x:(event.clientX-rect.left)*w/rect.width,y:(event.clientY-rect.top)*h/rect.height}}
function hit(x,y){const items=active.document.objects;for(let i=items.length-1;i>=0;i--){const o=items[i];if(x>=Math.min(o.x,o.x+o.w)-6&&x<=Math.max(o.x,o.x+o.w)+6&&y>=Math.min(o.y,o.y+o.h)-6&&y<=Math.max(o.y,o.y+o.h)+6)return o}return null}
function make(type,x,y){return{id:crypto.randomUUID(),type,x,y,w:type==='text'?340:1,h:type==='text'?80:1,fill:'#183b47',text:type==='text'?'Your text':'',font:'Arial',size:48,bold:false}}
$('canvas').addEventListener('pointerdown',event=>{if(readonly)return;const p=point(event);$('canvas').setPointerCapture(event.pointerId);if(tool==='select'){const o=hit(p.x,p.y);selected=o?.id||null;properties();refreshLayers();paint();if(o){checkpoint();drag={kind:p.x>o.x+o.w-16&&p.y>o.y+o.h-16?'resize':'move',id:o.id,start:p,initial:clone(o)};}}else{checkpoint();const o=make(tool==='draw'?'path':tool,p.x,p.y);if(tool==='text'){o.w=340;o.h=75;active.document.objects.push(o);selected=o.id;properties();changed();setTool('select');$('objectText').focus();return}if(tool==='draw'){o.w=1;o.h=1;o.points=[[0,0]]}active.document.objects.push(o);selected=o.id;drag={kind:'create',id:o.id,start:p,initial:clone(o)};properties();paint()}});
$('canvas').addEventListener('pointermove',event=>{if(!drag)return;const p=point(event),o=current();if(!o)return;const dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(drag.kind==='move'){o.x=drag.initial.x+dx;o.y=drag.initial.y+dy;const {w,h}=logical();if(Math.abs(o.x+o.w/2-w/2)<8)o.x=w/2-o.w/2;if(Math.abs(o.y+o.h/2-h/2)<8)o.y=h/2-o.h/2}else if(drag.kind==='resize'){o.w=Math.max(8,drag.initial.w+dx);o.h=Math.max(8,drag.initial.h+dy)}else if(o.type==='path'){o.points.push([dx,dy]);o.w=Math.max(o.w,dx);o.h=Math.max(o.h,dy)}else{o.x=Math.min(drag.start.x,p.x);o.y=Math.min(drag.start.y,p.y);o.w=Math.max(3,Math.abs(dx));o.h=Math.max(3,Math.abs(dy))}paint()});
function endDrag(){if(!drag)return;drag=null;changed();properties()};$('canvas').addEventListener('pointerup',endDrag);$('canvas').addEventListener('pointercancel',endDrag);
function setTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===value))}document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
function properties(){const o=current();$('emptySelection').classList.toggle('hidden',!!o);$('properties').classList.toggle('hidden',!o);if(!o)return;$('objectText').parentElement.classList.toggle('hidden',o.type!=='text');$('font').parentElement.classList.toggle('hidden',o.type!=='text');$('fontSize').parentElement.classList.toggle('hidden',o.type!=='text');$('bold').parentElement.classList.toggle('hidden',o.type!=='text');$('objectColor').parentElement.classList.toggle('hidden',o.type==='image');$('objectText').value=o.text||'';$('objectColor').value=/^#[0-9a-f]{6}$/i.test(o.fill)?o.fill:'#19313c';$('fontSize').value=o.size||48;$('font').value=o.font||'Arial';$('bold').checked=!!o.bold}
function property(id,key,parse=v=>v){$(id).addEventListener('input',()=>{const o=current();if(!o)return;checkpoint();o[key]=parse($(id).type==='checkbox'?$(id).checked:$(id).value);changed()})}property('objectText','text');property('objectColor','fill');property('fontSize','size',Number);property('font','font');property('bold','bold');$('background').oninput=()=>{checkpoint();active.document.background=$('background').value;changed()};
function remove(){if(!selected||readonly)return;checkpoint();active.document.objects=active.document.objects.filter(o=>o.id!==selected);selected=null;properties();changed()}$('delete').onclick=remove;
function reorder(step){const list=active.document.objects,i=list.findIndex(o=>o.id===selected);if(i<0||i+step<0||i+step>=list.length)return;checkpoint();[list[i],list[i+step]]=[list[i+step],list[i]];changed()}$('front').onclick=()=>reorder(1);$('back').onclick=()=>reorder(-1);
function center(axis){const o=current();if(!o)return;checkpoint();const {w,h}=logical();if(axis==='x')o.x=(w-o.w)/2;else o.y=(h-o.h)/2;changed()}$('centerH').onclick=()=>center('x');$('centerV').onclick=()=>center('y');
function undoAction(){if(!undo.length||readonly)return;redo.push(clone(active.document));active.document=undo.pop();selected=null;properties();changed()}function redoAction(){if(!redo.length||readonly)return;undo.push(clone(active.document));active.document=redo.pop();selected=null;properties();changed()}$('undo').onclick=undoAction;$('redo').onclick=redoAction;
document.addEventListener('keydown',event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redoAction():undoAction()}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='y'){event.preventDefault();redoAction()}else if(event.key==='Delete')remove();else if(current()&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();checkpoint();const o=current(),n=event.shiftKey?10:1;if(event.key==='ArrowLeft')o.x-=n;if(event.key==='ArrowRight')o.x+=n;if(event.key==='ArrowUp')o.y-=n;if(event.key==='ArrowDown')o.y+=n;changed()}});
function refreshLayers(){const box=$('layers');box.replaceChildren();if(!active)return;for(const o of [...active.document.objects].reverse()){const b=document.createElement('button');b.className='layer'+(selected===o.id?' active':'');b.textContent=`${o.type==='text'?(o.text||'Text').slice(0,32):o.type[0].toUpperCase()+o.type.slice(1)}`;b.onclick=()=>{selected=o.id;properties();refreshLayers();paint()};box.append(b)}}
function refreshFiles(){const box=$('files');box.replaceChildren();if(!active?.lineId){box.textContent='Select an order line to place attachments.';return}const listed=files.filter(f=>f.lineId===active.lineId);if(!listed.length){box.textContent='No attachments on this line yet.';return}for(const f of listed){const b=document.createElement('button');b.className='file';b.textContent=f.name;const note=document.createElement('small');note.textContent=f.contentType.startsWith('image/')?'Place on canvas':`${Math.round(f.bytes/1024)} KB · Preview only`;b.append(note);b.disabled=!f.contentType.startsWith('image/')||readonly;b.onclick=()=>placeImage(f).catch(e=>toast(e.message));box.append(b)}}
async function uploadImage(file){if(!active?.lineId||readonly)throw new Error('Select an editable order line first.');if(file.size>6_291_456)throw new Error('Choose an image of at most 6 MB.');const lineId=active.lineId;const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('The image could not be read.'));reader.readAsDataURL(file)});const result=await call('/design/attach',{orderId:Number(orderId),lineId,filename:file.name,bytesBase64:encoded},true);const state=await call('/design/state',{orderId:Number(orderId)});files=state.files;refreshFiles();const added=files.find(f=>f.id===result.fileId);if(added&&active.lineId===lineId)await placeImage(added);else toast('Image uploaded to its order line.');}
async function fetchImage(fileId){if(images.has(fileId))return images.get(fileId).promise;const entry={image:null,promise:null};images.set(fileId,entry);entry.promise=(async()=>{const chunks=[];let offset=0,total=Infinity,mime='image/png';while(offset<total){const part=await call('/design/file',{orderId:Number(orderId),fileId,offset});const binary=atob(part.bytesBase64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);chunks.push(bytes);offset+=bytes.length;total=part.totalBytes;mime=part.contentType;if(!bytes.length)throw new Error('Attachment download stopped early.')}const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob);const img=new Image();img.src=url;await img.decode();entry.image=img;paint();return img})();return entry.promise}
async function placeImage(f){const img=await fetchImage(f.id);const {w,h}=logical();checkpoint();const width=Math.min(w*.65,img.naturalWidth),height=width*img.naturalHeight/img.naturalWidth;const o={id:crypto.randomUUID(),type:'image',fileId:f.id,x:(w-width)/2,y:(h-height)/2,w:width,h:height,fill:'#ffffff'};active.document.objects.push(o);selected=o.id;properties();changed();setPanel('style')}
function setPanel(value){document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===value));for(const name of ['style','layers','files'])$(`${name}Panel`).classList.toggle('hidden',name!==value)}document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>setPanel(b.dataset.panel));
function exportCanvas(dpi,limit){const inchesW=unitInches(Number(active.width),active.unit),inchesH=unitInches(Number(active.height),active.unit);let width=Math.round(inchesW*dpi),height=Math.round(inchesH*dpi);if(limit){const factor=Math.min(1,limit/Math.max(width,height));width=Math.max(1,Math.round(width*factor));height=Math.max(1,Math.round(height*factor))}else if(width>16000||height>16000||width*height>80_000_000)throw new Error('This design exceeds the browser print export limit. Use a smaller physical size or prepare a tiled production export.');const output=document.createElement('canvas');output.width=width;output.height=height;const ctx=output.getContext('2d');const {w,h}=logical();ctx.setTransform(width/w,0,0,height/h,0,0);drawScene(ctx,w,h,false);return output}
function canvasBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('The image could not be rendered.')),'image/png'))}
function crc32(bytes){let crc=0xffffffff;for(const value of bytes){crc^=value;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
async function withDpi(blob,dpi){const source=new Uint8Array(await blob.arrayBuffer());if(source.length<33||source[0]!==137||source[1]!==80||source[2]!==78||source[3]!==71)throw new Error('The exported PNG is invalid.');const chunk=new Uint8Array(21),view=new DataView(chunk.buffer);view.setUint32(0,9);chunk.set([112,72,89,115],4);const ppm=Math.round(dpi/0.0254);view.setUint32(8,ppm);view.setUint32(12,ppm);chunk[16]=1;view.setUint32(17,crc32(chunk.slice(4,17)));const output=new Uint8Array(source.length+chunk.length);output.set(source.slice(0,33));output.set(chunk,33);output.set(source.slice(33),54);return new Blob([output],{type:'image/png'})}
async function downloadExport(){try{await save();for(const o of active.document.objects)if(o.type==='image')await fetchImage(o.fileId);const png=await withDpi(await canvasBlob(exportCanvas(300)),300);const url=URL.createObjectURL(png),link=document.createElement('a');link.href=url;link.download=`custom-order-${orderId}-${active.lineId||'overview'}-300dpi.png`;link.click();setTimeout(()=>URL.revokeObjectURL(url),60_000);toast('300 DPI PNG exported. Check image resolution and production settings before printing.')}catch(e){toast(e.message)}}$('export').onclick=downloadExport;
async function send(){if(!active.lineId)return;try{await save();for(const o of active.document.objects)if(o.type==='image')await fetchImage(o.fileId);const png=await canvasBlob(exportCanvas(180,1600));if(png.size>8_388_608)throw new Error('Review image exceeds 8 MB. Reduce image detail before sending.');const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read review image.'));reader.readAsDataURL(png)});$('send').disabled=true;$('saveState').textContent='Sending…';const result=await call('/design/publish',{orderId:Number(orderId),lineId:active.lineId,documentId:active.id,revision:active.revision,pngBase64:encoded},true);await navigator.clipboard.writeText(result.approvalUrl).catch(()=>{});toast(`Customer link copied for proof revision ${result.revision}.`);const state=await call('/design/state',{orderId:Number(orderId)});proofs=state.proofs;proofStatus();window.prompt('Customer approval link (copy if needed):',result.approvalUrl)}catch(e){toast(e.message)}finally{proofStatus();status()}}$('send').onclick=send;
$('save').onclick=()=>save().then(()=>toast('Design saved.')).catch(e=>toast(e.message));$('uploadImage').onchange=event=>{const file=event.target.files?.[0];if(file)uploadImage(file).catch(e=>toast(e.message)).finally(()=>{event.target.value=''})};$('zoom').oninput=()=>{zoom=Number($('zoom').value)/100;$('zoomValue').textContent=`${$('zoom').value}%`;resize()};$('guides').onchange=paint;$('retry').onclick=signIn;window.addEventListener('resize',resize);window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});signIn();
})();
