// Keep the handoff page and API on one TLS origin. Phones that approved the
// page certificate must not be forced through a second certificate prompt on
// the separate administrative API port.
const $=id=>document.getElementById(id),token=new URLSearchParams(location.search).get('token')||'',API=`${location.origin}/api/v1`;let selected=null;
async function call(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);let response;try{response=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal})}catch(e){throw new Error('Cannot reach SmartStock. Stay on the store Wi-Fi and try again.')}finally{clearTimeout(timer)}const json=await response.json().catch(()=>({}));if(!response.ok||!json.ok)throw new Error(json.error?.message||`Request failed (${response.status})`);return json.data}
function status(message,error=false){$('photoStatus').textContent=message;$('photoStatus').style.color=error?'#b91c1c':''}
async function jpegBytes(file,max=1200,quality=.78){const url=URL.createObjectURL(file),img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});const scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const blob=await new Promise(ok=>canvas.toBlob(ok,'image/jpeg',quality));return new Uint8Array(await blob.arrayBuffer())}
function base64(bytes){let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
function choose(event){selected=event.target.files[0]||null;if(!selected)return;const url=URL.createObjectURL(selected);$('photoPreview').innerHTML=`<img alt="Selected item" src="${url}">`;$('photoUpload').disabled=false;status('Review the photo, then upload it.')}
$('photoCamera').onchange=choose;$('photoLibrary').onchange=choose;
$('photoUpload').onclick=async()=>{if(!selected)return;$('photoUpload').disabled=true;$('photoProgress').classList.remove('hidden');status('Uploading photo…');try{const bytes=await jpegBytes(selected);await call('/photo/upload',{token,bytesBase64:base64(bytes)});$('photoControls').classList.add('hidden');status('Photo uploaded. You can return to the computer.')}catch(e){status(e.message,true);$('photoUpload').disabled=false}finally{$('photoProgress').classList.add('hidden')}};
(async()=>{if(!token){status('This photo link is incomplete. Create a new QR code on the computer.',true);return}try{const target=await call('/photo/target',{token});$('targetName').textContent=target.targetName;$('photoControls').classList.remove('hidden');status('Take a clear photo or choose one from your phone.')}catch(e){status(e.message,true)}})();
