let spoilState=null,spoilSelected=null,spoilPhotos=[],spoilBusy=false,spoilPending=null;
try{spoilPending=JSON.parse(sessionStorage.getItem('smartstockPendingSpoil')||'null')}catch{}
async function openSpoils(){show('spoils');note('');if(spoilPending){await loadSpoilOrder(spoilPending.orderId);note('Retry the previous submission to confirm its result.');return}await findSpoilOrders()}
$('#openSpoils').onclick=openSpoils;
$('#spoilBack').onclick=()=>{if(!spoilBusy)show('home')};
$('#spoilSearch').onsubmit=e=>{e.preventDefault();findSpoilOrders()};
async function findSpoilOrders(){try{const data=await call('/spoils/search',{query:$('#spoilSearch [name="query"]').value});const root=$('#spoilOrders');root.replaceChildren();for(const order of data.orders){const b=document.createElement('button');b.type='button';b.textContent=`${order.number} / ${order.customer} / ${order.status}`;b.onclick=()=>{if(spoilPending&&Number(spoilPending.orderId)!==Number(order.orderId)){note('Retry the pending report before switching orders.',true);return}loadSpoilOrder(order.orderId)};root.append(b)}if(!data.orders.length)root.textContent='No matching orders.'}catch(e){note(e.message,true)}}
async function loadSpoilOrder(id){try{spoilState=await call('/spoils/state',{orderId:id});spoilSelected=id;$('#spoilOrder').textContent=`${spoilState.order.number} / ${spoilState.order.customer} / ${spoilState.order.status}`;const select=$('#spoilLine');select.replaceChildren();spoilState.lines.forEach((line,index)=>{const option=document.createElement('option');option.value=line.lineId;option.textContent=`Line ${index+1}: ${line.item}${line.variant?' / '+line.variant:''} / ${line.production}${line.eligible?'':' / read only'}`;select.append(option)});if(spoilPending)select.value=spoilPending.lineId;spoilPhotos.forEach(x=>URL.revokeObjectURL(x.url));spoilPhotos=[];renderSpoilPhotos();$('#spoilReason').value=spoilPending?.reason||'';$('#spoilForm').classList.toggle('hidden',!can('RECORD_CUSTOM_ORDER_SPOILS')||!spoilState.lines.length);spoilImpact();renderSpoilHistory()}catch(e){note(e.message,true)}}
function spoilImpact(){const line=spoilState?.lines.find(x=>String(x.lineId)===$('#spoilLine').value);const stock=Number(line?.stock||0);$('#spoilImpact').textContent=(line?.notes?line.notes+' / ':'')+(line?.productType==='INVENTORY'?`One replacement will be deducted. Stock: ${stock}. After spoil: ${stock-1}.${stock<=0?' Warning: replacement stock will be negative.':''}`:'No inventory deduction for this line.');for(const id of ['spoilReason','spoilLine','spoilCamera','spoilPhotos'])$('#'+id).disabled=!!spoilPending||spoilBusy;$('#spoilSubmit').disabled=spoilBusy||(!spoilPending&&!line?.eligible);$('#spoilSubmit').textContent=spoilPending?'Retry / confirm previous spoil':'Record spoil'}
$('#spoilLine').onchange=spoilImpact;
async function addSpoilPhotos(e){if(spoilBusy||spoilPending)return;try{const selected=[...e.target.files];if(spoilPhotos.length+selected.length>3)throw new Error('Choose at most three photos.');for(const file of selected){const bytes=await jpegBytes(file);if(bytes.length>2*1024*1024)throw new Error('Photo is too large.');spoilPhotos.push({bytes:base64(bytes),url:URL.createObjectURL(new Blob([bytes],{type:'image/jpeg'}))})}renderSpoilPhotos()}catch(error){note(error.message,true)}finally{e.target.value=''}}
$('#spoilCamera').onchange=addSpoilPhotos;$('#spoilPhotos').onchange=addSpoilPhotos;
function renderSpoilPhotos(){const root=$('#spoilPreviews');root.replaceChildren();if(spoilPending){root.textContent=`${spoilPending.photos.length} photo(s) kept for the pending submission.`;return}spoilPhotos.forEach((photo,index)=>{const box=document.createElement('div'),img=document.createElement('img'),remove=document.createElement('button');img.src=photo.url;img.alt=`Spoil photo ${index+1}`;img.style.maxWidth='180px';remove.type='button';remove.textContent='Remove photo';remove.disabled=spoilBusy;remove.onclick=()=>{URL.revokeObjectURL(photo.url);spoilPhotos.splice(index,1);renderSpoilPhotos()};box.append(img,remove);root.append(box)})}
$('#spoilForm').onsubmit=async e=>{e.preventDefault();if(spoilBusy)return;try{if(!spoilPending){if(!spoilPhotos.length)throw new Error('Take or choose a spoil photo.');const reason=$('#spoilReason').value.trim();if(!reason)throw new Error('Enter the spoil reason.');if(!confirm('Record this spoil? Inventory items consume one replacement.'))return;const pending={reportId:crypto.randomUUID(),orderId:spoilSelected,lineId:Number($('#spoilLine').value),reason,photos:spoilPhotos.map(x=>x.bytes)};sessionStorage.setItem('smartstockPendingSpoil',JSON.stringify(pending));spoilPending=pending}spoilBusy=true;spoilImpact();const saved=await call('/spoils/submit',spoilPending,true,spoilPending.reportId);spoilPending=null;sessionStorage.removeItem('smartstockPendingSpoil');await loadSpoilOrder(spoilSelected);note(saved.shortage?'Spoil recorded. Replacement stock is below zero.':'Spoil recorded with its photo and reason.')}catch(error){if(error.status>=400&&error.status<500&&![408,429].includes(error.status)&&spoilPending){spoilPhotos=spoilPending.photos.map(bytes=>({bytes,url:'data:image/jpeg;base64,'+bytes}));spoilPending=null;sessionStorage.removeItem('smartstockPendingSpoil')}note(`${error.message}${spoilPending?' Retry confirms the same report without a second deduction.':''}`,true)}finally{spoilBusy=false;spoilImpact();renderSpoilPhotos()}};
function renderSpoilHistory(){const root=$('#spoilHistory');root.replaceChildren();const heading=document.createElement('h2');heading.textContent='Internal spoil history';root.append(heading);for(const report of spoilState.reports){const box=document.createElement('article'),text=document.createElement('p');text.textContent=`Line ${report.lineId} / ${report.employee} / ${report.createdAt} / ${report.reason} / ${report.stockDeducted?'Replacement deducted':'No stock deduction'}${report.reversedAt?' / Reversed by '+report.reversedBy+': '+report.reversalReason:''}`;box.append(text);for(const photo of report.photos){const b=document.createElement('button');b.type='button';b.textContent='View spoil photo';b.onclick=async()=>{try{const data=await call('/spoils/photo',{photoId:photo.id}),img=document.createElement('img');img.alt='Internal spoil evidence';img.style.maxWidth='100%';img.src=`data:${data.contentType};base64,${data.bytesBase64}`;b.replaceWith(img)}catch(error){note(error.message,true)}};box.append(b)}if(!report.reversedAt&&can('REVERSE_CUSTOM_ORDER_SPOILS')){const reverse=document.createElement('button');reverse.type='button';reverse.className='danger';reverse.textContent='Reverse spoil';reverse.onclick=async()=>{const reason=prompt('Reason for reversing this spoil (deducted stock will be restored):');if(!reason?.trim())return;reverse.disabled=true;try{await call('/spoils/reverse',{reportId:report.id,reason},true,crypto.randomUUID());await loadSpoilOrder(spoilSelected);note('Spoil reversed. Original evidence preserved.')}catch(error){note(error.message,true);reverse.disabled=false}};box.append(reverse)}root.append(box)}if(!spoilState.reports.length)root.append(document.createTextNode('No spoils recorded.'))}
