'use strict';
const $=id=>document.getElementById(id);
const statusNames={DRAFT:'Draft',PENDING:'Submitted',UNDER_REVIEW:'Under review',INTERVIEW:'Interview',INFORMATION_REQUESTED:'Information requested',APPROVING:'Hiring in progress',APPROVED:'Hired',REJECTED:'Not selected',WITHDRAWN:'Withdrawn'};
const fieldNames={firstName:'First name',middleName:'Middle name',lastName:'Last name',phone:'Phone',dateOfBirth:'Date of birth',address:'Address',town:'Town / region',interests:'Areas of interest',introduction:'About you',education:'Education',examResults:'Exam results',skills:'Skills',experience:'Work / volunteering',reference1:'Reference 1',reference2:'Reference 2'};
let csrf='',application=null,step=0,mode='login',saveTimer,saveChain=Promise.resolve(),dirty=false,uploading=0,conflict=false;
const pendingUploads=new Map();
function message(text){$('message').textContent=text||'';}
function show(id){for(const panel of ['welcome','account','dashboard','editor'])$(panel).hidden=panel!==id;branding();}
async function api(route,body={}){let response;try{response=await fetch('/register/api/'+route,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Registration-Request':'same-origin','X-CSRF-Token':csrf},body:JSON.stringify(body)});}catch(e){throw new Error('Connection lost. Your latest changes may not be saved. Keep this page open and retry.');}const data=await response.json();if(!response.ok)throw new Error(data.message||'The request could not be completed. Please retry.');return data;}
async function branding(){try{const r=await fetch('/register/branding',{cache:'no-store'});if(!r.ok)return;const b=await r.json();$('company').textContent=b.name||'Careers';$('footer-company').textContent=b.name||'Employment application portal';$('motto').textContent=b.motto||'Your next chapter starts here.';document.title=(b.name||'Careers')+' · Applications';$('contact').textContent=[b.address,b.phone,b.email].filter(Boolean).join(' · ');$('logo').hidden=!b.logo;$('company').hidden=!!b.logo;$('logo').alt=(b.name||'Company')+' logo';if(b.logo)$('logo').src=b.logo;}catch(e){/* Keep the last public branding while reconnecting. */}}
function authMode(next){mode=next;show('account');message('');$('auth-title').textContent={login:'Welcome back',signup:'Create your account',verify:'Verify your email',recover:'Recover your account',reset:'Choose a new password'}[mode];$('auth-submit').textContent={login:'Sign in',signup:'Create account',verify:'Verify and continue',recover:'Send recovery code',reset:'Reset password'}[mode];$('auth-help').textContent=mode==='signup'?'Save your application, track its progress, and keep this account if you join our team.':mode==='verify'||mode==='reset'?'Enter the code from your email. Keep this page open while you check your inbox.':'Continue your application or check its progress.';const pw=['login','signup','reset'].includes(mode),code=['verify','reset'].includes(mode);$('password-label').hidden=!pw;$('auth-password').required=pw;$('auth-password').autocomplete=mode==='login'?'current-password':'new-password';$('code-label').hidden=!code;$('auth-code').required=code;$('resend-code').hidden=!code;$('forgot').hidden=mode!=='login';$('verify-link').hidden=!['login','signup'].includes(mode);}
$('resend-code').onclick=async()=>{if(!$('auth-email').reportValidity())return;const button=$('resend-code');button.disabled=true;message('');try{const result=await api('auth/'+(mode==='reset'?'recover':'resend'),{email:$('auth-email').value});message(result.message);}catch(e){message(e.message);}finally{setTimeout(()=>{button.disabled=false;},30000);}};
$('start').onclick=()=>authMode('signup');$('signin').onclick=()=>authMode('login');$('forgot').onclick=()=>authMode('recover');$('verify-link').onclick=()=>authMode('verify');$('account-back').onclick=()=>{message('');show('welcome');};
$('auth-form').onsubmit=async event=>{event.preventDefault();$('auth-submit').disabled=true;message('');try{const result=await api('auth/'+mode,{email:$('auth-email').value,password:$('auth-password').value,code:$('auth-code').value});$('auth-password').value='';$('auth-code').value='';if(mode==='signup'||mode==='recover'){authMode(mode==='signup'?'verify':'reset');message(result.message);return;}csrf=result.csrfToken;$('logout').hidden=false;await load();}catch(e){message(e.message);}finally{$('auth-submit').disabled=false;}};
$('logout').onclick=async()=>{if(dirty&&!confirm('Your latest changes are not saved. Sign out anyway?'))return;try{clearTimeout(saveTimer);await saveChain;await api('auth/logout');csrf='';application=null;dirty=false;pendingUploads.clear();$('application').reset();$('logout').hidden=true;show('welcome');message('You have signed out.');}catch(e){message(e.message);}};
function editable(){return application&&['DRAFT','INFORMATION_REQUESTED'].includes(application.status);}
async function load(){application=await api('application');dirty=false;conflict=false;renderDashboard();}
function renderDashboard(){show('dashboard');$('greeting').textContent=application.form.firstName?'Hello, '+application.form.firstName:'Your next step';$('status').textContent=statusNames[application.status]||application.status;$('reference').textContent='Application reference: '+application.id;$('saved-at').textContent='Last saved: '+new Date(application.updatedAt).toLocaleString();$('status-help').textContent=({DRAFT:'Your application is saved as a draft. Submit it when you’re ready.',PENDING:'Your application has been received. You can check its progress here.',INFORMATION_REQUESTED:'Please review the message below, update your application, and submit it again.',APPROVED:'Welcome to the team. Use this same account for SmartStock; your manager will confirm your assigned access.',REJECTED:'Your application was not selected. Thank you for your interest.',WITHDRAWN:'You have withdrawn this application.'})[application.status]||'Your application is with the hiring team. Check below for updates.';$('continue').hidden=!editable();$('continue').textContent=application.status==='INFORMATION_REQUESTED'?'Update application':'Continue application';$('withdraw').hidden=['APPROVING','APPROVED','REJECTED','WITHDRAWN'].includes(application.status);$('history').replaceChildren();for(const item of application.history){const li=document.createElement('li'),title=document.createElement('strong'),date=document.createElement('small'),p=document.createElement('p');title.textContent=statusNames[item.status]||item.status;date.textContent=new Date(item.at).toLocaleString();p.textContent=item.message;li.append(title,date,p);$('history').append(li);}if(!application.history.length){const li=document.createElement('li');li.textContent='No submission yet. Your draft is private until you submit.';$('history').append(li);}$('submitted-review').hidden=editable();if(!editable()){reviewFields($('submitted-fields'),application.form);renderFiles($('submitted-files'),false);}}
$('refresh').onclick=()=>load().catch(e=>message(e.message));
$('continue').onclick=()=>{message('');show('editor');for(const [key,label] of Object.entries(fieldNames)){const input=$('application').elements.namedItem(key);if(input)input.value=application.form[key]||'';}$('application-email').value=application.email;$('application').elements.declaration.checked=!!application.form.declaration;renderFiles($('attachments'),true);goStep(0);};
function formData(){const out={};for(const key of Object.keys(fieldNames))out[key]=$('application').elements.namedItem(key).value;out.declaration=$('application').elements.declaration.checked;return out;}
function reviewFields(target,form){target.replaceChildren();for(const [key,label] of Object.entries(fieldNames)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=form[key]||'Not provided';target.append(dt,dd);}const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent='Email';dd.textContent=application.email;target.append(dt,dd);}
function goStep(next){step=Math.max(0,Math.min(2,next));document.querySelectorAll('[data-page]').forEach(el=>el.hidden=Number(el.dataset.page)!==step);document.querySelectorAll('[data-step]').forEach(el=>{if(Number(el.dataset.step)===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});$('back').hidden=step===0;$('next').hidden=step===2;$('submit').hidden=step!==2;if(step===2)reviewFields($('review'),formData());branding();}
document.querySelectorAll('[data-step]').forEach(button=>button.onclick=()=>goStep(Number(button.dataset.step)));
$('back').onclick=()=>goStep(step-1);$('next').onclick=()=>{const invalid=[...document.querySelectorAll('[data-page="'+step+'"] [required]')].find(el=>!el.checkValidity());if(invalid){invalid.reportValidity();return;}goStep(step+1);};
function scheduleSave(){dirty=true;$('save-status').textContent='Unsaved changes';clearTimeout(saveTimer);if(!conflict)saveTimer=setTimeout(()=>save().catch(e=>message(e.message)),1200);}
$('application').addEventListener('input',event=>{if(event.target.name)scheduleSave();});
function save(submit=false){clearTimeout(saveTimer);const snapshot=formData();const work=async()=>{if(conflict)throw new Error('Reload the application before saving; another window changed it.');$('save-status').textContent=submit?'Submitting…':'Saving…';try{const result=await api(submit?'submit':'save',{revision:application.revision,form:snapshot});application=result;dirty=JSON.stringify(formData())!==JSON.stringify(snapshot);$('save-status').textContent=dirty?'Unsaved changes':'All changes saved';if(submit){dirty=false;message('Your application has been submitted.');renderDashboard();}return result;}catch(e){dirty=true;if(e.message.includes('another window'))conflict=true;$('save-status').textContent='Not saved — please retry';throw e;}};const result=saveChain.then(work,work);saveChain=result.catch(()=>{});return result;}
$('save-exit').onclick=async()=>{if(uploading||pendingUploads.size){message('Finish or remove pending uploads before leaving.');return;}try{await save();renderDashboard();message('Your application has been saved.');}catch(e){message(e.message);}};
$('application').onsubmit=async event=>{event.preventDefault();if(uploading||pendingUploads.size){message('Finish or remove pending uploads before submitting.');return;}for(const input of $('application').querySelectorAll('[required]'))if(!input.checkValidity()){goStep(Number(input.closest('[data-page]').dataset.page));input.reportValidity();return;}if(!confirm('Submit your application for review? You can view it afterward, and a manager can request corrections.'))return;$('submit').disabled=true;try{await save(true);}catch(e){message(e.message);}finally{$('submit').disabled=false;}};
$('withdraw').onclick=async()=>{if(!confirm('Withdraw this application from consideration?'))return;try{await api('withdraw');await load();message('Your application has been withdrawn.');}catch(e){message(e.message);}};
function renderFiles(target,canRemove){target.replaceChildren();const files=application.attachments||[];if(target.id==='attachments')$('file-count').textContent=files.length+' / 10 files · '+(files.reduce((n,f)=>n+f.size,0)/1024/1024).toFixed(1)+' / 50 MB';for(const file of files){const card=document.createElement('div');card.className='file-card';const url='/register/attachments/'+encodeURIComponent(file.id);if(file.contentType.startsWith('image/')){const img=document.createElement('img');img.src=url;img.alt=file.description||file.filename;img.loading='lazy';card.append(img);}const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=file.filename;const small=document.createElement('small');small.textContent=(file.size/1024/1024).toFixed(1)+' MB'+(file.contentType==='application/pdf'?' · '+file.pages+' page(s)':'');card.append(a,small);if(canRemove){const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='Remove';button.onclick=async()=>{button.disabled=true;try{await api('remove',{id:file.id});const latest=await api('application');application.attachments=latest.attachments;renderFiles(target,true);}catch(e){message(e.message);button.disabled=false;}};card.append(button);}target.append(card);}}
function base64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read this file.'));reader.readAsDataURL(file);});}
function uploadRequest(body,progress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/register/api/upload');xhr.setRequestHeader('Content-Type','application/json');xhr.setRequestHeader('X-Registration-Request','same-origin');xhr.setRequestHeader('X-CSRF-Token',csrf);xhr.upload.onprogress=event=>{if(event.lengthComputable)progress.value=event.loaded/event.total*100;};xhr.onload=()=>{let result;try{result=JSON.parse(xhr.responseText);}catch(e){reject(new Error('Upload could not be completed. Retry this file.'));return;}if(xhr.status>=200&&xhr.status<300)resolve(result);else reject(new Error(result.message||'Upload failed.'));};xhr.onerror=()=>reject(new Error('Connection lost. Retry this file.'));xhr.timeout=120000;xhr.ontimeout=()=>reject(new Error('Upload timed out. Retry this file.'));xhr.send(JSON.stringify(body));});}
$('files').onchange=async()=>{const chosen=[...$('files').files];$('files').value='';for(const file of chosen){if(application.attachments.length+pendingUploads.size>=10){message('You can include up to 10 attachments.');break;}if(file.size>10*1024*1024||!['image/jpeg','image/png','application/pdf'].includes(file.type)){message(file.name+': choose a JPEG, PNG, or PDF of 10 MB or smaller.');continue;}const id=crypto.randomUUID(),row=document.createElement('div'),title=document.createElement('span'),progress=document.createElement('progress'),retry=document.createElement('button'),remove=document.createElement('button');row.className='queue-item';title.textContent=file.name;progress.max=100;progress.value=0;retry.type=remove.type='button';retry.textContent='Retry';remove.textContent='Remove';retry.hidden=remove.hidden=true;row.append(title,progress,retry,remove);$('upload-queue').append(row);const item={file,category:'other',description:''};pendingUploads.set(id,item);const run=async()=>{uploading++;retry.hidden=remove.hidden=true;title.textContent=file.name+' — uploading';try{const encoded=await base64(file);await uploadRequest({id,filename:file.name,category:item.category,description:item.description,base64:encoded},progress);pendingUploads.delete(id);row.remove();const latest=await api('application');application.attachments=latest.attachments;renderFiles($('attachments'),true);}catch(e){title.textContent=file.name+' — '+e.message;retry.hidden=remove.hidden=false;}finally{uploading--;}};retry.onclick=run;remove.onclick=()=>{pendingUploads.delete(id);row.remove();};await run();}};
window.addEventListener('beforeunload',event=>{if(dirty||uploading||pendingUploads.size){event.preventDefault();event.returnValue='';}});
setInterval(branding,45000);branding();
api('auth/session').then(async session=>{csrf=session.csrfToken;$('logout').hidden=false;await load();}).catch(()=>{});
