const params=new URLSearchParams(location.search),storeId=Number(params.get('storeId')),token=new URLSearchParams(location.hash.slice(1)).get('token');
const proofMode=location.pathname.endsWith('custom-order-proof');const content=document.getElementById('content'),status=document.getElementById('status'),title=document.getElementById('title');
function say(message,error=false){status.textContent=message;status.className=error?'error':'success'}
async function call(action,extra={}){const response=await fetch('/shop/api/v1/custom-order-private',{method:'POST',headers:{'Content-Type':'application/json','X-Storefront-Request':'same-origin'},body:JSON.stringify({storeId,token,action,...extra})});let data;try{data=await response.json()}catch{throw Error('The store did not respond. Please try again.')}if(!response.ok)throw Error(data.message||'This request could not be completed.');return data}
async function retry(action,body){try{return await call(action,body)}catch(first){await new Promise(resolve=>setTimeout(resolve,400));return call(action,body)}}
function el(name,text,cls){const e=document.createElement(name);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e}
function bytesFromBase64(value){const raw=atob(value),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
async function download(id,proof,size,name,mime,preview=false){const chunks=[];for(let offset=0;offset<size;){const r=await call(proof?'PROOF_CHUNK':'FILE_CHUNK',{fileId:id,offset});const chunk=bytesFromBase64(r.bytesBase64);chunks.push(chunk);offset+=chunk.length;say(`Loading ${name}: ${Math.floor(offset*100/size)}%`)}const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob);if(preview){const target=document.getElementById('preview');target.replaceChildren();const view=el(mime==='application/pdf'?'iframe':'img');view.src=url;if(view.tagName==='IMG')view.alt='Design preview';target.append(view)}else{const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}say('Ready.')}
async function upload(file,lineId,progress){const uploadId=crypto.randomUUID();const sha256='0'.repeat(64);const started=await retry('BEGIN',{uploadId,lineId,filename:file.name,size:file.size,sha256});for(let offset=0;offset<file.size;){const chunk=new Uint8Array(await file.slice(offset,offset+768*1024).arrayBuffer());let binary='';for(let i=0;i<chunk.length;i+=32768)binary+=String.fromCharCode(...chunk.subarray(i,i+32768));const result=await retry('CHUNK',{uploadId:started.uploadId,offset,bytesBase64:btoa(binary)});offset=result.receivedBytes;progress.value=offset;progress.max=file.size;say(`Uploading ${file.name}: ${Math.floor(offset*100/file.size)}%`)}await retry('FINISH',{uploadId:started.uploadId})}
async function showFiles(){const data=await call('LIST');title.textContent=`Custom order ${data.orderNumber}`;content.replaceChildren();const readonly=data.status==='DELIVERED';for(const line of data.lines){const card=el('section',null,'card'),heading=el('h2',`${line.name}${line.variant?' / '+line.variant:''}`),list=el('ul');card.append(heading,list);for(const file of data.files.filter(f=>String(f.lineId)===String(line.lineId))){const item=el('li'),button=el('button',file.filename,'secondary');button.onclick=()=>download(file.id,false,file.bytes,file.filename,file.contentType).catch(e=>say(e.message,true));item.append(button,el('small',` ${Math.ceil(file.bytes/1024)} KB`));list.append(item)}if(!readonly){const picker=el('input');picker.type='file';picker.multiple=true;picker.accept='.jpg,.jpeg,.png,.webp,.gif,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx';const button=el('button','Upload selected files'),progress=el('progress');progress.value=0;button.onclick=async()=>{button.disabled=true;try{for(const file of picker.files)await upload(file,line.lineId,progress);say('Files uploaded.');await showFiles()}catch(e){say(e.message,true)}finally{button.disabled=false}};card.append(picker,button,progress)}content.append(card)}if(readonly)say('This order has been delivered. Files are read only until their retention date.');else say('Choose an order line to add files. You can select several at once.');content.hidden=false}
async function showProof(){const proof=await call('PROOF_DETAILS');title.textContent=`Design approval · revision ${proof.revision}`;content.replaceChildren();const card=el('section',null,'card');card.append(el('h2',proof.filename));const preview=el('div');preview.id='preview';card.append(preview);const open=el('button','View preview','secondary');open.onclick=()=>download(proof.proofId,true,proof.bytes,proof.filename,proof.contentType,true).catch(e=>say(e.message,true));card.append(open);if(proof.status==='AWAITING_APPROVAL'){const reason=el('textarea'),changes=el('textarea');reason.placeholder='Why are you rejecting this preview?';reason.setAttribute('aria-label','Reason for rejecting');changes.placeholder='What should the store change?';changes.setAttribute('aria-label','Requested changes');const approve=el('button','Approve'),reject=el('button','Reject and request changes','danger');approve.onclick=()=>decide('APPROVE','','');reject.onclick=()=>{if(!reason.value.trim()||!changes.value.trim()){say('Enter both a reason and the changes you need.',true);return}decide('REJECT',reason.value.trim(),changes.value.trim())};card.append(reason,changes,approve,reject)}else card.append(el('p',proof.status==='APPROVED'?'You approved this design.':proof.status==='CHANGES_REQUESTED'?'You requested changes.':'This preview has been superseded.'));content.append(card);content.hidden=false;say('Review the exact preview before deciding.')}
async function decide(decision,reason,changes){try{const result=await call('PROOF_DECIDE',{decision,reason,changes});say(result.status==='APPROVED'?'Design approved.':'Changes sent to the store.');await showProof()}catch(e){say(e.message,true)}}
if(!Number.isInteger(storeId)||storeId<=0||!token){say('This private link is incomplete.',true)}else(proofMode?showProof():showFiles()).catch(e=>say(e.message,true));
