import React from 'react';
import {ArrowRight,ArrowUpRight,Image as ImageIcon} from 'lucide-react';
import {services,type Service} from './services.mjs';
import type {Project} from './Made';

type Props={onService:(name:string)=>void;onProject:(id:string)=>void;onMade:()=>void;onShop:()=>void;onQuote:()=>void;onStores:()=>void;storeId:number;projects:Project[]};
function ServiceCards({items,onService}:{items:Service[];onService:(name:string)=>void}){
  return <div className="discovery-service-grid">{items.map(service=><a key={service.slug} href={`/shop/services/${service.slug}`} onClick={e=>{e.preventDefault();onService(service.name);}}><span>{service.name}</span><h3>{service.headline}</h3><p>{service.examples}</p><small>Explore service <ArrowUpRight size={16}/></small></a>)}</div>;
}
function ProjectStrip({projects,storeId,onProject}:{projects:Project[];storeId:number;onProject:(id:string)=>void}){
  if(!projects.length)return null;
  return <section className="discovery-projects"><p className="home-overline">Made at Deckers</p><h2>See what we’ve made.</h2><div>{projects.slice(0,3).map(project=><button key={project.id} onClick={()=>onProject(project.id)}>{project.cover?<img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${project.id}`} alt={project.title}/>:<ImageIcon size={38}/>}<span>{project.title}<ArrowUpRight size={16}/></span></button>)}</div></section>;
}
export function ServicesPage({onService,onProject,onQuote,storeId,projects,available=services}:Props&{available?:Service[]}){
  return <div className="discovery-page"><section className="discovery-hero services"><p className="home-overline">Explore what’s possible</p><h1>What can we<br/><em>make for you?</em></h1><p>Find a starting point, then tell us what you have in mind. Our team will review your idea and help with the next steps.</p><button className="campaign-primary" onClick={onQuote}>Start a custom project <ArrowRight size={18}/></button></section><section className="discovery-services"><p className="home-overline">Services at your store</p><h2>Start with an idea.</h2><ServiceCards items={available} onService={onService}/>{!available.length&&<p>Choose another Deckers store to explore available services.</p>}</section><ProjectStrip projects={projects} storeId={storeId} onProject={onProject}/></div>;
}
export function BusinessPage({onService,onProject,onQuote,onShop,storeId,projects,available=services}:Props&{available?:Service[]}){
  const business=available.filter(service=>['business-cards','business-printing','stationery','signs','signs-banners','banner-printing','custom-apparel','embroidery','large-format-printing'].includes(service.slug));
  const work=projects.filter(project=>/business|corporate|uniform|brand|sign|banner|stationery/i.test([project.category,project.productionMethod,...project.tags].join(' ')));
  return <div className="discovery-page"><section className="discovery-hero business"><p className="home-overline">For your business</p><h1>Make your brand<br/><em>feel like yours.</em></h1><p>From the first business card to the sign outside, bring us the details you want customers to remember.</p><div className="discovery-actions"><button className="campaign-primary" onClick={onQuote}>Plan a business project <ArrowRight size={18}/></button><button className="campaign-secondary" onClick={onShop}>Shop products <ArrowUpRight size={18}/></button></div></section><section className="discovery-services"><p className="home-overline">Ways to get started</p><h2>Every detail adds up.</h2><ServiceCards items={business} onService={onService}/></section><ProjectStrip projects={work} storeId={storeId} onProject={onProject}/></div>;
}
export function AboutPage({onService,onMade,onStores,onQuote,available=services}:Props&{available?:Service[]}){
  return <div className="discovery-page"><section className="discovery-hero about"><p className="home-overline">About Deckers</p><h1>See it. Imagine it.<br/><em>Make it.</em></h1><p>Deckers brings products, printing, personalization, and custom production together. Explore what our team has made and start with an idea of your own.</p><div className="discovery-actions"><button className="campaign-primary" onClick={onMade}>See our work <ArrowRight size={18}/></button><button className="campaign-secondary" onClick={onQuote}>Start a project <ArrowUpRight size={18}/></button></div></section><section className="discovery-story"><p className="home-overline">One place for the next idea</p><h2>Discover. Create. Collect.</h2><div><article><span>01</span><h3>Find a starting point.</h3><p>Browse our products, services, and projects for inspiration.</p></article><article><span>02</span><h3>Make it yours.</h3><p>Share your artwork, preferences, or the change you would make to a project.</p></article><article><span>03</span><h3>Work with your store.</h3><p>Your selected Deckers store reviews the request and follows up with the next steps.</p></article></div>{available.some(service=>service.slug==='3d-printing')&&<button className="home-inline" onClick={()=>onService('3D Printing')}>Explore 3D Printing <ArrowUpRight size={18}/></button>}<button className="home-inline" onClick={onStores}>Find your store <ArrowUpRight size={18}/></button></section></div>;
}
