import React from 'react';
import {ArrowRight, ArrowUpRight, Box, Layers3, Shirt, Sparkles, Printer, Gift, Store} from 'lucide-react';
import type {Project} from './Made';
import {latest3DPrints,capabilityProject,projectForServices} from './projectDiscovery.mjs';
import {serviceForTopic} from './services.mjs';
import {campaignAction,type CampaignAction} from './campaignActions.mjs';

export type Campaign = {eyebrow:string;headline:string;description:string;steps:string;primary:string;secondary:string;topic:string;primaryAction?:CampaignAction;secondaryAction?:CampaignAction;visual?:'3D_PRINT'|'EDITORIAL';mediaUrl?:string;mediaAlt?:string};
export const featuredCampaign:Campaign={eyebrow:'Now at Deckers · 3D Printing',headline:'Your Ideas. Made Real.',description:'Custom 3D printing is now available at Deckers.',steps:'Upload your design · Choose your material · We print it',primary:'Start a 3D Print',secondary:'Explore 3D Printing',topic:'3D Printing',primaryAction:'START',secondaryAction:'EXPLORE',visual:'3D_PRINT'};
const openCampaign:Campaign={eyebrow:'Make something at Deckers',headline:'See it. Imagine it. Make it.',description:'Explore what your store can make, personalize, and prepare for you.',steps:'Find inspiration · Share your idea · Make it yours',primary:'Start a custom project',secondary:'Shop what’s ready',topic:'Custom Project',primaryAction:'START',secondaryAction:'SHOP',visual:'EDITORIAL'};
const capabilities=[
  {name:'3D Printing',description:'Objects and ideas made layer by layer.',icon:Box,tone:'violet'},
  {name:'Custom Apparel',description:'Make a statement you can wear.',icon:Shirt,tone:'peach'},
  {name:'Signs & Banners',description:'Get seen at every scale.',icon:Layers3,tone:'lime'},
  {name:'Business Printing',description:'The details that carry your brand.',icon:Printer,tone:'cream'},
  {name:'Personalized Gifts',description:'A little more meaningful.',icon:Gift,tone:'pink'},
  {name:'Something Else',description:'Tell us what you have in mind.',icon:Sparkles,tone:'slate'}
];
type Props={onShop:()=>void;onExplore:(name:string)=>void;onStart:(name:string)=>void;onMade:()=>void;onStores:()=>void;onProject:(id:string)=>void;onCreate:(project:Project)=>void;storeId:number;projects:Project[];products:React.ReactNode;hasProducts:boolean;browseOnly?:boolean;campaign?:Campaign;availableServiceNames?:string[]};
export function Home({onShop,onExplore,onStart,onMade,onStores,onProject,onCreate,storeId,projects,products,hasProducts,browseOnly=false,campaign=featuredCampaign,availableServiceNames}:Props){
  const available=(name:string)=>!serviceForTopic(name)||!availableServiceNames||availableServiceNames.includes(name);
  if(!available(campaign.topic))campaign=openCampaign;
  if(campaign.topic==='3D Printing'&&campaign.visual==='3D_PRINT'&&campaign.primary==='Explore 3D Printing'&&['Shop what is ready','Shop what’s ready'].includes(campaign.secondary))campaign={...campaign,steps:featuredCampaign.steps,primary:featuredCampaign.primary,secondary:featuredCampaign.secondary};
  const prints=latest3DPrints(projects);
  const featuredProject=projects.find(project=>project.featured&&project.cover)||projects.find(project=>project.cover);
  const businessTopics=['Business Cards','Business Printing','Signs & Banners','Custom Apparel'];
  const businessProject=projectForServices(projects,['business-cards','business-printing','stationery','signs-banners','signs','custom-apparel','embroidery']);
  const runCampaignAction=(action:CampaignAction)=>{if(action==='START')browseOnly?onStores():onStart(campaign.topic);else if(action==='EXPLORE')onExplore(campaign.topic);else if(action==='MADE')onMade();else onShop();};
  const heroMedia=campaign.mediaUrl||(campaign.visual==='3D_PRINT'?'/shop/hero-3d.jpg':'');
  const heroDescription=browseOnly&&campaign.topic==='3D Printing'?'Discover what Deckers can create with 3D printing. Ask your store about current availability.':campaign.description;
  const heroSteps=browseOnly&&campaign.topic==='3D Printing'?'Bring your idea · Discuss the details · Plan the print':campaign.steps;
  return <div className="creative-home">
    <section className="campaign-hero" aria-labelledby="campaign-title"><div className="campaign-copy"><p className="campaign-kicker">{browseOnly&&campaign.topic==='3D Printing'?'Explore at Deckers · 3D Printing':campaign.eyebrow}</p><h1 id="campaign-title" tabIndex={-1}>{campaign.headline}</h1><p>{heroDescription}</p><div className="campaign-actions"><button className="campaign-primary" onClick={()=>runCampaignAction(campaignAction(campaign,'primary'))}>{browseOnly&&campaignAction(campaign,'primary')==='START'?'Find your store':campaign.primary}<ArrowUpRight size={18}/></button><button className="campaign-secondary" onClick={()=>runCampaignAction(campaignAction(campaign,'secondary'))}>{campaign.secondary}<ArrowRight size={18}/></button></div><small>{heroSteps}</small></div>{heroMedia?<div className="campaign-media"><img src={heroMedia} alt={campaign.mediaAlt||'Concept image of a 3D printer making an orange sculptural object'} fetchPriority="high"/></div>:campaign.visual==='EDITORIAL'?<div className="campaign-editorial" aria-hidden="true"><span>SEE IT.</span><span>IMAGINE IT.</span><span>MAKE IT.</span></div>:<div className="print-scene" role="img" aria-label="Illustration of a custom object being built layer by layer"><div className="scene-halo"/><div className="printer-rail"/><div className="printer-head"/><div className="print-object"><i/><i/><i/><i/><i/><i/></div><div className="printer-platform"/><span className="scene-index">01 / CREATE</span></div>}</section>
    {(available('3D Printing')||available('Custom Apparel'))&&<section className="home-editorial" aria-labelledby="new-heading"><div className="home-section-top"><p className="home-overline">Discover what’s possible</p><h2 id="new-heading">New at Deckers<span className="period">.</span></h2></div><div className="new-grid">{available('3D Printing')&&<button className="new-card new-card-primary" onClick={()=>onExplore('3D Printing')}><img className="new-card-photo" src="/shop/new-3d.jpg" alt="" loading="lazy"/><span>01 / NEW CAPABILITY</span><strong>Built layer<br/>by layer.</strong><small>Explore 3D Printing <ArrowUpRight size={17}/></small></button>}{available('Custom Apparel')&&<button className="new-card new-card-secondary" onClick={()=>onExplore('Custom Apparel')}><img className="new-card-photo" src="/shop/new-apparel.jpg" alt="" loading="lazy"/><span>02 / MAKE IT YOURS</span><strong>Wear your<br/>idea.</strong><small>Explore Custom Apparel <ArrowUpRight size={17}/></small></button>}</div></section>}
    <section className="capability-section" aria-labelledby="capabilities-heading"><div className="home-section-top"><p className="home-overline">A world of possibilities</p><h2 id="capabilities-heading">What can we<br/><em>make for you?</em></h2><p>Start with an idea. We’ll help you find the way to make it.</p></div><div className="capability-grid">{capabilities.filter(item=>available(item.name)).map(({name,description,icon:Icon,tone})=>{const example=capabilityProject(projects,serviceForTopic(name)?.slug);return <button className={'capability-card '+tone+(example?' has-photo':'')} key={name} onClick={()=>onExplore(name)}>{example&&<img className="capability-photo" loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${example.id}`} alt=""/>}<Icon size={43} strokeWidth={1.25}/><span><strong>{name}</strong><small>{description}</small></span><ArrowUpRight className="capability-arrow" size={19}/></button>;})}</div></section>
    <section className="made-section" aria-labelledby="made-heading"><div className="made-heading"><p className="home-overline">See it. Imagine it. Make it.</p><h2 id="made-heading">Made at<br/><em>Deckers.</em></h2><p>{projects.length?`Explore ${projects.length} project${projects.length===1?'':'s'} made by our team. Find an idea to make your own.`:'Real projects can spark your next one. We’re preparing a collection of work made by our team.'}</p><button className="campaign-primary" onClick={onMade}>Explore our work <ArrowUpRight size={18}/></button></div>{featuredProject?<article className="made-featured"><img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${featuredProject.id}`} alt={featuredProject.title}/><div className="made-featured-copy"><span>{featuredProject.category||'Made at Deckers'}</span><h3>{featuredProject.title}</h3><div><button onClick={()=>onProject(featuredProject.id)}>View project <ArrowUpRight size={17}/></button><button onClick={()=>onCreate(featuredProject)}>{browseOnly?'Explore this project':'Make something like this'} <ArrowRight size={17}/></button></div></div></article>:<div className="made-art" aria-hidden="true"><div className="made-disc made-disc-one"/><div className="made-disc made-disc-two"/><span>THE NEXT IDEA<br/>COULD BE YOURS.</span></div>}</section>
    {prints.length>0&&<section className="latest-prints" aria-labelledby="latest-prints-heading"><div className="home-section-top"><p className="home-overline">Fresh from our team</p><h2 id="latest-prints-heading">Latest 3D Prints<span className="period">.</span></h2><button className="home-inline" onClick={onMade}>See all projects <ArrowRight size={18}/></button></div><div className="discovery-grid">{prints.map(project=><article className="discovery-card" key={project.id}><button className="discovery-image" onClick={()=>onProject(project.id)} aria-label={`View ${project.title}`}><img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${project.id}`} alt={project.title}/></button><div><span>{project.productionMethod||project.category}</span><h3>{project.title}</h3><p>{project.summary}</p><button onClick={()=>onProject(project.id)}>View Project <ArrowUpRight size={16}/></button><button onClick={()=>onCreate(project)}>{browseOnly?'Explore this project':'Make Something Like This'} <ArrowRight size={16}/></button></div></article>)}</div>{available('3D Printing')&&<button className="home-inline" onClick={()=>onExplore('3D Printing')}>{browseOnly?'Explore 3D Printing':'Upload your model'} <ArrowUpRight size={18}/></button>}</section>}
    <section className="home-products" aria-labelledby="products-heading"><div className="home-section-top"><p className="home-overline">Available at your store</p><h2 id="products-heading">Explore the shop<span className="period">.</span></h2><button className="home-inline" onClick={onShop}>Shop all products <ArrowRight size={18}/></button></div>{hasProducts?products:<div className="home-empty"><Store size={32}/><p>This store is preparing its online collection.</p><button onClick={onStores}>Find your store <ArrowRight size={16}/></button></div>}</section>
    <section className="purpose-section" aria-labelledby="purpose-heading"><div><p className="home-overline">Made for your moment</p><h2 id="purpose-heading">Whatever you’re<br/>working on.</h2></div><div className="purpose-links">{['For your business','For your event','For your team','For a gift'].map(x=><button key={x} onClick={()=>onExplore(x)}>{x}<ArrowUpRight size={21}/></button>)}</div></section>
    <section className="business-feature" aria-labelledby="business-feature-heading"><div className="business-feature-copy"><p className="home-overline">For your business</p><h2 id="business-feature-heading">Make every detail<br/><em>feel like yours.</em></h2><p>From the first business card to the sign outside, bring us the details you want customers to remember.</p><div className="business-feature-links">{businessTopics.filter(available).map(topic=><button key={topic} onClick={()=>onExplore(topic)}>{topic}<ArrowUpRight size={15}/></button>)}</div><button className="campaign-primary" onClick={()=>onExplore('For your business')}>Explore business solutions <ArrowRight size={18}/></button></div>{businessProject?<button className="business-feature-project" onClick={()=>onProject(businessProject.id)} aria-label={`View ${businessProject.title} at Made at Deckers`}><img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${businessProject.id}`} alt=""/><span>Made at Deckers <strong>{businessProject.title}</strong><small>View project <ArrowUpRight size={16}/></small></span></button>:<div className="business-feature-art" aria-hidden="true"><span>DECKERS<br/>FOR BUSINESS</span><i/><b>Ideas with<br/>impact.</b></div>}</section>
    <section className="custom-cta"><p className="home-overline">Anything is a starting point</p><h2>Have something<br/><em>different in mind?</em></h2><p>Tell us what you’re trying to make. We’d love to hear your idea.</p><button className="campaign-primary" onClick={()=>onStart('Something Else')}>{browseOnly?'Explore custom projects':'Start a custom project'} <ArrowUpRight size={18}/></button></section>
  </div>;
}
