import React from 'react';
import {ArrowLeft,ArrowRight,MapPin,Plus,Share2} from 'lucide-react';
import type {Project} from './Made';
import {projectsForProduct} from './projectDiscovery.mjs';
import {ProductImage} from './ProductImage';
import {publishedVariants,variantLabel} from './productVariants.mjs';

export type Product={id:number;sku?:string;name:string;size:string;color:string;description:string;price:number;regularPrice?:number|null;image:string;category:string;availability:string;canOrder:boolean;featured:boolean;groupId?:string|null;groupName?:string;optionNames?:string[];variantOptions?:Record<string,string>};
type Props={product:Product;products:Product[];projects:Project[];storeId:number;storeName:string;money:(value:number)=>string;onBack:()=>void;onProduct:(product:Product)=>void;onProject:(id:string)=>void;onAdd:(product:Product)=>void;browseOnly?:boolean};
export function ProductPage({product,products,projects,storeId,storeName,money,onBack,onProduct,onProject,onAdd,browseOnly=false}:Props){
  const related=products.filter(item=>item.id!==product.id&&item.category===product.category&&(!product.groupId||item.groupId!==product.groupId)).slice(0,3);
  const variants=publishedVariants(product,products);
  const inspiration=projectsForProduct(product,projects);
  return <article className="standalone-product"><button className="home-inline" onClick={onBack}><ArrowLeft size={17}/> Shop products</button><div className="standalone-product-main"><div className="standalone-product-image"><ProductImage product={product} storeId={storeId} large/></div><div className="standalone-product-copy"><p className="home-overline">{product.category}</p><h1>{product.name}</h1>{(product.size||product.color)&&<p>{[product.size,product.color].filter(Boolean).join(' · ')}</p>}<div className="standalone-price">{product.regularPrice&&<del>{money(product.regularPrice)}</del>}<strong>{money(product.price)}</strong></div><p>{product.description||'Ask your store for more details about this product.'}</p>{variants.length>1&&<div className="product-variants"><p>Choose an option{product.groupName&&<> for {product.groupName}</>}</p><div>{variants.map(item=><button key={item.id} aria-pressed={item.id===product.id} onClick={()=>onProduct(item)}>{variantLabel(item)}<small>{item.availability}</small></button>)}</div></div>}<p className="product-availability">{product.availability} at {storeName}</p>{browseOnly?<p className="product-pickup"><MapPin size={16}/> Online ordering is coming soon. Contact {storeName} to purchase.</p>:<><button className="campaign-primary" disabled={!product.canOrder} onClick={()=>onAdd(product)}>{product.canOrder?'Add to bag':'Currently unavailable'}<Plus size={18}/></button><p className="product-pickup"><MapPin size={16}/> Pay and collect in store.</p></>}<button className="home-inline" onClick={()=>{if(navigator.share)void navigator.share({title:product.name,url:location.href});else void navigator.clipboard?.writeText(location.href);}}><Share2 size={17}/> Share this product</button></div></div>{related.length>0&&<section className="standalone-product-related"><p className="home-overline">Keep exploring</p><h2>Related products.</h2><div>{related.map(item=><button key={item.id} onClick={()=>onProduct(item)}><span>{item.name}<small>{money(item.price)} · {item.availability}</small></span><ArrowRight size={17}/></button>)}</div></section>}{inspiration.length>0&&<section className="standalone-product-related"><p className="home-overline">Made at Deckers</p><h2>See what we’ve made.</h2><div>{inspiration.map(project=><button key={project.id} onClick={()=>onProject(project.id)}><span>{project.title}<small>{project.category}</small></span><ArrowRight size={17}/></button>)}</div></section>}</article>;
}
