import React from 'react';
import {ArrowDown,ArrowUpRight,Image as ImageIcon} from 'lucide-react';
import type {Project} from './Made';
import type {Service} from './services.mjs';

export function ServiceIntro({service,projects,storeId,onProject,browseOnly=false}:{service:Service;projects:Project[];storeId:number;onProject:(id:string)=>void;browseOnly?:boolean}){
  const related=projects.filter(project=>[project.category,project.productionMethod,...(project.tags||[])].join(' ').toLowerCase().includes(service.name.toLowerCase())).slice(0,3);
  return <div className="service-intro"><section className="service-hero" aria-labelledby="service-title"><div><p className="home-overline">Made possible at Deckers</p><h1 id="service-title" tabIndex={-1}>{service.headline}</h1><p>{service.description}</p><button className="campaign-primary" onClick={()=>document.getElementById('service-request')?.scrollIntoView({behavior:'smooth'})}>{browseOnly?'Contact your store':'Start a project'} <ArrowDown size={18}/></button></div><div className="service-hero-art" aria-hidden="true"><span>{service.name}</span><strong>{service.examples}</strong></div></section><section className="service-process"><p className="home-overline">Start with your idea</p><h2>Tell us what you have in mind.</h2><p>{browseOnly?'Online requests are coming soon. Visit or contact your Deckers store to discuss size, quantity, colors, timing, and artwork.':'Share the size, quantity, colors, timing, and artwork you have. We’ll review the details and follow up with the next steps and a quote.'}</p></section>{related.length>0&&<section className="service-inspiration"><p className="home-overline">Made at Deckers</p><h2>See what we’ve made.</h2><div>{related.map(project=><button key={project.id} onClick={()=>onProject(project.id)}>{project.cover?<img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${project.id}`} alt=""/>:<ImageIcon size={42}/>}<span>{project.title}<ArrowUpRight size={16}/></span></button>)}</div></section>}<div className="service-request-heading" id="service-request"><p className="home-overline">Ready to begin?</p><h2>{browseOnly?'Discuss your idea with us.':'Request a review.'}</h2></div></div>;
}
