import React from 'react';
import {ArrowDown,ArrowUpRight,Box,FileUp,ScanSearch,Layers3} from 'lucide-react';
import type {Project} from './Made';
import {latest3DPrints} from './projectDiscovery.mjs';

export function ThreeDPrintingIntro({projects,storeId,onProject,browseOnly=false}:{projects:Project[];storeId:number;onProject:(id:string)=>void;browseOnly?:boolean}){
  const prints=latest3DPrints(projects);
  return <div className="three-d-intro">
    <section className="three-d-hero" aria-labelledby="three-d-title"><div className="three-d-copy"><p className="home-overline">New at Deckers · 3D Printing</p><h1 id="three-d-title" tabIndex={-1}>Your idea,<br/><em>made real.</em></h1><p>From a model on your screen to an object you can hold. Share what you want to make and our team will help you work through the details.</p><button className="campaign-primary" onClick={()=>document.getElementById('start-3d-print')?.scrollIntoView({behavior:'smooth'})}>{browseOnly?'Contact your store':'Start a 3D Print'} <ArrowDown size={18}/></button><small>{browseOnly?'Explore the possibilities · Discuss your idea with our team':'Upload your design · Choose your material · We review it together'}</small></div><div className="three-d-visual" role="img" aria-label="Illustration of a layered object taking shape"><div className="three-d-ring"/><div className="three-d-stack">{Array.from({length:8},(_,i)=><i key={i} style={{'--layer':i} as React.CSSProperties}/>)}</div><span>FROM IDEA<br/>TO OBJECT</span></div></section>
    <section className="three-d-process" aria-labelledby="three-d-process-heading"><p className="home-overline">How it works</p><h2 id="three-d-process-heading">Make room for what’s possible.</h2><div>{[{icon:FileUp,title:'Share your idea',body:browseOnly?'Bring a model or describe what you need when you contact your store.':'Upload an STL, OBJ, or 3MF model, or describe what you need.'},{icon:ScanSearch,title:'Review the details',body:'Tell us the size, color, material, quantity, and finish you have in mind.'},{icon:Layers3,title:'We make it real',body:'Our team checks the model, confirms printability and price, then follows up before production.'}].map(({icon:Icon,title,body},i)=><article key={title}><Icon size={31} strokeWidth={1.5}/><span>0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    {prints.length>0&&<section className="three-d-work" aria-labelledby="three-d-work-heading"><div><p className="home-overline">Made at Deckers</p><h2 id="three-d-work-heading">See what’s taking shape.</h2></div><div className="three-d-work-grid">{prints.map(project=><button key={project.id} onClick={()=>onProject(project.id)}><img loading="lazy" src={`/shop/image?storeId=${storeId}&kind=project&projectId=${project.id}`} alt={project.title}/><span>{project.title}<ArrowUpRight size={17}/></span></button>)}</div></section>}
    <section className="three-d-start" id="start-3d-print"><Box size={26}/><div><p className="home-overline">{browseOnly?'Contact your store':'Start here'}</p><h2>Tell us what you’re making.</h2><p>{browseOnly?'Online model uploads are coming soon. Contact your Deckers store to discuss your design, size, material, and timing.':'Use the private form below. A preview helps you check STL, OBJ, and supported 3MF assemblies. Files needing extra model parts or extensions go to the team for review. We confirm scale, printability, and pricing.'}</p></div></section>
  </div>;
}
