-- Immutable, completed recovery generations for the local-first store mirror.
--
-- smartstock_store_rows remains the current synchronization/read cache. Recovery
-- reads are pinned to a completed generation so an interrupted materialization
-- can never expose a mixture of the previous and next backup.

CREATE TABLE IF NOT EXISTS public.smartstock_store_snapshot_generations (
    generation_id uuid PRIMARY KEY,
    location_id integer NOT NULL,
    status text NOT NULL DEFAULT 'BUILDING'
        CHECK (status IN ('BUILDING', 'COMPLETE')),
    table_counts jsonb NOT NULL DEFAULT '{}'::jsonb
        CHECK (pg_catalog.jsonb_typeof(table_counts) = 'object'),
    active_row_count bigint NOT NULL DEFAULT 0 CHECK (active_row_count >= 0),
    based_on_generation_id uuid
        REFERENCES public.smartstock_store_snapshot_generations(generation_id),
    started_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    completed_at timestamptz,
    CHECK ((status = 'BUILDING' AND completed_at IS NULL)
        OR (status = 'COMPLETE' AND completed_at IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS smartstock_store_snapshot_one_building_idx
    ON public.smartstock_store_snapshot_generations(location_id)
    WHERE status = 'BUILDING';
CREATE INDEX IF NOT EXISTS smartstock_store_snapshot_completed_idx
    ON public.smartstock_store_snapshot_generations(location_id, completed_at DESC)
    WHERE status = 'COMPLETE';

CREATE TABLE IF NOT EXISTS public.smartstock_store_snapshot_rows (
    generation_id uuid NOT NULL
        REFERENCES public.smartstock_store_snapshot_generations(generation_id)
        ON DELETE CASCADE,
    location_id integer NOT NULL,
    table_name text NOT NULL CHECK (table_name ~ '^[a-z][a-z0-9_]{0,100}$'),
    row_key jsonb NOT NULL,
    row_data jsonb NOT NULL,
    row_hash text NOT NULL CHECK (pg_catalog.length(row_hash) BETWEEN 16 AND 128),
    source_updated_at timestamptz,
    row_sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (generation_id, table_name, row_key)
);

CREATE INDEX IF NOT EXISTS smartstock_store_snapshot_rows_page_idx
    ON public.smartstock_store_snapshot_rows(generation_id, table_name, row_sequence);

ALTER TABLE public.smartstock_store_mirror_status
    ADD COLUMN IF NOT EXISTS current_generation_id uuid
        REFERENCES public.smartstock_store_snapshot_generations(generation_id);

ALTER TABLE public.smartstock_store_snapshot_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smartstock_store_snapshot_rows ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.smartstock_store_snapshot_generations
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.smartstock_store_snapshot_rows
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.smartstock_store_snapshot_rows_row_sequence_seq
    FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.smartstock_store_snapshot_generations TO service_role;
GRANT ALL ON TABLE public.smartstock_store_snapshot_rows TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.smartstock_store_snapshot_rows_row_sequence_seq
    TO service_role;

-- Adopt only a provably complete pre-generation mirror. A mismatched legacy
-- mirror is deliberately left without a recovery generation; the next server
-- sync will then upload every row and establish the first verified generation.
DO $$
DECLARE
    v_status record;
    v_generation uuid;
    v_actual_counts jsonb;
BEGIN
    FOR v_status IN
        SELECT location_id, table_counts, active_row_count, completed_at
        FROM public.smartstock_store_mirror_status
        WHERE current_generation_id IS NULL
    LOOP
        v_generation := gen_random_uuid();
        INSERT INTO public.smartstock_store_snapshot_generations(
            generation_id, location_id, status, table_counts, active_row_count,
            started_at, completed_at
        ) VALUES (
            v_generation, v_status.location_id, 'COMPLETE', v_status.table_counts,
            v_status.active_row_count, v_status.completed_at, v_status.completed_at
        );

        INSERT INTO public.smartstock_store_snapshot_rows(
            generation_id, location_id, table_name, row_key, row_data, row_hash,
            source_updated_at
        )
        SELECT v_generation, location_id, table_name, row_key, row_data, row_hash,
               source_updated_at
        FROM public.smartstock_store_rows
        WHERE location_id = v_status.location_id AND NOT is_deleted;

        SELECT COALESCE(pg_catalog.jsonb_object_agg(
                   expected.key,
                   (SELECT pg_catalog.count(*)
                    FROM public.smartstock_store_snapshot_rows rows
                    WHERE rows.generation_id = v_generation
                      AND rows.table_name = expected.key)
               ), '{}'::jsonb)
        INTO v_actual_counts
        FROM pg_catalog.jsonb_each_text(v_status.table_counts) expected;

        IF v_actual_counts = v_status.table_counts
           AND (SELECT pg_catalog.count(*)
                FROM public.smartstock_store_snapshot_rows
                WHERE generation_id = v_generation) = v_status.active_row_count THEN
            UPDATE public.smartstock_store_mirror_status
            SET current_generation_id = v_generation
            WHERE location_id = v_status.location_id;
        ELSE
            DELETE FROM public.smartstock_store_snapshot_generations
            WHERE generation_id = v_generation;
        END IF;
    END LOOP;
END
$$;

CREATE OR REPLACE FUNCTION public.smartstock_begin_store_mirror(
    p_location_id integer,
    p_generation_id uuid,
    p_clone_current boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_base uuid;
    v_existing record;
BEGIN
    IF p_location_id IS NULL OR p_location_id <= 0 OR p_generation_id IS NULL THEN
        RAISE EXCEPTION 'A valid location and generation are required.';
    END IF;

    SELECT generation_id, location_id, status INTO v_existing
    FROM public.smartstock_store_snapshot_generations
    WHERE generation_id = p_generation_id;
    IF FOUND THEN
        IF v_existing.location_id <> p_location_id OR v_existing.status <> 'BUILDING' THEN
            RAISE EXCEPTION 'The mirror generation is not writable for this location.';
        END IF;
        RETURN pg_catalog.jsonb_build_object(
            'generation_id', p_generation_id, 'started', false);
    END IF;

    -- Store sync is serialized locally. Any different BUILDING generation is an
    -- abandoned attempt whose local hashes were never committed.
    DELETE FROM public.smartstock_store_snapshot_generations
    WHERE location_id = p_location_id AND status = 'BUILDING'
      AND generation_id <> p_generation_id;

    IF COALESCE(p_clone_current, true) THEN
        SELECT current_generation_id INTO v_base
        FROM public.smartstock_store_mirror_status
        WHERE location_id = p_location_id;
    ELSE
        v_base := NULL;
    END IF;

    INSERT INTO public.smartstock_store_snapshot_generations(
        generation_id, location_id, based_on_generation_id
    ) VALUES (p_generation_id, p_location_id, v_base);

    IF v_base IS NOT NULL THEN
        INSERT INTO public.smartstock_store_snapshot_rows(
            generation_id, location_id, table_name, row_key, row_data, row_hash,
            source_updated_at
        )
        SELECT p_generation_id, location_id, table_name, row_key, row_data, row_hash,
               source_updated_at
        FROM public.smartstock_store_snapshot_rows
        WHERE generation_id = v_base;
    END IF;

    RETURN pg_catalog.jsonb_build_object(
        'generation_id', p_generation_id,
        'based_on_generation_id', v_base,
        'started', true
    );
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_begin_store_mirror(integer, uuid, boolean)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_begin_store_mirror(integer, uuid, boolean)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_materialize_store_rows(
    p_location_id integer,
    p_generation_id uuid,
    p_rows jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_row jsonb;
    v_count integer := 0;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.smartstock_store_snapshot_generations
        WHERE generation_id = p_generation_id
          AND location_id = p_location_id AND status = 'BUILDING'
    ) THEN
        RAISE EXCEPTION 'The mirror generation is not writable for this location.';
    END IF;

    IF pg_catalog.jsonb_typeof(COALESCE(p_rows, '[]'::jsonb)) <> 'array' THEN
        RAISE EXCEPTION 'p_rows must be a JSON array.';
    END IF;
    IF pg_catalog.jsonb_array_length(COALESCE(p_rows, '[]'::jsonb)) > 250 THEN
        RAISE EXCEPTION 'A materialization request cannot contain more than 250 rows.';
    END IF;

    FOR v_row IN
        SELECT value
        FROM pg_catalog.jsonb_array_elements(COALESCE(p_rows, '[]'::jsonb))
    LOOP
        IF COALESCE(v_row->>'table_name', '') !~ '^[a-z][a-z0-9_]{0,100}$'
           OR pg_catalog.jsonb_typeof(v_row->'row_key') <> 'object'
           OR pg_catalog.jsonb_typeof(v_row->'row_data') <> 'object'
           OR pg_catalog.length(COALESCE(v_row->>'row_hash', '')) NOT BETWEEN 16 AND 128 THEN
            RAISE EXCEPTION 'Invalid materialized store row.';
        END IF;
        IF v_row->>'table_name' LIKE 'sync\_%'
           OR v_row->>'table_name' LIKE 'lan\_%'
           OR v_row->>'table_name' IN (
               'security_audit_events', 'local_auth_cache', 'device_credentials'
           ) THEN
            RAISE EXCEPTION 'Table is not allowed in the cloud store mirror.';
        END IF;

        INSERT INTO public.smartstock_store_rows(
            location_id, table_name, row_key, row_data, row_hash, is_deleted,
            source_updated_at
        ) VALUES (
            p_location_id, v_row->>'table_name', v_row->'row_key',
            v_row->'row_data', v_row->>'row_hash',
            COALESCE((v_row->>'is_deleted')::boolean, false),
            CASE WHEN COALESCE(v_row->>'source_updated_at', '') = ''
                THEN NULL ELSE (v_row->>'source_updated_at')::timestamptz END
        )
        ON CONFLICT (location_id, table_name, row_key) DO UPDATE
        SET row_data = EXCLUDED.row_data,
            row_hash = EXCLUDED.row_hash,
            is_deleted = EXCLUDED.is_deleted,
            source_updated_at = EXCLUDED.source_updated_at,
            version_sequence = nextval('public.smartstock_store_row_version_seq'::regclass),
            materialized_at = pg_catalog.now()
        WHERE public.smartstock_store_rows.row_hash IS DISTINCT FROM EXCLUDED.row_hash
           OR public.smartstock_store_rows.is_deleted IS DISTINCT FROM EXCLUDED.is_deleted;

        IF COALESCE((v_row->>'is_deleted')::boolean, false) THEN
            DELETE FROM public.smartstock_store_snapshot_rows
            WHERE generation_id = p_generation_id
              AND table_name = v_row->>'table_name'
              AND row_key = v_row->'row_key';
        ELSE
            INSERT INTO public.smartstock_store_snapshot_rows(
                generation_id, location_id, table_name, row_key, row_data,
                row_hash, source_updated_at
            ) VALUES (
                p_generation_id, p_location_id, v_row->>'table_name',
                v_row->'row_key', v_row->'row_data', v_row->>'row_hash',
                CASE WHEN COALESCE(v_row->>'source_updated_at', '') = ''
                    THEN NULL ELSE (v_row->>'source_updated_at')::timestamptz END
            )
            ON CONFLICT (generation_id, table_name, row_key) DO UPDATE
            SET row_data = EXCLUDED.row_data,
                row_hash = EXCLUDED.row_hash,
                source_updated_at = EXCLUDED.source_updated_at;
        END IF;
        v_count := v_count + 1;
    END LOOP;

    RETURN pg_catalog.jsonb_build_object(
        'acknowledged', v_count, 'generation_id', p_generation_id);
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_materialize_store_rows(integer, uuid, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_materialize_store_rows(integer, uuid, jsonb)
    TO service_role;

-- Rolling-deployment compatibility: pre-generation servers keep using the
-- two-argument RPC, but their batches are transparently written into one
-- BUILDING generation and published by the old finalize RPC below.
CREATE OR REPLACE FUNCTION public.smartstock_materialize_store_rows(
    p_location_id integer,
    p_rows jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_generation uuid;
BEGIN
    SELECT generation_id INTO v_generation
    FROM public.smartstock_store_snapshot_generations
    WHERE location_id = p_location_id AND status = 'BUILDING'
    ORDER BY started_at DESC LIMIT 1;
    IF v_generation IS NULL THEN
        v_generation := gen_random_uuid();
        PERFORM public.smartstock_begin_store_mirror(
            p_location_id, v_generation, true);
    END IF;
    RETURN public.smartstock_materialize_store_rows(
        p_location_id, v_generation, p_rows);
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_materialize_store_rows(integer, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_materialize_store_rows(integer, jsonb)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_finalize_store_mirror(
    p_location_id integer,
    p_generation_id uuid,
    p_table_counts jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_entry record;
    v_total bigint := 0;
    v_actual_counts jsonb;
    v_completed_at timestamptz := pg_catalog.now();
BEGIN
    IF p_location_id IS NULL OR p_location_id <= 0 OR p_generation_id IS NULL
       OR pg_catalog.jsonb_typeof(p_table_counts) <> 'object' THEN
        RAISE EXCEPTION 'A valid location, generation, and table-count object are required.';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM public.smartstock_store_snapshot_generations
        WHERE generation_id = p_generation_id
          AND location_id = p_location_id AND status = 'BUILDING'
    ) THEN
        RAISE EXCEPTION 'The mirror generation is not writable for this location.';
    END IF;

    FOR v_entry IN SELECT key, value FROM pg_catalog.jsonb_each_text(p_table_counts)
    LOOP
        IF v_entry.key !~ '^[a-z][a-z0-9_]{0,100}$'
           OR v_entry.value !~ '^[0-9]+$' THEN
            RAISE EXCEPTION 'Invalid store mirror table count.';
        END IF;
        v_total := v_total + v_entry.value::bigint;
    END LOOP;

    DELETE FROM public.smartstock_store_snapshot_rows rows
    WHERE rows.generation_id = p_generation_id
      AND NOT (p_table_counts ? rows.table_name);

    SELECT COALESCE(pg_catalog.jsonb_object_agg(
               expected.key,
               (SELECT pg_catalog.count(*)
                FROM public.smartstock_store_snapshot_rows rows
                WHERE rows.generation_id = p_generation_id
                  AND rows.table_name = expected.key)
           ), '{}'::jsonb)
    INTO v_actual_counts
    FROM pg_catalog.jsonb_each_text(p_table_counts) expected;

    IF v_actual_counts <> p_table_counts
       OR (SELECT pg_catalog.count(*)
           FROM public.smartstock_store_snapshot_rows
           WHERE generation_id = p_generation_id) <> v_total THEN
        RAISE EXCEPTION 'Mirror generation row counts do not match the completed local snapshot.';
    END IF;

    UPDATE public.smartstock_store_snapshot_generations
    SET status = 'COMPLETE', table_counts = p_table_counts,
        active_row_count = v_total, completed_at = v_completed_at
    WHERE generation_id = p_generation_id;

    INSERT INTO public.smartstock_store_mirror_status(
        location_id, table_counts, active_row_count, completed_at,
        current_generation_id
    ) VALUES (
        p_location_id, p_table_counts, v_total, v_completed_at, p_generation_id
    )
    ON CONFLICT(location_id) DO UPDATE
    SET table_counts = EXCLUDED.table_counts,
        active_row_count = EXCLUDED.active_row_count,
        completed_at = EXCLUDED.completed_at,
        current_generation_id = EXCLUDED.current_generation_id;

    RETURN pg_catalog.jsonb_build_object(
        'completed', true,
        'generation_id', p_generation_id,
        'active_row_count', v_total,
        'completed_at', v_completed_at
    );
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_finalize_store_mirror(integer, uuid, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_finalize_store_mirror(integer, uuid, jsonb)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_finalize_store_mirror(
    p_location_id integer,
    p_table_counts jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_generation uuid;
BEGIN
    SELECT generation_id INTO v_generation
    FROM public.smartstock_store_snapshot_generations
    WHERE location_id = p_location_id AND status = 'BUILDING'
    ORDER BY started_at DESC LIMIT 1;
    IF v_generation IS NULL THEN
        v_generation := gen_random_uuid();
        PERFORM public.smartstock_begin_store_mirror(
            p_location_id, v_generation, true);
    END IF;
    RETURN public.smartstock_finalize_store_mirror(
        p_location_id, v_generation, p_table_counts);
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_finalize_store_mirror(integer, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_finalize_store_mirror(integer, jsonb)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_snapshot(
    p_location_id integer,
    p_after_sequence bigint DEFAULT 0,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    WITH current_generation AS (
        SELECT s.current_generation_id
        FROM public.smartstock_store_mirror_status s
        JOIN public.smartstock_store_snapshot_generations g
          ON g.generation_id = s.current_generation_id AND g.status = 'COMPLETE'
        WHERE s.location_id = p_location_id
    ), page AS (
        SELECT r.table_name, r.row_key, r.row_data, r.row_hash,
               r.source_updated_at, r.row_sequence
        FROM public.smartstock_store_snapshot_rows r
        JOIN current_generation g ON g.current_generation_id = r.generation_id
        WHERE r.row_sequence > GREATEST(COALESCE(p_after_sequence, 0::bigint), 0::bigint)
        ORDER BY r.row_sequence
        LIMIT LEAST(GREATEST(COALESCE(p_limit, 500), 1), 1000)
    )
    SELECT pg_catalog.jsonb_build_object(
        'generation_id', (SELECT current_generation_id FROM current_generation),
        'rows', COALESCE(pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
                'table_name', table_name,
                'row_key', row_key,
                'row_data', row_data,
                'row_hash', row_hash,
                'is_deleted', false,
                'sequence', row_sequence,
                'source_updated_at', source_updated_at
            ) ORDER BY row_sequence
        ), '[]'::jsonb),
        'next_cursor', COALESCE(pg_catalog.max(row_sequence), p_after_sequence, 0)
    )
    FROM page
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_snapshot(integer, bigint, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_snapshot(integer, bigint, integer)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_snapshot_manifest(p_location_id integer)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    SELECT pg_catalog.jsonb_build_object(
        'generation_id', s.current_generation_id,
        'completed_at', g.completed_at,
        'active_row_count', COALESCE(g.active_row_count, 0),
        'tables', COALESCE((
            SELECT pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'name', entry.key,
                    'row_count', entry.value::bigint
                ) ORDER BY entry.key
            )
            FROM pg_catalog.jsonb_each_text(g.table_counts) entry
        ), '[]'::jsonb)
    )
    FROM public.smartstock_store_mirror_status s
    JOIN public.smartstock_store_snapshot_generations g
      ON g.generation_id = s.current_generation_id
     AND g.status = 'COMPLETE'
    WHERE s.location_id = p_location_id
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_snapshot_manifest(integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_snapshot_manifest(integer)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_table_snapshot(
    p_location_id integer,
    p_table_name text,
    p_generation_id uuid,
    p_after_sequence bigint DEFAULT 0,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    WITH authorized_generation AS (
        SELECT generation_id
        FROM public.smartstock_store_snapshot_generations
        WHERE generation_id = p_generation_id
          AND location_id = p_location_id AND status = 'COMPLETE'
    ), page AS (
        SELECT r.row_key, r.row_data, r.row_hash, r.source_updated_at,
               r.row_sequence
        FROM public.smartstock_store_snapshot_rows r
        JOIN authorized_generation g USING (generation_id)
        WHERE r.table_name = p_table_name
          AND r.row_sequence > GREATEST(COALESCE(p_after_sequence, 0::bigint), 0::bigint)
        ORDER BY r.row_sequence
        LIMIT LEAST(GREATEST(COALESCE(p_limit, 500), 1), 1000)
    )
    SELECT pg_catalog.jsonb_build_object(
        'generation_id', p_generation_id,
        'rows', COALESCE(pg_catalog.jsonb_agg(
            pg_catalog.jsonb_build_object(
                'row_key', row_key,
                'row_data', row_data,
                'row_hash', row_hash,
                'is_deleted', false,
                'sequence', row_sequence,
                'source_updated_at', source_updated_at
            ) ORDER BY row_sequence
        ), '[]'::jsonb),
        'next_cursor', COALESCE(pg_catalog.max(row_sequence), p_after_sequence, 0)
    )
    FROM page
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_table_snapshot(integer, text, uuid, bigint, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_table_snapshot(integer, text, uuid, bigint, integer)
    TO service_role;

-- Compatibility wrapper for cross-store readers during rolling deployment. It
-- still reads only a completed generation, never the mutable transport table.
CREATE OR REPLACE FUNCTION public.smartstock_store_table_snapshot(
    p_location_id integer,
    p_table_name text,
    p_after_sequence bigint DEFAULT 0,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    SELECT public.smartstock_store_table_snapshot(
        p_location_id,
        p_table_name,
        (SELECT current_generation_id
         FROM public.smartstock_store_mirror_status
         WHERE location_id = p_location_id),
        p_after_sequence,
        p_limit
    )
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_table_snapshot(integer, text, bigint, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_table_snapshot(integer, text, bigint, integer)
    TO service_role;

NOTIFY pgrst, 'reload schema';
