-- SmartStock store-server sync transport.
--
-- Store servers call this RPC with a server-only Supabase secret key. Registers
-- never receive that key and continue to communicate with the paired store
-- server over the authenticated LAN API.

CREATE TABLE IF NOT EXISTS public.sync_outbox (
    event_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type text NOT NULL,
    location_id integer,
    device_id text,
    user_id integer,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    synced_at timestamptz,
    origin_event_id uuid,
    origin_location_id integer,
    origin_device_id text,
    origin_created_at timestamptz
);

CREATE INDEX IF NOT EXISTS sync_outbox_status_created_idx
    ON public.sync_outbox(status, created_at);

CREATE TABLE IF NOT EXISTS public.sync_applied_events (
    origin_event_id uuid PRIMARY KEY,
    event_type text NOT NULL,
    origin_location_id integer,
    origin_device_id text,
    applied_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    cloud_reference text
);

ALTER TABLE public.sync_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_applied_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sync_outbox, public.sync_applied_events
    FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.sync_outbox, public.sync_applied_events TO service_role;

ALTER TABLE public.sync_outbox
    ADD COLUMN IF NOT EXISTS cloud_sequence bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS sync_outbox_cloud_sequence_key
    ON public.sync_outbox (cloud_sequence);

CREATE INDEX IF NOT EXISTS sync_outbox_cloud_delta_idx
    ON public.sync_outbox (cloud_sequence, location_id);

CREATE SEQUENCE IF NOT EXISTS public.smartstock_store_row_version_seq;

CREATE TABLE IF NOT EXISTS public.smartstock_store_rows (
    location_id integer NOT NULL,
    table_name text NOT NULL,
    row_key jsonb NOT NULL,
    row_data jsonb NOT NULL,
    row_hash text NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    version_sequence bigint NOT NULL
        DEFAULT nextval('public.smartstock_store_row_version_seq'::regclass),
    source_updated_at timestamptz,
    materialized_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    PRIMARY KEY (location_id, table_name, row_key),
    CHECK (table_name ~ '^[a-z][a-z0-9_]{0,100}$'),
    CHECK (pg_catalog.length(row_hash) BETWEEN 16 AND 128)
);

CREATE UNIQUE INDEX IF NOT EXISTS smartstock_store_rows_version_key
    ON public.smartstock_store_rows(version_sequence);
CREATE INDEX IF NOT EXISTS smartstock_store_rows_location_version_idx
    ON public.smartstock_store_rows(location_id, version_sequence);

CREATE TABLE IF NOT EXISTS public.smartstock_store_mirror_status (
    location_id integer PRIMARY KEY,
    table_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    active_row_count bigint NOT NULL DEFAULT 0,
    completed_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    CHECK (pg_catalog.jsonb_typeof(table_counts) = 'object'),
    CHECK (active_row_count >= 0)
);

ALTER TABLE public.smartstock_store_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smartstock_store_mirror_status ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.smartstock_store_rows FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.smartstock_store_mirror_status FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.smartstock_store_row_version_seq
    FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.smartstock_store_rows TO service_role;
GRANT ALL ON TABLE public.smartstock_store_mirror_status TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.smartstock_store_row_version_seq TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_materialize_store_rows(
    p_location_id integer,
    p_rows jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_row jsonb;
    v_count integer := 0;
BEGIN
    IF p_location_id IS NULL OR p_location_id <= 0 THEN
        RAISE EXCEPTION 'A valid store location is required.';
    END IF;
    IF pg_catalog.jsonb_typeof(COALESCE(p_rows, '[]'::jsonb)) <> 'array' THEN
        RAISE EXCEPTION 'p_rows must be a JSON array.';
    END IF;
    IF pg_catalog.jsonb_array_length(COALESCE(p_rows, '[]'::jsonb)) > 250 THEN
        RAISE EXCEPTION 'A materialization request cannot contain more than 250 rows.';
    END IF;

    FOR v_row IN
        SELECT value FROM pg_catalog.jsonb_array_elements(COALESCE(p_rows, '[]'::jsonb))
    LOOP
        IF COALESCE(v_row->>'table_name', '') !~ '^[a-z][a-z0-9_]{0,100}$'
           OR pg_catalog.jsonb_typeof(v_row->'row_key') <> 'object'
           OR pg_catalog.jsonb_typeof(v_row->'row_data') <> 'object'
           OR pg_catalog.length(COALESCE(v_row->>'row_hash', '')) NOT BETWEEN 16 AND 128 THEN
            RAISE EXCEPTION 'Invalid materialized store row.';
        END IF;
        IF v_row->>'table_name' LIKE 'sync\_%'
           OR v_row->>'table_name' LIKE 'lan\_%'
           OR v_row->>'table_name' IN (
               'security_audit_events', 'local_auth_cache', 'device_credentials'
           ) THEN
            RAISE EXCEPTION 'Table is not allowed in the cloud store mirror.';
        END IF;

        INSERT INTO public.smartstock_store_rows(
            location_id, table_name, row_key, row_data, row_hash, is_deleted,
            source_updated_at
        )
        VALUES (
            p_location_id,
            v_row->>'table_name',
            v_row->'row_key',
            v_row->'row_data',
            v_row->>'row_hash',
            COALESCE((v_row->>'is_deleted')::boolean, false),
            CASE WHEN COALESCE(v_row->>'source_updated_at', '') = ''
                THEN NULL ELSE (v_row->>'source_updated_at')::timestamptz END
        )
        ON CONFLICT (location_id, table_name, row_key) DO UPDATE
        SET row_data = EXCLUDED.row_data,
            row_hash = EXCLUDED.row_hash,
            is_deleted = EXCLUDED.is_deleted,
            source_updated_at = EXCLUDED.source_updated_at,
            version_sequence = nextval('public.smartstock_store_row_version_seq'::regclass),
            materialized_at = pg_catalog.now()
        WHERE public.smartstock_store_rows.row_hash IS DISTINCT FROM EXCLUDED.row_hash
           OR public.smartstock_store_rows.is_deleted IS DISTINCT FROM EXCLUDED.is_deleted;
        v_count := v_count + 1;
    END LOOP;

    RETURN pg_catalog.jsonb_build_object('acknowledged', v_count);
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_materialize_store_rows(integer, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_materialize_store_rows(integer, jsonb)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_finalize_store_mirror(
    p_location_id integer,
    p_table_counts jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_entry record;
    v_total bigint := 0;
BEGIN
    IF p_location_id IS NULL OR p_location_id <= 0
       OR pg_catalog.jsonb_typeof(p_table_counts) <> 'object' THEN
        RAISE EXCEPTION 'A valid location and table-count object are required.';
    END IF;
    FOR v_entry IN SELECT key, value FROM pg_catalog.jsonb_each_text(p_table_counts)
    LOOP
        IF v_entry.key !~ '^[a-z][a-z0-9_]{0,100}$'
           OR v_entry.value !~ '^[0-9]+$' THEN
            RAISE EXCEPTION 'Invalid store mirror table count.';
        END IF;
        v_total := v_total + v_entry.value::bigint;
    END LOOP;

    INSERT INTO public.smartstock_store_mirror_status(
        location_id, table_counts, active_row_count, completed_at
    )
    VALUES (p_location_id, p_table_counts, v_total, pg_catalog.now())
    ON CONFLICT(location_id) DO UPDATE
    SET table_counts=EXCLUDED.table_counts,
        active_row_count=EXCLUDED.active_row_count,
        completed_at=EXCLUDED.completed_at
    WHERE public.smartstock_store_mirror_status.table_counts
              IS DISTINCT FROM EXCLUDED.table_counts
       OR public.smartstock_store_mirror_status.active_row_count
              IS DISTINCT FROM EXCLUDED.active_row_count;
    RETURN pg_catalog.jsonb_build_object(
        'completed', true, 'active_row_count', v_total
    );
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_finalize_store_mirror(integer, jsonb)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_finalize_store_mirror(integer, jsonb)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_snapshot(
    p_location_id integer,
    p_after_sequence bigint DEFAULT 0,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    WITH page AS (
        SELECT r.table_name, r.row_key, r.row_data, r.row_hash,
               r.is_deleted, r.version_sequence
        FROM public.smartstock_store_rows r
        WHERE r.location_id = p_location_id
          AND r.version_sequence > GREATEST(COALESCE(p_after_sequence, 0::bigint), 0::bigint)
        ORDER BY r.version_sequence
        LIMIT LEAST(GREATEST(COALESCE(p_limit, 500), 1), 1000)
    )
    SELECT pg_catalog.jsonb_build_object(
        'rows', COALESCE(
            pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'table_name', table_name,
                    'row_key', row_key,
                    'row_data', row_data,
                    'row_hash', row_hash,
                    'is_deleted', is_deleted,
                    'sequence', version_sequence
                )
                ORDER BY version_sequence
            ),
            '[]'::jsonb
        ),
        'next_cursor', COALESCE(pg_catalog.max(version_sequence), p_after_sequence, 0)
    )
    FROM page
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_snapshot(integer, bigint, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_snapshot(integer, bigint, integer)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_snapshot_manifest(p_location_id integer)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    SELECT pg_catalog.jsonb_build_object(
        'tables', COALESCE(
            pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'name', counts.table_name,
                    'row_count', counts.row_count
                )
                ORDER BY counts.table_name
            ),
            '[]'::jsonb
        )
    )
    FROM (
        SELECT entry.key AS table_name, entry.value::bigint AS row_count
        FROM public.smartstock_store_mirror_status s,
             LATERAL pg_catalog.jsonb_each_text(s.table_counts) entry
        WHERE s.location_id = p_location_id
    ) counts
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_snapshot_manifest(integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_snapshot_manifest(integer)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_store_table_snapshot(
    p_location_id integer,
    p_table_name text,
    p_after_sequence bigint DEFAULT 0,
    p_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
    WITH page AS (
        SELECT r.row_key, r.row_data, r.row_hash, r.is_deleted, r.version_sequence
        FROM public.smartstock_store_rows r
        WHERE r.location_id = p_location_id
          AND r.table_name = p_table_name
          AND r.version_sequence > GREATEST(COALESCE(p_after_sequence, 0::bigint), 0::bigint)
        ORDER BY r.version_sequence
        LIMIT LEAST(GREATEST(COALESCE(p_limit, 500), 1), 1000)
    )
    SELECT pg_catalog.jsonb_build_object(
        'rows', COALESCE(
            pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'row_key', row_key,
                    'row_data', row_data,
                    'row_hash', row_hash,
                    'is_deleted', is_deleted,
                    'sequence', version_sequence
                )
                ORDER BY version_sequence
            ),
            '[]'::jsonb
        ),
        'next_cursor', COALESCE(pg_catalog.max(version_sequence), p_after_sequence, 0)
    )
    FROM page
$$;

REVOKE ALL ON FUNCTION public.smartstock_store_table_snapshot(integer, text, bigint, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_store_table_snapshot(integer, text, bigint, integer)
    TO service_role;

CREATE OR REPLACE FUNCTION public.smartstock_sync_exchange(
    p_location_id integer,
    p_cursor bigint DEFAULT 0,
    p_events jsonb DEFAULT '[]'::jsonb,
    p_limit integer DEFAULT 100
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 100), 1), 500);
    v_cursor bigint := GREATEST(COALESCE(p_cursor, 0::bigint), 0::bigint);
    v_event jsonb;
    v_event_id uuid;
    v_acknowledged jsonb := '[]'::jsonb;
    v_changes jsonb := '[]'::jsonb;
    v_next_cursor bigint := v_cursor;
BEGIN
    IF p_location_id IS NULL OR p_location_id <= 0 THEN
        RAISE EXCEPTION 'A valid store location is required.';
    END IF;

    IF pg_catalog.jsonb_typeof(COALESCE(p_events, '[]'::jsonb)) <> 'array' THEN
        RAISE EXCEPTION 'p_events must be a JSON array.';
    END IF;

    IF pg_catalog.jsonb_array_length(COALESCE(p_events, '[]'::jsonb)) > 100 THEN
        RAISE EXCEPTION 'A sync request cannot contain more than 100 events.';
    END IF;

    FOR v_event IN
        SELECT value
        FROM pg_catalog.jsonb_array_elements(COALESCE(p_events, '[]'::jsonb))
    LOOP
        IF pg_catalog.jsonb_typeof(v_event) <> 'object'
           OR COALESCE(v_event->>'event_id', '') = ''
           OR COALESCE(v_event->>'event_type', '') = '' THEN
            RAISE EXCEPTION 'Each sync event requires event_id and event_type.';
        END IF;

        v_event_id := (v_event->>'event_id')::uuid;

        INSERT INTO public.sync_applied_events (
            origin_event_id, event_type, origin_location_id,
            origin_device_id, cloud_reference
        )
        VALUES (
            v_event_id,
            pg_catalog.left(v_event->>'event_type', 200),
            p_location_id,
            NULLIF(v_event->>'device_id', ''),
            'smartstock_sync_exchange'
        )
        ON CONFLICT (origin_event_id) DO NOTHING;

        INSERT INTO public.sync_outbox (
            event_id, event_type, location_id, device_id, user_id, payload,
            status, attempts, created_at, synced_at,
            origin_event_id, origin_location_id, origin_device_id, origin_created_at
        )
        VALUES (
            v_event_id,
            pg_catalog.left(v_event->>'event_type', 200),
            p_location_id,
            NULLIF(v_event->>'device_id', ''),
            CASE WHEN COALESCE(v_event->>'user_id', '') ~ '^[0-9]+$'
                THEN (v_event->>'user_id')::integer ELSE NULL END,
            COALESCE(v_event->'payload', '{}'::jsonb),
            'RECEIVED_FROM_STORE',
            0,
            pg_catalog.now(),
            pg_catalog.now(),
            v_event_id,
            p_location_id,
            NULLIF(v_event->>'device_id', ''),
            CASE WHEN COALESCE(v_event->>'created_at', '') = ''
                THEN pg_catalog.now() ELSE (v_event->>'created_at')::timestamptz END
        )
        ON CONFLICT (event_id) DO NOTHING;

        v_acknowledged := v_acknowledged || pg_catalog.jsonb_build_array(v_event_id::text);
    END LOOP;

    WITH delta AS (
        SELECT o.cloud_sequence, o.event_id, o.event_type, o.location_id,
               o.device_id, o.user_id, o.payload, o.origin_location_id,
               o.origin_device_id, o.origin_created_at
        FROM public.sync_outbox o
        WHERE o.cloud_sequence > v_cursor
          AND o.origin_location_id IS DISTINCT FROM p_location_id
          AND (
              o.location_id IS NULL
              OR o.event_type IN (
                  'PRODUCT_CREATED', 'PRODUCT_UPDATED',
                  'ROLE_CREATED', 'ROLE_PERMISSIONS_UPDATED',
                  'TIME_CLOCK_AUTO_CLOSE_SETTINGS_UPDATED',
                  'DEVICE_ACCESS_UPDATED'
              )
              OR (
                  o.event_type = 'STORE_TRANSFER_CREATED'
                  AND COALESCE(o.payload->>'destination_location_id', '') ~ '^[0-9]+$'
                  AND (o.payload->>'destination_location_id')::integer = p_location_id
              )
          )
        ORDER BY o.cloud_sequence
        LIMIT v_limit
    )
    SELECT
        COALESCE(
            pg_catalog.jsonb_agg(
                pg_catalog.jsonb_build_object(
                    'sequence', cloud_sequence,
                    'event_id', event_id,
                    'event_type', event_type,
                    'location_id', location_id,
                    'device_id', device_id,
                    'user_id', user_id,
                    'payload', payload,
                    'origin_location_id', origin_location_id,
                    'origin_device_id', origin_device_id,
                    'created_at', origin_created_at
                )
                ORDER BY cloud_sequence
            ),
            '[]'::jsonb
        ),
        COALESCE(pg_catalog.max(cloud_sequence), v_cursor)
    INTO v_changes, v_next_cursor
    FROM delta;

    INSERT INTO public.store_sync_status (
        location_id, status, message, last_success_at, last_seen_at, updated_at
    )
    VALUES (
        p_location_id, 'Online', 'Store synchronized through the HTTPS API',
        pg_catalog.now(), pg_catalog.now(), pg_catalog.now()
    )
    ON CONFLICT (location_id) DO UPDATE
    SET status = EXCLUDED.status,
        message = EXCLUDED.message,
        last_success_at = EXCLUDED.last_success_at,
        last_seen_at = EXCLUDED.last_seen_at,
        updated_at = EXCLUDED.updated_at;

    RETURN pg_catalog.jsonb_build_object(
        'acknowledged_event_ids', v_acknowledged,
        'changes', v_changes,
        'next_cursor', v_next_cursor,
        'has_more', pg_catalog.jsonb_array_length(v_changes) = v_limit
    );
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_sync_exchange(integer, bigint, jsonb, integer)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_sync_exchange(integer, bigint, jsonb, integer)
    TO service_role;

COMMENT ON FUNCTION public.smartstock_sync_exchange(integer, bigint, jsonb, integer)
    IS 'Server-only batched SmartStock event upload and cursor-based delta download.';

CREATE OR REPLACE FUNCTION public.smartstock_sync_manifest()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_table record;
    v_count bigint;
    v_tables jsonb := '[]'::jsonb;
BEGIN
    FOR v_table IN
        SELECT c.relname AS table_name
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind IN ('r', 'p')
        ORDER BY c.relname
    LOOP
        EXECUTE pg_catalog.format('SELECT count(*) FROM public.%I', v_table.table_name)
            INTO v_count;
        v_tables := v_tables || pg_catalog.jsonb_build_array(
            pg_catalog.jsonb_build_object(
                'name', v_table.table_name,
                'row_count', v_count,
                'columns', (
                    SELECT COALESCE(
                        pg_catalog.jsonb_agg(a.attname ORDER BY a.attnum),
                        '[]'::jsonb
                    )
                    FROM pg_catalog.pg_attribute a
                    JOIN pg_catalog.pg_class tc ON tc.oid = a.attrelid
                    JOIN pg_catalog.pg_namespace tn ON tn.oid = tc.relnamespace
                    WHERE tn.nspname = 'public'
                      AND tc.relname = v_table.table_name
                      AND a.attnum > 0
                      AND NOT a.attisdropped
                )
            )
        );
    END LOOP;

    RETURN pg_catalog.jsonb_build_object(
        'tables', v_tables,
        'generated_at', pg_catalog.now()
    );
END
$$;

REVOKE ALL ON FUNCTION public.smartstock_sync_manifest()
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.smartstock_sync_manifest()
    TO service_role;

COMMENT ON FUNCTION public.smartstock_sync_manifest()
    IS 'Server-only schema and recovery row-count manifest for SmartStock.';

NOTIFY pgrst, 'reload schema';
