INSERT INTO public.mobile_permissions(permission_key,permission_name,description,permission_group,permission_subgroup,created_at)
VALUES ('ACCESS_SCHEDULER_WEB','Access Scheduler Web','Allows signing in to the owner-only scheduler web app.','People','Scheduling',CURRENT_TIMESTAMP)
ON CONFLICT (permission_key) DO UPDATE SET permission_name=EXCLUDED.permission_name,
 description=EXCLUDED.description,permission_group=EXCLUDED.permission_group,permission_subgroup=EXCLUDED.permission_subgroup;

INSERT INTO public.role_mobile_permissions(role_id,permission_key,updated_at)
SELECT r.role_id,p.permission_key,CURRENT_TIMESTAMP FROM public.roles r CROSS JOIN public.mobile_permissions p
WHERE UPPER(r.role_name)='ADMIN' AND p.permission_key='ACCESS_SCHEDULER_WEB'
ON CONFLICT (role_id,permission_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.scheduler_web_runtime (
 runtime_id smallint PRIMARY KEY DEFAULT 1 CHECK (runtime_id = 1),
 enabled boolean NOT NULL DEFAULT false,
 generation uuid NOT NULL DEFAULT gen_random_uuid(),
 gateway_running boolean NOT NULL DEFAULT false,
 gateway_heartbeat_at timestamp with time zone,
 public_origin text,
 changed_by_user_id integer REFERENCES public.users(user_id) ON DELETE SET NULL,
 changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO public.scheduler_web_runtime(runtime_id,enabled) VALUES(1,false) ON CONFLICT(runtime_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.scheduler_web_sessions (
 session_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
 session_hash text NOT NULL UNIQUE,
 csrf_hash text NOT NULL,
 user_id integer NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
 auth_user_id uuid NOT NULL,
 expires_at timestamp with time zone NOT NULL,
 absolute_expires_at timestamp with time zone NOT NULL,
 created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 last_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 revoked_at timestamp with time zone
);
CREATE INDEX IF NOT EXISTS scheduler_web_sessions_user_active_idx ON public.scheduler_web_sessions(user_id,expires_at) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS public.scheduler_web_auth_attempts (
 attempt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 identifier_hash text NOT NULL,
 remote_address text,
 succeeded boolean DEFAULT false NOT NULL,
 attempted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS scheduler_web_auth_attempts_rate_idx ON public.scheduler_web_auth_attempts(identifier_hash,attempted_at DESC);

CREATE TABLE IF NOT EXISTS public.scheduler_web_idempotency (
 session_id uuid NOT NULL REFERENCES public.scheduler_web_sessions(session_id) ON DELETE CASCADE,
 idempotency_key text NOT NULL,
 operation_key text NOT NULL,
 request_hash text NOT NULL,
 response_json jsonb NOT NULL,
 created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
 PRIMARY KEY(session_id,idempotency_key)
);

ALTER TABLE public.scheduler_web_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduler_web_auth_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduler_web_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduler_web_runtime ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.scheduler_web_runtime,public.scheduler_web_sessions,public.scheduler_web_auth_attempts,public.scheduler_web_idempotency FROM PUBLIC;
