ALTER TABLE public.customer_accounts
    ADD COLUMN IF NOT EXISTS require_charge_authorization boolean NOT NULL DEFAULT false;

ALTER TABLE public.company_customization
    ADD COLUMN IF NOT EXISTS account_signature_retention_years integer NOT NULL DEFAULT 3;

ALTER TABLE public.company_customization DROP CONSTRAINT IF EXISTS company_customization_account_signature_retention_chk;
ALTER TABLE public.company_customization ADD CONSTRAINT company_customization_account_signature_retention_chk
    CHECK (account_signature_retention_years BETWEEN 1 AND 25);

CREATE TABLE IF NOT EXISTS public.customer_charge_authorizations (
    authorization_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint NOT NULL UNIQUE REFERENCES public.customer_account_transactions(transaction_id),
    customer_id integer NOT NULL REFERENCES public.customer_accounts(customer_id),
    location_id integer NOT NULL REFERENCES public.locations(location_id),
    document_type text NOT NULL,
    document_id bigint NOT NULL,
    representative_name text NOT NULL,
    signature_png bytea,
    signature_sha256 text,
    unsigned_reason text,
    captured_by_user_id integer REFERENCES public.users(user_id),
    captured_by_name text,
    device_id uuid,
    device_name text,
    captured_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    signature_expires_at timestamp with time zone NOT NULL,
    signature_purged_at timestamp with time zone,
    sync_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT customer_charge_authorizations_evidence_chk CHECK
      ((signature_png IS NOT NULL AND unsigned_reason IS NULL) OR
       (signature_png IS NULL AND NULLIF(BTRIM(unsigned_reason),'') IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS customer_charge_authorizations_customer_idx
    ON public.customer_charge_authorizations(customer_id,captured_at DESC);
CREATE INDEX IF NOT EXISTS customer_charge_authorizations_document_idx
    ON public.customer_charge_authorizations(document_type,document_id);
CREATE INDEX IF NOT EXISTS customer_charge_authorizations_expiry_idx
    ON public.customer_charge_authorizations(signature_expires_at)
    WHERE signature_png IS NOT NULL;

ALTER TABLE public.customer_charge_authorizations ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN
        REVOKE ALL ON TABLE public.customer_charge_authorizations FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN
        REVOKE ALL ON TABLE public.customer_charge_authorizations FROM authenticated;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN
        GRANT ALL ON TABLE public.customer_charge_authorizations TO service_role;
        GRANT ALL ON SEQUENCE public.customer_charge_authorizations_authorization_id_seq TO service_role;
    END IF;
END $$;
