INSERT INTO public.permissions(permission_key,permission_name,description,permission_group,permission_subgroup)
VALUES ('VIEW_DRAWER_HISTORY','View Drawer History','Allows viewing immutable drawer count and lifecycle history.','Operations','Cash Drawer')
ON CONFLICT (permission_key) DO NOTHING;

INSERT INTO public.role_permissions(role_id,permission_id)
SELECT r.role_id,p.permission_id FROM public.roles r CROSS JOIN public.permissions p
WHERE UPPER(r.role_name)='ADMIN' AND p.permission_key='VIEW_DRAWER_HISTORY'
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.cash_drawer_count_events (
    cash_drawer_count_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_drawer_session_id bigint NOT NULL REFERENCES public.cash_drawer_sessions(cash_drawer_session_id) ON DELETE RESTRICT,
    location_id integer NOT NULL REFERENCES public.locations(location_id),
    revision_no integer NOT NULL,
    event_type text NOT NULL CHECK (event_type IN ('COUNT_EDIT','CLEAR','FLOAT_CALCULATED','HANDOVER','CLOSE','CORRECTION')),
    denomination_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    float_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    counted_cash numeric(12,2) NOT NULL DEFAULT 0,
    float_total numeric(12,2) NOT NULL DEFAULT 0,
    cash_in_hand numeric(12,2) NOT NULL DEFAULT 0,
    expected_cash numeric(12,2) NOT NULL DEFAULT 0,
    complete boolean NOT NULL DEFAULT false,
    reason text,
    changed_by_user_id integer REFERENCES public.users(user_id),
    changed_by_name text,
    device_id uuid REFERENCES public.devices(device_id),
    device_name text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cash_drawer_count_events_revision_unique UNIQUE(cash_drawer_session_id,revision_no)
);

CREATE INDEX IF NOT EXISTS cash_drawer_count_events_session_time_idx
    ON public.cash_drawer_count_events(cash_drawer_session_id,revision_no DESC);
CREATE INDEX IF NOT EXISTS cash_drawer_count_events_location_time_idx
    ON public.cash_drawer_count_events(location_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.balance_sheet_drawer_sessions (
    balance_sheet_submission_id bigint NOT NULL REFERENCES public.balance_sheet_submissions(balance_sheet_submission_id) ON DELETE RESTRICT,
    cash_drawer_session_id bigint NOT NULL REFERENCES public.cash_drawer_sessions(cash_drawer_session_id) ON DELETE RESTRICT,
    snapshot_label text NOT NULL,
    snapshot_amount numeric(12,2) NOT NULL DEFAULT 0,
    PRIMARY KEY(balance_sheet_submission_id,cash_drawer_session_id)
);
CREATE INDEX IF NOT EXISTS balance_sheet_drawer_sessions_session_idx
    ON public.balance_sheet_drawer_sessions(cash_drawer_session_id,balance_sheet_submission_id);

CREATE OR REPLACE FUNCTION public.prevent_cash_drawer_count_event_changes() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Cash drawer count history is immutable'; END; $$;
DROP TRIGGER IF EXISTS cash_drawer_count_events_immutable ON public.cash_drawer_count_events;
CREATE TRIGGER cash_drawer_count_events_immutable BEFORE UPDATE OR DELETE ON public.cash_drawer_count_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_cash_drawer_count_event_changes();

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN
    ALTER TABLE public.cash_drawer_count_events ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.balance_sheet_drawer_sessions ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS cash_drawer_count_events_service_role_all ON public.cash_drawer_count_events;
    CREATE POLICY cash_drawer_count_events_service_role_all ON public.cash_drawer_count_events TO service_role USING (true) WITH CHECK (true);
    DROP POLICY IF EXISTS balance_sheet_drawer_sessions_service_role_all ON public.balance_sheet_drawer_sessions;
    CREATE POLICY balance_sheet_drawer_sessions_service_role_all ON public.balance_sheet_drawer_sessions TO service_role USING (true) WITH CHECK (true);
    GRANT ALL ON public.cash_drawer_count_events,public.balance_sheet_drawer_sessions TO service_role;
    GRANT USAGE,SELECT ON SEQUENCE public.cash_drawer_count_events_cash_drawer_count_event_id_seq TO service_role;
  END IF;
END $$;
