ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS archived_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS archived_by_user_id integer,
    ADD COLUMN IF NOT EXISTS archive_reason text;

DO $$ BEGIN
    ALTER TABLE public.products ADD CONSTRAINT products_archived_by_user_id_fkey
        FOREIGN KEY (archived_by_user_id) REFERENCES public.users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.product_lifecycle_audit (
    product_lifecycle_audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES public.products(product_id),
    action_type text NOT NULL CHECK (action_type IN ('ARCHIVE','RESTORE')),
    reason text,
    user_id integer NOT NULL REFERENCES public.users(user_id),
    device_id uuid REFERENCES public.devices(device_id),
    location_id integer NOT NULL REFERENCES public.locations(location_id),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS product_lifecycle_audit_product_idx
    ON public.product_lifecycle_audit(product_id,created_at DESC);
CREATE INDEX IF NOT EXISTS products_active_name_idx ON public.products(is_active,name);
ALTER TABLE public.product_lifecycle_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.product_lifecycle_audit FROM PUBLIC;

INSERT INTO public.permissions(permission_key,permission_name,description,permission_group,permission_subgroup,created_at)
VALUES ('PRODUCT_ARCHIVE','Archive and Restore Products','Allows globally archiving and restoring products.','Inventory','Items',CURRENT_TIMESTAMP)
ON CONFLICT(permission_key) DO UPDATE SET permission_name=EXCLUDED.permission_name,
    description=EXCLUDED.description,permission_group=EXCLUDED.permission_group,
    permission_subgroup=EXCLUDED.permission_subgroup;

INSERT INTO public.role_permissions(role_id,permission_id,updated_at)
SELECT r.role_id,p.permission_id,CURRENT_TIMESTAMP FROM public.roles r CROSS JOIN public.permissions p
WHERE UPPER(r.role_name)='ADMIN' AND p.permission_key='PRODUCT_ARCHIVE'
ON CONFLICT(role_id,permission_id) DO NOTHING;
