ALTER TABLE public.customer_accounts
    ADD COLUMN IF NOT EXISTS whatsapp_opt_in boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS whatsapp_consent_phone text,
    ADD COLUMN IF NOT EXISTS whatsapp_consent_at timestamp with time zone,
    ADD COLUMN IF NOT EXISTS whatsapp_consent_by_user_id integer REFERENCES public.users(user_id);

CREATE TABLE IF NOT EXISTS public.whatsapp_configuration (
    location_id integer PRIMARY KEY REFERENCES public.locations(location_id),
    enabled boolean NOT NULL DEFAULT false,
    phone_number_id text,
    api_version text NOT NULL DEFAULT 'v23.0',
    message_mode text NOT NULL DEFAULT 'FULL' CHECK (message_mode IN ('FULL','COMPACT','REFERENCE')),
    template_language text NOT NULL DEFAULT 'en_US',
    estimated_price_usd numeric(10,4) NOT NULL DEFAULT 0.05 CHECK (estimated_price_usd >= 0),
    monthly_budget_usd numeric(10,2) NOT NULL DEFAULT 5.00 CHECK (monthly_budget_usd >= 0),
    template_names jsonb NOT NULL DEFAULT '{}'::jsonb,
    contact_line text NOT NULL DEFAULT '',
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.whatsapp_outbox (
    whatsapp_outbox_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id integer NOT NULL REFERENCES public.locations(location_id),
    queued_by_user_id integer NOT NULL REFERENCES public.users(user_id),
    customer_id integer REFERENCES public.customer_accounts(customer_id),
    document_type text NOT NULL,
    document_id bigint NOT NULL,
    document_number text,
    recipient_phone text NOT NULL,
    message_mode text NOT NULL,
    template_name text NOT NULL,
    message_text text NOT NULL,
    estimated_cost_usd numeric(10,4) NOT NULL DEFAULT 0,
    status text NOT NULL CHECK (status IN ('SENDING','ACCEPTED','FAILED')),
    meta_message_id text,
    last_error text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS whatsapp_outbox_month_idx ON public.whatsapp_outbox(location_id, created_at, status);
CREATE INDEX IF NOT EXISTS whatsapp_outbox_document_idx ON public.whatsapp_outbox(document_type, document_id, created_at DESC);
ALTER TABLE public.whatsapp_configuration ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_outbox ENABLE ROW LEVEL SECURITY;
