CREATE TABLE IF NOT EXISTS public.custom_order_item_variant_barcodes (
    custom_variant_barcode_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_variant_id bigint NOT NULL REFERENCES public.custom_order_item_variants(custom_variant_id) ON DELETE CASCADE,
    barcode text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS custom_order_item_variant_barcodes_variant_idx
    ON public.custom_order_item_variant_barcodes(custom_variant_id);
